### PR TITLE
Fix unexpected analytics report table filter results

### LINKED ISSUE #7895: Analytics filter table shows all data when it has no results
### Describe the bug
Analytics filter isn't working as expected, the result table shows all data despite filter should return no results. Most likely a regression since the previous behaviour causes this bug https://github.com/woocommerce/woocommerce-admin/issues/7588 - "No data" returned even when there is result from filter. I tested this with WooCommerce 5.8 and WordPress 5.8.1.

### To Reproduce

1. Go to WooCommerce > Analytics > Customer
1. In the filter bar, enter a non-existing customer name and press enter
2. Observe the table is populated with default list despite it should be no result

### Actual behavior:
Analytics table is populated despite no results. 

### Screenshots
https://d.pr/i/ofAfyy 
Full Size: https://d.pr/i/ofAfyy

### Expected behavior
It should display "No data" like it did previously.

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #7895

Fix the report table logic to show `No data to display` UI when it has no results [as it did previously](https://github.com/woocommerce/woocommerce-admin/blob/0f6c86313f4f8ca27320f93553ff0de116a123e4/client/analytics/components/report-table/index.js#L588-L594).

### Screenshots

non-existing customer name 
Screen Shot 2021-12-22 at 16 22 27

existing customer name 
Screen Shot 2021-12-22 at 16 22 38

### Detailed test instructions:

1. Go to WooCommerce > Customer
2. In the filter bar, enter a non-existing customer name and press enter
3. You should see the `No data to display` message.

### CODE REVIEW

File: client/analytics/components/report-table/index.js [hunk 1]
```diff
@@ -598,7 +598,9 @@ export default compose(
 			SETTINGS_STORE_NAME
 		).getSetting( 'wc_admin', 'wcAdminSettings' );
 
-		if ( isRequesting ) {
+		const noSearchResultsFound =
```
Comment (ilyasfoo) [inline client/analytics/components/report-table/index.js:601]: Nice, thanks for declaring this as a variable!

**Review by ilyasfoo — APPROVED** [review]
Great sleuthing on the regression! This tests well, LGTM! :shipit:
