### PR TITLE
Fix/some outstanding CES bugs

### LINKED ISSUE #5468: Customer effort score: Show comments section in survey
Part of #5259

Add a section for the user to add a comment to their feedback. The section should only be displayed if the user selects "Very difficult" or "Somewhat difficult". The comment is an *optional* field - add an "Optional" label per this screenshot (decided [here](https://woostartp2.wordpress.com/2020/10/16/customer-effort-score-design-i2/#comment-1070)).

If "Neutral", "Somewhat easy", or "Very easy is selected", the comments field will not show and the effort score will be recorded on its own.

ces-update-1

The [WP core component for the text area](https://wordpress.github.io/gutenberg/?path=/story/components-textareacontrol--default) can be used, with the label bumped up to the `Subtitle small` text component to provide better hierarchy in the modal. The CES prompt question is also displayed as `Subtitle small`.

See [this P2 post](https://woostartp2.wordpress.com/2020/10/16/customer-effort-score-design-i2/).

### PR DESCRIPTION
**Pull request by becdetat**
This fixes 3 issues that were uncovered by early testing:

- a warning on the type of the `trackProps` prop coming from the settings update enqueue
- the submit label being undefined in the settings update enqueue
- comments not being included when recording the feedback

### Detailed test instructions:

1. go to the WooCommerce settings page
1. open the console to see any errors
1. change a setting
1. save the change
1. when the page reloads, the CES snackbar prompt should appear
1. click 'Give feedback'
1. note that no console errors appear
1. give a low rating, triggering the comments section to appear
1. enter a comment then send
1. note that the success snackbar content is not 'undefined'
1. there should be a tracks notice in the console, including the comments you provided
image

### CODE REVIEW

File: client/customer-effort-score-tracks/customer-effort-score-tracks.js [hunk 1]
```diff
@@ -98,10 +98,11 @@ function CustomerEffortScoreTracks( {
 		} );
 	};
 
-	const recordScore = ( score ) => {
+	const recordScore = ( score, comments ) => {
 		recordEvent( 'ces_feedback', {
 			action,
 			score,
+			comments,
```
Comment (mattsherman) [inline client/customer-effort-score-tracks/customer-effort-score-tracks.js:105]: If comments are not entered, they get sent as `undefined`... do we know if this will cause any issues actually recording to Tracks? I don't *think* so.

**Review by mattsherman — APPROVED** [review]
Nice job fixing up these outstanding issues.

Tested and things work as expected.

Just left a note about sending an `undefined` to Tracks... I don't think it will be an issue, but you may want to double-check this before merging (I ran out of time to test actually sending to Tracks in my env this morning).

File: client/customer-effort-score-tracks/customer-effort-score-tracks.js (hunk 1 above)
Comment (becdetat) [reply client/customer-effort-score-tracks/customer-effort-score-tracks.js]: I don't think so either, but I've changed this to use `''` if `comments` is falsey. Thanks :-)
