### PR TITLE
Fix navigation and WooCommerce menu ordering

### LINKED ISSUE #5331: Navigation: Analytics and Home pages out of order
The Analytics children and Home item appear out of order.  We'll need to declare order for these items in WooCommerce Admin now that https://github.com/woocommerce/navigation/pull/118 is merged in.

Screen Shot 2020-09-30 at 10 50 40 AM
Screen Shot 2020-09-30 at 10 50 36 AM

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #5331

Fixes the order of the registered items to match the designs.

This continues to use order increments of `10` to allow other items to register between if necessary.

### Screenshots
Screen Shot 2020-10-14 at 3 37 31 PM
Screen Shot 2020-10-14 at 3 37 37 PM
Screen Shot 2020-10-14 at 3 37 55 PM

### Detailed test instructions:

1. Enable the navigation feature.
1. Check that items are in the correct order (matching the Figma designs).
1. Make sure no regressions occur when the new nav is turned off.

### CODE REVIEW

File: src/Features/Analytics.php [hunk 1]
```diff
@@ -129,72 +132,83 @@ public function register_pages() {
...
 				'parent' => 'woocommerce-analytics',
 				'path'   => '/analytics/orders',
+				'order'  => 30,
 			),
 			array(
 				'id'     => 'woocommerce-analytics-products',
 				'title'  => __( 'Products', 'woocommerce-admin' ),
 				'parent' => 'woocommerce-analytics',
 				'path'   => '/analytics/products',
+				'order'  => 40,
```
Comment (psealock) [inline src/Features/Analytics.php:156]: This demo has `Products` under `Overview`, https://cdpn.io/jameskoster/debug/wvKrmwv#

File: src/Features/Analytics.php [hunk 2]
```diff
@@ -129,72 +132,83 @@ public function register_pages() {
...
 				'path'         => '/customers',
 				'is_top_level' => true,
+				'order'        => 50,
 			),
 			array(
 				'id'     => 'woocommerce-analytics-settings',
-				'title'  => __( 'Settings', 'woocommerce-admin' ),
-				'parent' => 'woocommerce-analytics',
+				'title'  => $navigation_enabled ? __( 'Analytics', 'woocommerce-admin' ) : __( 'Settings', 'woocommerce-admin' ),
+				'parent' => $navigation_enabled ? 'settings' : 'woocommerce-analytics',
```
Comment (psealock) [inline src/Features/Analytics.php:211]: Nice

File: src/Features/AnalyticsDashboard.php [hunk 3]
```diff
@@ -88,6 +88,7 @@ public function register_page() {
 				'parent'       => 'woocommerce',
 				'path'         => self::MENU_SLUG,
 				'is_top_level' => true,
+				'order'        => 1,
```
Comment (psealock) [inline src/Features/AnalyticsDashboard.php:91]: Does zero work here? I'd hate for someone to sneak into the top spot.

**Review by psealock — APPROVED** [review]
Looking and working fantastic @joshuatf. Just a few small things, pre-approving

File: src/Features/Analytics.php (hunk 1 above)
Comment (joshuatf) [reply src/Features/Analytics.php:156]: Updated- this also updates in WCA, but I assume we'd want to keep consistent.

File: src/Features/AnalyticsDashboard.php (hunk 3 above)
Comment (joshuatf) [reply src/Features/AnalyticsDashboard.php]: It does!  Updated to 0.
