### PR TITLE
Remove use of deprecated @wordpress/date getSettings()

### LINKED ISSUE #807: Javascript warning: wp.date.getSettings is deprecated
**Describe the bug**

The following appears in the development console when viewing pages like the WooCommerce Dashboard:

```
wp.date.getSettings is deprecated and will be removed from Gutenberg in 4.4. Please use wp.date.__experimentalGetSettings instead. Note: Unstable APIs are strongly discouraged to be used, and are subject to removal without notice.
```

**To Reproduce**

1. Install and activate wc-admin
2. Open your developer console
3. Navigate to wp-admin > WooCommerce > Dashboad

**Expected behavior**

Silence.

**Screenshots**

screen shot 2018-11-09 at 9 45 32 am

**Desktop (please complete the following information):**

* OS: Mojave
* Browser: Brave

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #807.

See: https://github.com/WordPress/gutenberg/pull/10636

### Detailed test instructions:

1. Install and activate wc-admin
1. Open your developer console
1. Navigate to wp-admin > WooCommerce > Dashboad
1. Verify that no `wp.date` deprecation warning is present

### CODE REVIEW

**Review by psealock — DISMISSED** [review]
LGMT, although it would be nice to remove the dependency altogether considering `__experimentalGetSettings().l10n` is our only usage.

I suppose it depends on Gutenberg's ultimate plans for `__experimentalGetSettings`.

**Comment by jeffstieler** [comment]
@psealock - agreed. See: https://github.com/woocommerce/wc-admin/pull/1039/commits/979800ebb4678fa4d00f81f3caf14a08c4b0afeb

**Review by emdashcodes — COMMENTED** [review]
The code looks good for this, and is testing well in the browser.

However, it looks like two tests are failing. Looks like maybe something needs to be defined in the test setup?

`TypeError: Cannot read property 'userLocale' of undefined.`

`Error: No locale meta information provided.`

File: client/devdocs/example.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ class Example extends Component {
 			...pkgComponents,
 			Component,
 			withState,
-			getSettings,
+			getSettings: __experimentalGetSettings,
```
Comment (ryelle) [inline client/devdocs/example.js]: I think you can remove this, since you're not using getSettings in the component anymore.

**Review by ryelle — DISMISSED** [review]
Can you also add a line to the `date/CHANGELOG.md` with a note about this fix?

**Comment by jeffstieler** [comment]
This is happening on `master` and doesn't make the tests fail:

```javascript
console.error node_modules/memize/index.js:74

Jed localization error: Error: No locale meta information provided.
```

**Comment by jeffstieler** [comment]
Thanks @ryelle @justinshreve! This is ready for another review.

**Review by timmyc — APPROVED** [review]
This is testing well for me.
