### PR TITLE
Avoid Jetpack REST API when retrieving active modules 

### LINKED ISSUE #4751: Jetpack requests causing creation of lots of `post_by_email_address` options, can crash site.
**Describe the bug**
Further info about the effects: p6JqRr-2UZ-p2

when registering REST API endpoints in WC Admin, the new Jetpack request is triggered on each pageload where REST API gets initialized, which is always. This creates a new option for each logged in user. 

\Automattic\WooCommerce\Admin\API\Init::rest_api_init
\Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller::register_routes
\Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller::get_collection_params
\Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller::get_indicator_data
\Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller::get_jetpack_modules_data does request to `GET` `/jetpack/v4/module/all`, which calls 
Jetpack_Core_API_Module_List_Endpoint->process
Jetpack_Core_API_Module_List_Endpoint->get_modules
Jetpack_Core_Json_Api_Endpoints::prepare_options_for_response
Jetpack_Core_Json_Api_Endpoints::get_remote_value('post-by-email', ...)
update_option('post_by_email_addressUSER_ID', 'NULL')

**Expected behavior**
As a strategic objective, I think we should strive for the REST API endpoints to be loaded only when needed, i.e. only when in admin (unless we want WC Admin to become also framework/API for front end, but I thought that's mostly domain for Blocks package).

When I tried to wrap `new API\Init();` in `is_admin()`, I found out that e.g. some Blocks on the front end need data store for notes, so some more work is needed to decouple things before we can remove things.

Additionally, most of the background requests in WC admin are running in context where `is_admin()` is `false` and `wp_doing_ajax()` is `false` as well, so it's not a good test for when to call the API init.

As a tactical fix for now, we can just drop doing the Jetpack requests when not in admin.

WC Admin v: 1.3-rc.2
WC version: 4.3-rc.2

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #4751. Alternative to https://github.com/woocommerce/woocommerce-admin/pull/4752.

This PR seeks to avoid using the Jetpack REST API to retrieve active modules instead of selectively loading the Performance Indicators endpoint controller (as https://github.com/woocommerce/woocommerce-admin/pull/4752 does).

### Detailed test instructions:

- Install WC & Jetpack.
- Apply changes
- Test that performance indicators are still working in the admin area:
- WooCommerce > Home (if you have the home screen feature enabled), and
- Analytics > Overview
- Disable Jetpack
- Test that performance indicators are still working in the admin area (but missing "views", "visitors"):
- WooCommerce > Home (if you have the home screen feature enabled), and
- Analytics > Overview

### Changelog Note:

Fix: unnecessary REST API usage leading to potential overflow of Jetpack option sizes.

### CODE REVIEW

File: src/API/Reports/PerformanceIndicators/Controller.php [hunk 1]
```diff
@@ -177,17 +184,43 @@ public function get_analytics_report_data() {
...
 	}
 
+	/**
+	 * Get active Jetpack modules.
+	 *
+	 * @return array List of active Jetpack module slugs.
+	 */
+	public function get_active_jetpack_modules() {
+		if ( is_null( $this->active_jetpack_modules ) ) {
+			if ( class_exists( '\Jetpack' ) ) {
```
Comment (timmyc) [inline src/API/Reports/PerformanceIndicators/Controller.php:194]: When perusing similar approaches via the wonders of opengrok :) I noticed quite a few places doing a `function_exists()` call on `active_jetpack_modules()` too. Not sure if this was due to the method being added at some point, but perhaps it would be safe to check here too just in case.

File: src/API/Reports/PerformanceIndicators/Controller.php [hunk 2]
```diff
@@ -42,6 +42,13 @@ class Controller extends \WC_REST_Reports_Controller {
 	 */
 	protected $endpoints = array();
 
+	/**
+	 * Contains a list active Jetpack module slugs.
+	 *
+	 * @var array
+	 */
+	protected $active_jetpack_modules = null;
```
Comment (timmyc) [inline src/API/Reports/PerformanceIndicators/Controller.php:50]: Really like the caching of the modules, nice.

File: src/API/Reports/PerformanceIndicators/Controller.php (hunk 1 above)
Comment (jeffstieler) [reply src/API/Reports/PerformanceIndicators/Controller.php]: Done in 4b1289ef.

File: src/API/Reports/PerformanceIndicators/Controller.php [hunk 3]
```diff
@@ -177,17 +184,43 @@ public function get_analytics_report_data() {
...
 
+	/**
+	 * Get active Jetpack modules.
+	 *
+	 * @return array List of active Jetpack module slugs.
+	 */
+	public function get_active_jetpack_modules() {
+		if ( is_null( $this->active_jetpack_modules ) ) {
+			if ( class_exists( '\Jetpack' ) && method_exists( '\Jetpack', 'get_active_modules' ) ) {
+				$this->active_jetpack_modules = \Jetpack::get_active_modules();
```
Comment (peterfabian) [inline src/API/Reports/PerformanceIndicators/Controller.php:195]: I think this can be set to `null` here if someone filters `jetpack_active_modules` and returns null, so it would get called repeatedly, but that's super edge case, I suppose.

File: src/API/Reports/PerformanceIndicators/Controller.php [hunk 4]
```diff
@@ -42,6 +42,13 @@ class Controller extends \WC_REST_Reports_Controller {
 	 */
 	protected $endpoints = array();
 
+	/**
+	 * Contains a list active Jetpack module slugs.
```
Comment (peterfabian) [inline src/API/Reports/PerformanceIndicators/Controller.php:46]: Small type: a list _of_ slugs?

File: src/API/Reports/PerformanceIndicators/Controller.php (hunk 2 above)
Comment (peterfabian) [reply src/API/Reports/PerformanceIndicators/Controller.php:50]: Agreed, seems like it gets hit ±4 times per request, so caching makes sense 👍

**Review by peterfabian — APPROVED** [review]
Besides the nitpicks I found, it seems to work fine in my testing. 👍  
No more options are getting created and home page and analytics work, with and without Jetpack. Also, it seems like a better approach than hitting the REST API code. Nice touch with the added caching.

File: src/API/Reports/PerformanceIndicators/Controller.php (hunk 4 above)
Comment (jeffstieler) [reply src/API/Reports/PerformanceIndicators/Controller.php]: Fixed in 26523280.

File: src/API/Reports/PerformanceIndicators/Controller.php (hunk 3 above)
Comment (jeffstieler) [reply src/API/Reports/PerformanceIndicators/Controller.php]: Handled in 26523280.

**Comment by timmyc** [comment]
cherry picked to `release/1.3.0-rc.2` in eb599dda11b8614961ca3c5baa16adea2f0a6533
