### PR TITLE
Handle orphaned order statuses in analytics settings.

### LINKED ISSUE #4050: Unexpected Order Statuses Included in Analytics
**Describe the bug**

Unexpected/unregistered order statuses are included in Analytics queries, resulting in incorrect totals in reports.

**To Reproduce**

Either enable a plugin that creates custom order statuses, or modify some existing order statuses to something other than the core statuses, like `wc-partial-payment`, etc.

1. Ensure that you have a few orders with non-standard statuses
1. Make sure the stats tables are up-to-date
1. Use WooCommerce > Reports to look at sales by date for a date range that includes the test orders
1. Use Analytics > Revenue to look at the same date range
1. See the discrepancies

**Expected behavior**

I expect unaccounted for order statuses to be ignored in reporting, in line with what the original core WC reporting does.

**Screenshots**

Original core report:

Screen Shot 2020-04-02 at 9 41 58 AM

New analytics:

Screen Shot 2020-04-02 at 9 41 18 AM

(Caused by 2 orders with `wc-partial-payment` and `wc-scheduled-payment` statuses from the WooCommerce Deposits extension)

**Additional context**

See Slack: p1585775805046000-slack-team-isotope

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #4050.

This PR seeks to represent all order statuses that have been synced to the order stats table in analytics settings. The current behavior is to filter out any status that isn't actively registered which becomes problematic when a custom status is excluded and then the extension registering the status is deactivated/uninstalled.

### Screenshots

Screen Shot 2020-04-08 at 3 06 39 PM

### Detailed test instructions:

- Activate the WooCommerce Deposits extension (set up a store-wide partial payment)
- Place a partial payment order
- Go to Analytics > Settings
- Exclude the "Partially Paid" order status
- Go to Analytics > Orders
- Verify the partially paid order is not shown
- Deactivate the WooCommerce Deposits extension
- Go to Analytics > Settings
- Verify the `partial-payment` order status is shown under "Unregistered statuses" and is still selected
- Go to Analytics > Orders
- Verify the partially paid order is (still) not shown

### Changelog Note:

Tweak: Change Order Status setting to be inclusive instead of exclusive (fix unexpected orders in reports).

### CODE REVIEW

File: src/Loader.php [hunk 1]
```diff
@@ -760,6 +762,21 @@ public static function get_order_statuses( $statuses ) {
...
+	 * @return array Unregistered order statuses.
+	 */
+	public static function get_unregistered_order_statuses() {
+		$registered_statuses   = wc_get_order_statuses();
+		$all_synced_statuses   = OrdersDataStore::get_all_statuses();
+		$unregistered_statuses = array_diff( $all_synced_statuses, array_keys( $registered_statuses ) );
+		$formatted_status_keys = self::get_order_statuses( array_fill_keys( $unregistered_statuses, '' ) );
+		$formatted_statuses    = array_keys( $formatted_status_keys );
+
+		return array_combine( $formatted_statuses, $formatted_statuses );
```
Comment (psealock) [inline src/Loader.php:777]: Are the readable strings not obtainable, ie "Partial payment"?

Screen Shot 2020-04-10 at 10 50 20 AM

Comment (psealock) [reply src/Loader.php:777]: Oh ok, I see the status name isn't available when the plugin is disabled.

**Review by psealock — APPROVED** [review]
Nice solution here @jeffstieler! This is working well, testing is all good, and code looks good.
