### PR TITLE
Load onboarding data when enabled or directly visiting

### LINKED ISSUE #5269: [WC 4.6 RC1] Upgrade from WC 4.5.2 to WC 4.6 RC1 doesn't seem to work correctly
**Describe the bug**

The upgrade from WC 4.5.2 to WC 4.6 RC1 doesn't seem to work correctly. I tested it twice on different brand new JN sites and got the same result both times.

**To Reproduce**

1. Crete a brand new JN site.
2. Add WooCommerce by searching the plugin directory within the site (`Plugins` section in the sidebar). 
3. Install and activate WooCommere (should be 4.5.2)
4. The OBW will start as soon as you activate WooCommerce. Select to skip the Setup Wizard so that you could go through the wizard when you switch to 4.6 RC1. 
5. Look for WooCommerce Beta Tester plugin in the plugins directory (through (`Plugins` section in the sidebar).
6. Install and activate the WooCommere Beta Tester plugin. 
7. Switch WooCommerce version from 4.5.2 to 4.6 RC1 using the WooCommerce Beta Tester plugin. 
8. You will see that no onboarding is starting and I am getting redirected to Home Screen where I see no tasks to complete (it looks as they are already completed):

Screen Shot 2020-10-02 at 6 09 34 PM

9. Enable OBW by clicking on `Help` in the top right corner. Select Setup Wizard/Enable. 
10. OBW starts, but when it gets to the Product Types section, I am seeing the following (reproduced it twice on different sites to make sure it is not a fluke):

Screen Shot 2020-10-02 at 6 17 25 PM

11. Continue button here is non-clickable so can’t move on any further.

**Expected behavior**

In step 8 of the reproduction steps, I expected to see a clear way for me to get back to onboarding. I think it should not start automatically on the switch but it should be clear where to activate it. Customers don't know that they heed to click on  `Help` or that they need to complete onboarding at all. There are also no Home Screen tasks that I expected to see after the switch since the user did not complete any of the setup steps before switching from 4.5.2 to 4.6 RC1. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

N/A. 

<hr>

cc @pmcpinto

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #5269 

This loads the data needed for onboarding when onboarding has not been skipped/completed or when it is directly visited.

Note that this is a short-term fix and works by allowing the onboarding to be directly visited via a URL.  Long-term we'll want to introduce REST APIs for this data and loading states for the components so that we don't need to rely on this much preloading.

#### Before
Screen Shot 2020-10-07 at 3 17 26 PM

#### After
Screen Shot 2020-10-07 at 3 17 23 PM

### Detailed test instructions:

1. On a fresh install, walk through the onboarding and make sure things work as expected.
1. Note that the loading screens work for the profiler at all times (no flashes of the WP admin bar prior to the profiler loading).
1. Skip or complete the profiler.
1. Set the task list to hidden `update_option( 'woocommerce_task_list_hidden', 'yes' );`
1. Visit the profiler directly. `/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard`
1. Make sure you can walk through all steps and that industries, product types, etc, are all shown.

### CODE REVIEW

File: src/Features/Onboarding.php [hunk 1]
```diff
@@ -629,26 +640,26 @@ public static function delete_themes_transient() {
...
-			$current_user                           = wp_get_current_user();
-			$settings['onboarding']['userEmail']    = esc_html( $current_user->user_email );
-			$settings['onboarding']['productTypes'] = self::get_allowed_product_types();
-			$settings['onboarding']['themes']       = self::get_themes();
-		}
+		$settings['onboarding']['activeTheme']  = get_option( 'stylesheet' );
+		$settings['onboarding']['euCountries']  = WC()->countries->get_european_union_countries();
+		$settings['onboarding']['industries']   = self::get_allowed_industries();
+		$settings['onboarding']['productTypes'] = self::get_allowed_product_types();
+		$settings['onboarding']['profile']      = $profile;
```
Comment (jeffstieler) [inline src/Features/Onboarding.php:661]: Nitpick: this line is redundant now.

**Review by jeffstieler — APPROVED** [review]
Code looks good and this tested well. :shipit:

**Comment by timmyc** [comment]
cherry picked to `release/1.6.0` in https://github.com/woocommerce/woocommerce-admin/commit/3032affb9127e526a6fb72b06e273f0cf24448e1
