### PR TITLE
Fix end date for last periods

### LINKED ISSUE #6471: Analyitcs report chart and table exclude 29th February for last month preset
**Describe the bug**
This is a follow-up to https://github.com/woocommerce/woocommerce-admin/pull/6470. Report charts and table do not include previous year's period because the primary period is used to map out the data.

**To Reproduce**

1. We need to be in March 2021
2. Have an order completed on 29th February 2020
3. Open Analytics > Revenue
4. In date range, select "Last Month" preset and compare to "Previous Year"
5. Observe that 29th February sales are excluded

**Screenshot**
image
image

**Expected behavior**
With "Last Month" preset on Feb 2021, we would expect the comparison would compare with the whole month of the previous period (i.e: **1 - 28th 2021** vs **1 - 29th 2020**).

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes woocommerce/woocommerce-admin#6471 

Fix end date for last periods. 

**Does anyone have suggestions on fixing chart data?**

The `chartDate` maps over `primaryDate`; whether last year is a leap year; February only renders 28 days.

- Create an empty date and push the item to the end of primary; since the chart is ordered by date and this is an invalid date (Feb 29, 2021) this doesn't work. 
- Perhaps mapping over whichever array has more items, secondary, or primary would work?

### Screenshots
Before
Before

After
After

### Detailed test instructions:
1. We need to be in March 2021
1. Create a completed order on 29th February 2020
1. Go to Analytics > Revenue
1. In the date range filter, select "Last Month" preset and compare to "Previous Year"
1. Observe that 29th February sales are included
1. In the date range filter, select "Last Week" preset and compare to "Previous Year"
1. Observe that the end date is the same as the current year's end date
1. In the date range filter, select "Last Quarter" preset and compare to "Previous Year"
1. Observe that the end date is the same as the selected quarter and subtract 1 year
1. In the date range filter, select "Last Year" preset and compare to "Previous Year"
1. Observe that the end date is the same as the selected year and subtract 1 year

### CODE REVIEW

**Comment by joshuatf** [comment]
@woocommerce/isotope I'm curious on the expectation here.  Would we want to show Feb 29th in the chart even though the current year does not have this date?

**Comment by becdetat** [comment]
Internal discussion here about how to handle leap years (sorry it's internal @hsingyuc but the outcome will go here): p90Yrv-2f6-p2

**Comment by joshuatf** [comment]
@becdetat Did we reach a conclusion in p90Yrv-2f6-p2?

**Comment by becdetat** [comment]
@joshuatf I believe we did, I created two tickets to cover it:

woocommerce/woocommerce#32260
woocommerce/woocommerce#32259

I think this PR can be merged without worrying about those two issues though.

File: packages/date/test/index.js [hunk 1]
```diff
@@ -572,6 +572,19 @@ describe( 'getLastPeriod', () => {
 				lastMonthkLastYearEnd.isSame( dateValue.secondaryEnd, 'day' )
 			).toBe( true );
 		} );
+
+		it( 'should return correct values on a leap year', () => {
```
Comment (joshuatf) [inline packages/date/test/index.js:576]: Thanks for these tests!

File: TESTING-INSTRUCTIONS.md [hunk 2]
```diff
@@ -3,6 +3,19 @@ Testing instructions
 
 ## Unreleased
 
+### Fix end date for last periods #6584
+1. We need to be in March 2021
```
Comment (joshuatf) [inline TESTING-INSTRUCTIONS.md:7]: This may be a little tricky to test.  Maybe we could update this to:

```suggestion
1. Update your system clock to March 2021
```

**Review by joshuatf — APPROVED** [review]
Thanks for spending the time to investigate and fix this @hsingyuc!  Left one comment on testing instructions, but this is good to merge after that a rebasing to fix merge conflicts.

File: TESTING-INSTRUCTIONS.md (hunk 2 above)
Comment (hsingyuc) [reply TESTING-INSTRUCTIONS.md]: Thank you for the feedback. The changes has been pushed.

File: readme.txt [hunk 3]
```diff
@@ -82,7 +82,6 @@ Release and roadmap notes are available on the [WooCommerce Developers Blog](htt
 - Dev: Add `woocommerce_admin_export_id` filter for customizing the export file name #7178
 - Dev: Remove old payment gateway task components #7224
 - Fix: Currency display on Orders activity card on homescreen #7181
-- Fix: Fix obsolete key property in gateway defaults #7229
```
Comment (joshuatf) [inline readme.txt:85]: Was this accidentally deleted?

**Review by joshuatf — COMMENTED** [review]
Sorry @hsingyuc, I think we'll need another rebase on this and quick edit to the readme when you can.

File: readme.txt (hunk 3 above)
Comment (hsingyuc) [reply readme.txt]: @joshuatf  Thank you for the review! I rebased the changelog.

File: changelogs/fix-6471 [hunk 4]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
```
Comment (joshuatf) [inline changelogs/fix-6471:1]: @moon0326 I'm not very familiar with the new changelogger.  Could you take a look to see if this looks okay?

File: TESTING-INSTRUCTIONS.md [hunk 5]
```diff
@@ -31,7 +44,6 @@
 3. Place an order with the product
 4. Navigate to Analytics -> Categories
 5. You should see the category.
->>>>>>> cdc813055 (Add changelog)
```
Comment (joshuatf) [inline TESTING-INSTRUCTIONS.md:34]: Thanks for the fix!

**Review by joshuatf — COMMENTED** [review]
Thanks for the rebase!  I pinged someone to verify the new changelog format since I'm not familiar with the formatting yet.

File: changelogs/fix-6471 (hunk 4 above)
Comment (joshuatf) [reply changelogs/fix-6471:1]: Change log format is good here 👍

**Comment by joshuatf** [comment]
So sorry for doing this @hsingyuc, but could you give this another rebase?  We had some failing e2e tests on our end that blocked this from being merged.

**Comment by joshuatf** [comment]
Looks good!  Thanks for the hard work on this one, @hsingyuc!
