### PR TITLE
Revenue Report: align date formats for the chart

### LINKED ISSUE #391: Chart: Error: <rect> attribute width: A negative value is not valid. ("-817")
Somehow I've gotten to a state with the numbers on my site where the following errors are shown and the chart:

image

### PR DESCRIPTION
**Pull request by greenafrican**
This PR to align the date formats in `chartData` and the `dateParser` chart prop.

It also introduces a secondary x-axis tick at the start of the month and fixes the `&pound;` HTML entity rendering in #391 

Fixes #391

### CODE REVIEW

**Comment by LevinMedia** [comment]
@greenafrican this is looking good! 

I noticed a couple interesting senarios: 

When looking at year to date, and aggregating by week, only one secondary x-axis tick is showing up:
screen shot 2018-09-12 at 4 41 10 pm

When looking at year to date by month and quarter, the primary x-axis ticks are duplicative with the secondaries: 

screen shot 2018-09-12 at 4 37 46 pm

In this case, I think it only needs one secondary x-axis tick (2018) the primary X-axis ticks would be just the month abbreviation without the abbreviated year:

screen shot 2018-09-12 at 4 49 01 pm

The same format could be used when aggregating by quarter.

File: client/components/chart/utils.js [hunk 1]
```diff
@@ -250,7 +240,10 @@ export const drawAxis = ( node, params ) => {
 		.call(
 			d3AxisBottom( xScale )
 				.tickValues( params.uniqueDates.map( d => ( params.type === 'line' ? new Date( d ) : d ) ) )
-				.tickFormat( d => params.x2Format( d instanceof Date ? d : new Date( d ) ) )
+				.tickFormat( ( d, i ) => {
+					const monthDate = d instanceof Date ? d : new Date( d );
+					return monthDate.getDate() === 1 || i === 0 ? ( d = params.x2Format( monthDate ) ) : '';
```
Comment (Aljullu) [inline client/components/chart/utils.js]: Is the assignment to `d` necessary? I think this line can be rewritten like:
```ES6
return monthDate.getDate() === 1 || i === 0 ? params.x2Format( monthDate ) : ''; 
```
