### PR TITLE
Forward `autocompleter` prop from `CompareFilter` to `Search`

### LINKED ISSUE #6890: `CompareFilter` does not forward `autocompleter` setting to the `Search`
**Describe the bug**
This is similar to the problem with `FilterPicker` https://github.com/woocommerce/woocommerce-admin/issues/6062

I'm trying to set up a `<ReportFilters>` with a custom type of options to be chosen. I'm not able to, as for custom type I have to provide `autocompleter` to the `<Search>` component, but `<CompareFilter>` does not forward this config. That results in

```
react-dom.development.js:22800 Uncaught Error: Invalid autocompleter provided to Search component, it requires a completer object when using 'custom' type.
    at Search.getAutocompleter (index.js?ver=1619021289:34783)
    at Search.render (index.js?ver=1619021289:34875)
    at finishClassComponent (react-dom.development.js:17295)
    at updateClassComponent (react-dom.development.js:17245)
    at beginWork (react-dom.development.js:18755)
    at HTMLUnknownElement.callCallback (react-dom.development.js:182)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:231)
    at invokeGuardedCallback (react-dom.development.js:286)
    at beginWork$1 (react-dom.development.js:23338)
    at performUnitOfWork (react-dom.development.js:22289)
```

**To Reproduce**

1. Create `<ReportFilters>` or `<CompareFilter>` with settings that contains a custom type.
```jsx
<ReportFilters
	  filters={ [{
	  label: 'Comparison',,
	  chartMode: 'item-comparison',
	  value: 'compare-programs',
	  settings: {
		  type: 'custom',
		  param: 'programs',
		  getLabels: () => Promise.resolve( [] ),
		  labels: {
			  helpText: 'Check at least two programs below to compare',
			  placeholder: 'Search for programs to compare'
			  title: 'Compare Programs',
			  update: 'Compare',
		  },
	  
		  autocompleter: {
			  name: 'programs',
			  options: () => Promise.resolve( arrayOfOptions ),
			  getOptionIdentifier: ( option ) => option.id,
			  getOptionLabel: ( option ) => option.name,
			  getOptionKeywords: ( option ) => [ option.name ],
			  getOptionCompletion: ( program ) => ({
				  key: program.id,
				  label: program.name,
			  }),
		  },
	  },
    ]} />
```

2. See an error

**Expected behavior**
The component should render, with a specified autocompleter.

**Screenshots**
blank screen

**Desktop (please complete the following information):**

* OS: Ubuntu 20.04.2 LTS
* Browser Chrome
* Version 80

**Smartphone (please complete the following information):**

 n/a

**Additional context**

It seems that the entire path of using any `*Filter*` component for a `type` other than predefined (`'attributes', 'categories', 'countries', 'coupons', 'customers', 'downloadIps', 'emails', 'orders', 'products', 'taxes', 'usernames', 'variableProducts', 'variations'`) is pretty abandoned.
Maybe it's worth revisiting it as a whole, no just bug-by-bug. I noticed there are some bits of code that seems to serve custom usage, but also there are some non-WP/autocompleter -compliant properties in filters config, that is not fully explained in the docs, so I'm not sure what should I stick to when adding my own options to the filter.

As an external developer using `FilterPicker` or `CompareFilter` I was thinking that having already loaded a finite list of options would make it really straightforward to configure those components to use it. But it already took me few days trying to figure out and reverse-engineer, what additional functions, and promises I need to provide in the config, what those function should return, what promises should resolve with.

### PR DESCRIPTION
**Pull request by tomalec**
_(Follow-up to https://github.com/woocommerce/woocommerce-admin/pull/6880, to make `ReportFilters support custom Search)_

- Forward `autocompleter` prop from `CompareFilter` to `Search`.
Allow, to use the `custom` type of search, previously it was complaining about lack of `autocompleter`, even though it was provided.

- Move `path` in Storybooks example to a parameter, to allow setting it in unit tests.
- Add few tests for FilterPicker. 
	- it renders the basic storybook example without throwing an error
	- it forwards `autocompleter` & `type` props

Fixes: woocommerce/woocommerce-admin#6890
Needed for:242-gh-woocommerce/google-listings-and-ads

### Accessibility

-   [x] I've tested using only a keyboard (no mouse)
-   [x] I've tested using a screen reader

No new texts or animations were introduced, existing ones behave as before.
-   [n/a] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [n/a] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Detailed test instructions:

-   Create `CompareFilter` with `type="custom"` and `autocompleter`
	```jsx
	<CompareFilter
		type: 'custom',
		autocompleter: {...} // Even the one copied from exiting ones.
	/>
	``` 
-   Check for errors.

#### Doubts:
1. I was wondering whether maybe the more sustainable and flexible solution would be to either forward all the props to allow customization of the Search element, and do not curate the list of forwarded ones.

### CODE REVIEW

File: packages/components/src/compare-filter/index.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ export class CompareFilter extends Component {
 	}
 
 	render() {
-		const { labels, type } = this.props;
+		const { labels, type, autocompleter } = this.props;
```
Comment (becdetat) [inline packages/components/src/compare-filter/index.js:94]: What do you think about changing this to `searchAutocompleter`? That could make it more obvious that it is used by search.

**Review by becdetat — APPROVED** [review]
Apart from my one comment, this works well and the code is good. Pre-approving. Thanks!

File: packages/components/src/compare-filter/index.js (hunk 1 above)
Comment (tomalec) [reply packages/components/src/compare-filter/index.js:94]: But then it would be inconsistent with `type` which is also kind of `searchType`:
```js
	/**
	 * Which type of autocompleter should be used in the Search
	 */
	type: PropTypes.string.isRequired,
	/**
	 * The custom autocompleter to be forwarded to the `Search` component.
	 */
	autocompleter: PropTypes.object,
```

and changing `type` would be a breaking change.

As mentioned [above](https://github.com/woocommerce/woocommerce-admin/pull/6911#issue-626319409) I was thinking of doing it another way around and provide all props together like:
```js
	/**
	 * Object of localized labels.
	 */
	searchProps: PropTypes.shape( {
		placeholder: PropTypes.string,
		type: PropTypes.string.isRequired,
		autocompleter: PropTypes.object,
	} ),
```
Or even accepting the entire component as a prop.

Personally, to keep the API and prop names consistent, I'd either:
1. Leave it as is, or 
2. Group all search props together.

WDYT?

**Comment by tomalec** [comment]
I'm merging it as is. `autocompleter` vs. `searchAutocompleter` discussion could be continued at woocommerce/woocommerce#32254
