### PR TITLE
Fix the onTransitionEnd callback

### LINKED ISSUE #6427: Weird animations for help/inbox activity panel
**Describe the bug**
The activity panel has a strange bounce when opening, and briefly appears again after closing.
There is also an issue for when you switch between react pages and the panel buttons change (Inbox instead of Help), when opening the panel a user can't close it again by clicking on the same button (I couldn't reproduce this on 'main'). It will only close by clicking outside off the panel somewhere.

**To Reproduce**
1. Create a new Woo store with the WC Admin 2.1 beta
2. Finish the onboarding wizard
3. Click the **Help** button in the top right, and see the bounce, click it again, and see how it closes and briefly shows the panel again.
4. (2.1 beta only) Click on **Analytics > Overview** and open the **Inbox** panel
5. Try closing the **Inbox** panel, see how it stays open

**Expected behavior**
It should open and close normally without a bounce see screen shot
Screen Recording 2021-02-23 at 11 28 07 AM

**Screenshots**
help-menu

sidebar-issue-2

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #6427 

Fix the `panelSwitching` logic settings the `'false'` to be an actual boolean was the root of the issue. Did a small other fix, which keeps the focusOutside logic working on a more consistent basis.
TESTS to come :)

### Screenshots

fix-activity-panel

### Detailed test instructions:

- Open the **WooCommerce > Home** page on wp-admin.
- Click on the Help button in the top right, and check if the panel opens and closes smoothly
- You can toggle by click on the 'help' button, or clicking outside of the panel should close it as well
- Navigate to **Analytics > Overview**
- Click on the Inbox in the top right, panel should still open and close smoothly

### CODE REVIEW

File: client/header/activity-panel/index.js [hunk 1]
```diff
@@ -86,12 +86,14 @@ export const ActivityPanel = ( { isEmbedded, query, userPreferencesData } ) => {
...
 	const closePanel = () => {
-		setCurrentTab( '' );
 		setIsPanelOpen( false );
 	};
 
 	const clearPanel = () => {
-		setIsPanelSwitching( 'false' );
+		if ( ! isPanelOpen ) {
+			setIsPanelSwitching( false );
+			setCurrentTab( '' );
```
Comment (louwie17) [inline client/header/activity-panel/index.js:95]: Setting the `currentTab` as empty here works nicer, as it would continue to show the data as the panel slides closed. Once closed it will remove the rendered items.

File: client/header/activity-panel/panel.js [hunk 2]
```diff
@@ -31,6 +31,12 @@ export const Panel = ( {
 		}
 	};
 
+	const finishTransition = ( e ) => {
+		if ( e && e.propertyName === 'transform' ) {
+			clearPanel();
```
Comment (louwie17) [inline client/header/activity-panel/panel.js:36]: Only trigger this when the propertyName is `transform`, it is triggered for several others as well.

**Comment by samueljseay** [comment]
As we discussed in Slack it looks like this might still break some of the functionality. Recording of the issues I saw:


https://user-images.githubusercontent.com/1281828/108913341-b17b1800-768e-11eb-828e-8e1207293532.mov

**Comment by louwie17** [comment]
@samueljseay the issue there was that the panel was never removed from the DOM and the `focus` wasn't re-applied.
I made some changes in https://github.com/woocommerce/woocommerce-admin/pull/6432/commits/dcf54175e6ab11245667641d6b15969fd6601428 that fixes this.

**Review by adrianduffell — APPROVED** [review]
This tested well for me, the animation was nice and smooth. Thanks @louwie17!

🚀
