### PR TITLE
Fix updating WC customer without wordpress user (if multiple orders are present)

### LINKED ISSUE #4152: Information in 'Customers' page doesn't update after order update
**Describe the bug**
In WooCommerce → Customers, information such as name or email doesn't change when an order has been updated. Neither does it update when the user's account details have been adjusted. 

**To Reproduce**
1. Go to WooCommerce → Customers, pick a customer to adjust
2. Open an order that is related to this customer in WooCommerce → Orders
3. Edit the billing details to something other than it was before 
4. Reload the Customers page in step 1, see no change

Going to Analytics → Settings and re-importing orders doesn't make a change either. Making a change to the account's name and billing information doesn't make a difference either. 

**Expected behavior**
I expect that the information in WooCommerce → Customers adheres to the customer's information in the account or in the orders. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://wootesting.local
Site address (URL): http://wootesting.local
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 15.56MB
Database Data Size: 12.46MB
Database Index Size: 3.10MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 10.44MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 6
bookable_resource: 3
follow_up_email: 3
nav_menu_item: 5
page: 10
polylang_mo: 1
post: 3
product: 26
product_variation: 17
revision: 5
shop_coupon: 1
shop_order: 20
shop_order_refund: 1
shop_subscription: 1
wc_booking: 3
wc_membership_plan: 2
wc_user_membership: 1
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.3.3
WooCommerce: by Automattic – 4.0.1

### Inactive Plugins (41) ###

AutomateWoo: by WooCommerce – 4.8.3
Classic Editor: by WordPress Contributors – 1.5
Extend WooCommerce Subscription Intervals: by Brent Shepherd – 1.0 – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.8.31
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Jetpack by WordPress.com: by Automattic – 8.4.2
Polylang: by WP SYNTEX – 2.7.1
Product Filters for WooCommerce: by Nexter – 1.1.16 – Not tested with the active version of WooCommerce
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.3.1

Storefront Pricing Tables: by WooCommerce – 1.1.0
User Switching: by John Blackbourn & contributors – 1.5.4
WooCommerce Admin: by WooCommerce – 1.0.3
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.0 – 3.1.8 is available – Not tested with the active version of WooCommerce
WooCommerce Amazon Pay: by WooCommerce – 1.11.1 – Not tested with the active version of WooCommerce
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.18 – 2.4.22 is available – Not tested with the active version of WooCommerce
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.15
WooCommerce Chained Products: by StoreApps – 2.9.5 – 2.9.6 is available – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.0 – 1.7.5 is available – Not tested with the active version of WooCommerce
WooCommerce Deposits: by WooCommerce – 1.4.19 – 1.4.20 is available
WooCommerce Memberships: by SkyVerge – 1.16.5 – 1.17.2 is available – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.13 – 2.4.15 is available – Not tested with the active version of WooCommerce
WooCommerce One Page Checkout: by Automattic – 1.7.3 – 1.7.4 is available – Not tested with the active version of WooCommerce
WooCommerce Order Delivery: by WooCommerce – 1.6.4 – 1.6.6 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.21
WooCommerce Photography: by WooCommerce – 1.0.19 – 1.0.22 is available – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.31
WooCommerce Pre-Orders: by WooCommerce – 1.5.23 – 1.5.24 is available – Not tested with the active version of WooCommerce
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.1 – 3.8.3 is available – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.24 – 3.0.30 is available – Not tested with the active version of WooCommerce
WooCommerce Product Vendors: by WooCommerce – 2.1.28 – 2.1.30 is available
WooCommerce Sequential Order Numbers: by SkyVerge – 1.9.4
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.15.1 – 1.15.2 is available – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.23.0
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.16
WooCommerce Square: by WooCommerce – 2.1.1
WooCommerce Store Credit: by WooCommerce – 3.0.4 – 3.1.2 is available – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by WooCommerce – 3.0.1 – 3.0.3 is available – Not tested with the active version of WooCommerce
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.25
WooCommerce USPS Shipping: by WooCommerce – 4.4.37 – 4.4.41 is available – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: woocommerce/woocommerce#10 - /shop/
Cart: woocommerce/woocommerce#11 - /cart/
Checkout: woocommerce/woocommerce#12 - /checkout/
My account: woocommerce/woocommerce#13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 77
Oldest: 2020-03-20 07:27:04 +0000
Newest: 2020-04-17 14:12:44 +0000

Failed: 1
Oldest: 2020-03-26 09:05:06 +0000
Newest: 2020-03-26 09:05:06 +0000

Pending: 2
Oldest: 2020-04-17 15:12:44 +0000
Newest: 2020-04-17 17:20:14 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #4152

Added a `get_last_order` function to the customer datastore that uses the customer_id instead of making use of the Wordpress user id.

### Screenshots

update-customer-order

### Detailed test instructions:

- Create two orders with an unregistered user (use incognito window)
- Create another order with a new unregistered user (use different email)
- Update this last order in **WooCommerce -> Orders** (billing info/name).
- Go to **WooCommerce -> Customers** the data of the newest customer/order should be updated.

### CODE REVIEW

File: src/API/Reports/Customers/DataStore.php [hunk 1]
```diff
@@ -626,6 +625,34 @@ public static function get_customer_id_by_user_id( $user_id ) {
...
+		$orders_table                = $wpdb->prefix . 'wc_order_stats';
+		$excluded_statuses_condition = "AND status IN ( '" . implode( "','", array_map( 'esc_sql', array_keys( wc_get_order_statuses() ) ) ) . "' )";
+
+		$last_order = $wpdb->get_var(
+			$wpdb->prepare(
+				// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
+				"SELECT order_id FROM {$orders_table}
+				WHERE customer_id = %d
+				{$excluded_statuses_condition}
+				ORDER BY order_id DESC LIMIT 1",
```
Comment (louwie17) [inline src/API/Reports/Customers/DataStore.php:645]: Similar query to `get_oldest_orders` (below), we just DESC by order id, instead of ASC.

File: src/API/Reports/Customers/DataStore.php [hunk 2]
```diff
@@ -626,6 +625,34 @@ public static function get_customer_id_by_user_id( $user_id ) {
...
+	/**
+	 * Retrieve the last order made by a customer.
+	 *
+	 * @param int $customer_id Customer ID.
+	 * @return object Order|false.
+	 */
+	public static function get_last_order( $customer_id ) {
+		global $wpdb;
+		$orders_table                = $wpdb->prefix . 'wc_order_stats';
+		$excluded_statuses_condition = "AND status IN ( '" . implode( "','", array_map( 'esc_sql', array_keys( wc_get_order_statuses() ) ) ) . "' )";
```
Comment (jeffstieler) [inline src/API/Reports/Customers/DataStore.php:637]: This variable name seems opposite of how it's being used. Do we need to filter the status here anyhow?

File: src/API/Reports/Customers/DataStore.php [hunk 3]
```diff
@@ -626,6 +625,34 @@ public static function get_customer_id_by_user_id( $user_id ) {
 		return $customer_id ? (int) $customer_id : false;
 	}
 
+	/**
+	 * Retrieve the last order made by a customer.
+	 *
+	 * @param int $customer_id Customer ID.
+	 * @return object Order|false.
```
Comment (jeffstieler) [inline src/API/Reports/Customers/DataStore.php:632]: I believe this should be `WC_Order`.

File: src/API/Reports/Customers/DataStore.php (hunk 1 above)
Comment (jeffstieler) [reply src/API/Reports/Customers/DataStore.php:645]: Of course my test order failed this case - it is the newest order (as default sorted in the dashboard by date), but it doesn't have the highest numerical ID. Perhaps we should sort using `date_created` or `date_created_gmt` here?

**Review by jeffstieler — CHANGES_REQUESTED** [review]
Some comments/questions.

File: src/API/Reports/Customers/DataStore.php (hunk 2 above)
Comment (louwie17) [reply src/API/Reports/Customers/DataStore.php:637]: Yeah I don't think the status filter is necessary given this table only contains orders anyway.

File: src/API/Reports/Customers/DataStore.php (hunk 1 above)
Comment (louwie17) [reply src/API/Reports/Customers/DataStore.php:645]: Makes sense, I will update it to sort by `date_created_gmt`. I worked off the original [get_oldest_orders](https://github.com/woocommerce/woocommerce/blob/13f429e80de7c479443fc407f0aab0eb1ac322ad/includes/data-stores/class-wc-customer-data-store.php#L327-L347) function that sorted by post id. But `date_created` indeed makes more sense.

Comment (louwie17) [reply src/API/Reports/Customers/DataStore.php]: updated all changes in https://github.com/woocommerce/woocommerce-admin/pull/5825/commits/8e87f56328dcc5a502b17b426f05bda12f4a86d3

File: src/API/Reports/Customers/DataStore.php [hunk 4]
```diff
@@ -626,6 +625,33 @@ public static function get_customer_id_by_user_id( $user_id ) {
...
+		$last_order = $wpdb->get_var(
+			$wpdb->prepare(
+				// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
+				"SELECT order_id, date_created_gmt FROM {$orders_table}
+				WHERE customer_id = %d
+				ORDER BY date_created_gmt DESC, order_id DESC LIMIT 1",
+				// phpcs:enable
+				$customer_id
+			),
+			0
```
Comment (jeffstieler) [inline src/API/Reports/Customers/DataStore.php:647]: This is the default, so it can be safely omitted.

File: tests/api/reports-customers.php [hunk 5]
```diff
@@ -550,9 +550,110 @@ public function test_sync_latest_order_customer() {
...
+		$order3->save();
+
+		WC_Helper_Queue::run_all_pending();
+
+		$result = CustomersDataStore::sync_order_customer( $order3->get_id() );
+
+		WC_Helper_Queue::run_all_pending();
+
+		// Didn't update anything.
+		$this->assertEquals( -1, $result );
```
Comment (jeffstieler) [inline tests/api/reports-customers.php:600]: Why test this? So this is correctly returning `-1` because Customer 3's address was actually updated in the call to `run_all_pending()` above?

Can we just omit lines 595-600?

**Review by jeffstieler — APPROVED** [review]
This looks good and tested well. Left some comments on some potentially superfluous code.

File: tests/api/reports-customers.php (hunk 5 above)
Comment (louwie17) [reply tests/api/reports-customers.php:600]: @jeffstieler good catch actually, the result should be `1` not `-1`, and it should of failed. It seems that assertEquals thinks both -1 and 1 are the same thing.... (I tried it with 1 and it still passed).

It is suppose to update correctly that's why I check the `$result`. The checks further down are to make sure that it indeed actually updated.

Comment (louwie17) [reply tests/api/reports-customers.php:600]: Going to use `assertTrue( 1 === $result)` instead, that seems to compare correctly.

Comment (louwie17) [reply tests/api/reports-customers.php:600]: Nvm, sorry for the many comments. I am still confused why the isEquals didn't work, but $result is suppose to return true. so the `1 ===` is not necessary.

File: tests/api/reports-customers.php [hunk 6]
```diff
@@ -545,14 +545,115 @@ public function test_sync_latest_order_customer() {
...
+		$order3->set_billing_postcode( '54321' );
+		$order3->save();
+
+		WC_Helper_Queue::run_all_pending();
+
+		$result = CustomersDataStore::sync_order_customer( $order3->get_id() );
+
+		WC_Helper_Queue::run_all_pending();
+
+		// Didn't update anything.
```
Comment (jeffstieler) [inline tests/api/reports-customers.php:599]: Still seems like this comment is the opposite of what you're asserting.

Comment (louwie17) [reply tests/api/reports-customers.php:599]: Aaah shoot, yeah I will have to remove that comment
