### PR TITLE
Fix successful gateway configuration message

### LINKED ISSUE #7250: Gateway connection message should not be concatenated
In the gateway connection, the message reads: `{gateway name} connected successfully`.  This string:

* Should not be concatenated, but instead use sprintf
* Should be updated to "configured successfully" to avoid ambiguity between the actual connection process.

https://github.com/woocommerce/woocommerce-admin/blob/ca4f3ea905e005f0eb50238c0b7b471ff65b2942/client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js#L76-L80

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #7250 

* Uses `sprintf` to insert the payment gateway title
* Updates the success message
* Updates language around the "connection" step to be "configure"

@elizaan36 do you think the language is okay here or should it be "Set up your X account" or revert to "connect?"  We're trying to differentiate configuration from actual connection that happens during oauth connection.

### Screenshots

Screen Shot 2021-06-24 at 3 29 30 PM

Screen Shot 2021-06-28 at 2 32 47 PM

### Detailed test instructions:

1. Navigate to the payment gateway task
2. Set up any gateway
3. Note the success message

### CODE REVIEW

File: client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Configure.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ export const validateFields = ( values, fields ) => {
 	return errors;
 };
 
-export const Connect = ( {
+export const Configure = ( {
```
Comment (louwie17) [inline client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Configure.js:37]: This rename seems to break a test in the `connect.js` test file, just requires a name update.

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 tested well, just left one comment on a test failure, but pre-approving.

**Comment by elizaan36** [comment]
This language looks good to me!
