### PR TITLE
Make sure hidden fields are cleared when definition changes

### LINKED ISSUE #8249: [3.2.0 beta 2] Hidden address fields are not being cleared when previous value is entered
### Describe the bug

When a user selects a country with a postal code and fills it out, but then changes the country to one that hides the postal code field. The postal code field is not cleared, causing the previous entered value to still be saved.

### To Reproduce

1. On a fresh store go to the onboarding flow
2. Select United States as address and fill out all the required fields
3. Before hitting next, change the country to Guatemala
4. Notice how the postal code field is now hidden
5. Finish the onboarding flow
6. Go to **WooCommerce > Settings** and notice how the store address still contains a postal code.

### Expected behavior

Hidden fields values should be cleared if they were previously filled if present.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #8249 

Makes sure that if a store address field is set to hidden, it is cleared if it was previously set.

### Screenshots

clear-hidden-fields

### Detailed test instructions:

1. On a fresh store go to the onboarding flow
2. Select United States as address and fill out all the required fields
3. Before hitting next, change the country to Guatemala
4. Notice how the postal code field is now hidden
5. Finish the onboarding flow
6. Go to **WooCommerce > Settings** and notice how the store address postal code is blank.

No changelog necessary given it's a new feature

### CODE REVIEW

File: client/dashboard/components/settings/general/store-address.tsx [hunk 1]
```diff
@@ -348,6 +355,26 @@ export function StoreAddress( {
...
+			storeAddressFields.forEach( ( field ) => {
+				const fieldKey = field
+					.replace( /(address)Line([0-9])/, '$1$2' )
+					.toLowerCase();
+				const props = getInputProps( field );
+				if (
+					locale[ fieldKey ] &&
+					locale[ fieldKey ].hidden &&
+					props.value &&
+					props.value.length > 0
```
Comment (mattsherman) [inline client/dashboard/components/settings/general/store-address.tsx:370]: I am super unfamiliar with TypeScript, but couldn't you do...

```
locale[ fieldKey ]?.hidden &&
props.value?.length > 0
```

**Review by mattsherman — APPROVED** [review]
Tested, works as expected.

Left one code comment with a possible improvement, but I'm totally comfortable if you want to leave it as is.

File: client/dashboard/components/settings/general/store-address.tsx (hunk 1 above)
Comment (louwie17) [reply client/dashboard/components/settings/general/store-address.tsx:370]: Yes, most likely, let me add that.

Comment (louwie17) [reply client/dashboard/components/settings/general/store-address.tsx]: @mattsherman updated here: https://github.com/woocommerce/woocommerce-admin/pull/8250/commits/655e1113234b7e25b646288111b73a01e480ec22

**Review by mattsherman — APPROVED** [review]
Thanks for making the change to use optional chaining. Re-tested and still works as expected.
