### PR TITLE
Do not truncate non-U.S notes.

### LINKED ISSUE #8018: Inbox 2.0: Don't truncate non-English notes
In https://github.com/woocommerce/woocommerce-admin/issues/8005, it was discovered our truncation handling is broken for some non-English characters.

Until that is fixed, let's temporarily prevent non-English notes being truncated so as not to create support issues with the Inbox 2.0 launch.

To determine a non-English note, a check could be made on the note’s `locale` field. This would need to be exposed in the notes REST API response however. This field could possibly be given an `experimental` prefix to discourage external use for now. 

Locales are in the format of `en_US`, so the first part of the locale needs to be matched.

| locale  | Action |
| ------------- | ------------- |
| Begins with `en`  | Truncate note  |
| Does not begin with `en`  | Do not truncate note  |

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #8018 

This PR prevents non-U.S notes from being truncated.

### Detailed test instructions:

1. Find a note with more than 320 chars.
2. Confirm the note's content gets truncated on `WooCommerce -> Home`
3. Update the note's locale to something else from the table.
4. Navigate to `WooCommerce -> Home` and confirm the note's content is not truncated.

no changelog

### CODE REVIEW

File: client/inbox-panel/index.js [hunk 1]
```diff
@@ -164,6 +164,7 @@ const INBOX_QUERY = {
 		'image',
 		'is_deleted',
 		'is_read',
+		'locale',
```
Comment (moon0326) [inline client/inbox-panel/index.js:167]: I was going to suffix locale value with `_experiment` as the issue description suggested, but the value is already available from the backend.

Comment (ilyasfoo) [reply client/inbox-panel/index.js:167]: Nice! I didn't know we can just add parameter in our query if it was already defined in backend.

File: client/inbox-panel/index.js [hunk 2]
```diff
@@ -184,7 +185,12 @@ const InboxPanel = ( { showHeader = true } ) => {
 
 			return {
 				notes: getNotes( INBOX_QUERY ).map( ( note ) => {
-					note.content = truncateRenderableHTML( note.content, 320 );
+					if ( note.locale === 'en_US' ) {
```
Comment (ilyasfoo) [inline client/inbox-panel/index.js:188]: Since we're supporting is general English, this needs to support other English variations as well. According to [translate.wordpress.org](https://translate.wordpress.org/), the official English locales are:

- en_US
- en_AU
- en_CA
- en_GB
- en_ZA

image

**Review by ilyasfoo — APPROVED** [review]
Nice work, @moon0326! Tested well. Just a comment on supporting other variations of English locale. Pre-approved!

File: client/inbox-panel/index.js (hunk 2 above)
Comment (moon0326) [reply client/inbox-panel/index.js]: Thank you so much for catching this! 👍  Updated it in https://github.com/woocommerce/woocommerce-admin/pull/8022/commits/c370bd53633a9452ad75434fc6536526d4637665

Comment (ilyasfoo) [reply client/inbox-panel/index.js]: LGTM! 🚢
