### PR TITLE
Fix a lot of pending "run_remote_notifications" scheduled actions

### LINKED ISSUE #7957: run_remote_notifications scheduled actions set to run at 0000-00-00 00:00:00
### Describe the bug
Sometimes, when scheduled actions are not running, I have found that there are several `woocommerce_admin/stored_state_setup_for_products/async/run_remote_notifications` scheduled actions with a scheduled run date/time of `0000-00-00 00:00:00`.Because these actions have an erroneous date, they will never run.

While most sites experiencing this issue are running WooCommerce Subscriptions, I cannot determine if it is definitively caused by the WC Subscriptions extension.

This issue has been identified in the following tickets:

4430159-zen
4262593-zen
4153182-zen
4370603-zen
4403657-zen
4356383-zen
4219403-zen

And here are tickets where it may be a potential issue:
4372945-zen

Thus far, the only way we've found to clear these scheduled actions are to manually run them. Often times, this is relatively easy, but there have been cases where there are hundreds or thousands of these entries that all need to be run manually.

It was recommended that I create a bug report here per the following conversation: p1636131287202500-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #7957

This PR adds a check before updating the store state to avoid many pending `woocommerce admin/stored_state_setup_for_products/async/run/remote_notifications_actions`.

### Detailed test instructions:

1. Use a fresh site
2. Go to **WooCommerce > Products**.
3. Import the [products sample data](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/sample-data/sample_products.csv)
4. Go to /wp-admin/tools.php?page=action-scheduler
5. Verify that only one pending `woocommerce_admin/stored_state_setup_for_products/async/run_remote_notifications` action is generated.
6. Wait a few minutes and refresh the page to confirm that the action is completed.
Screen Shot 2022-02-09 at 15 45 50

### CODE REVIEW

File: src/RemoteInboxNotifications/StoredStateSetupForProducts.php [hunk 1]
```diff
@@ -112,19 +108,23 @@ public static function run_on_transition_post_status( $new_status, $old_status,
...
-		self::enqueue_async_run_remote_notifications();
+		self::update_stored_state_and_run_remote_notifications();
 	}
 
 	/**
 	 * Enqueues an async action (using action-scheduler) to run remote
 	 * notifications.
 	 */
-	private static function enqueue_async_run_remote_notifications() {
+	private static function update_stored_state_and_run_remote_notifications() {
```
Comment (ilyasfoo) [inline src/RemoteInboxNotifications/StoredStateSetupForProducts.php:118]: Since we're conditionally running the remote notification, I think it's better to name it something like 
```suggestion
	private static function update_stored_state_and_possibly_run_remote_notifications() {
```

File: src/RemoteInboxNotifications/StoredStateSetupForProducts.php [hunk 2]
```diff
@@ -112,19 +108,23 @@ public static function run_on_transition_post_status( $new_status, $old_status,
...
+		$stored_state = RemoteInboxNotificationsEngine::get_stored_state();
+		if ( true === $stored_state->there_are_now_products ) {
```
Comment (ilyasfoo) [inline src/RemoteInboxNotifications/StoredStateSetupForProducts.php:120]: Maybe also add a comment on why we're doing this check, for future context

**Review by ilyasfoo — APPROVED** [review]
This tested well, thanks for fixing, @chihsuan!

I noticed something odd but not related to your change which is [`run_remote_notifications`](https://github.com/woocommerce/woocommerce-admin/blob/d6cfc7bdc6f4de883b4c720c85c0f9829c5baebd/src/RemoteInboxNotifications/StoredStateSetupForProducts.php#L40-L42) never ran during the `woocommerce_admin/stored_state_setup_for_products/async/run_remote_notifications` scheduled action hook call.

I think it may be `StoredStateSetupForProducts::init` is not called on time before the hook is executed. This may have been an issue for a long time and I don't think we need to address it for now.

I have a few comments on adding comments. Pre-approving! 🚢

File: src/RemoteInboxNotifications/StoredStateSetupForProducts.php (hunk 2 above)
Comment (chihsuan) [reply src/RemoteInboxNotifications/StoredStateSetupForProducts.php:121]: Added in 634f262a7f4eaa1b02311e34a3fb0f8aaf4e65f6.
