### PR TITLE
Making business details sticky in OBW

### LINKED ISSUE #6718: [GlobalStep] Selected values on "Business details" dropdowns fails to retain during OBW.
## Bug Description:
Selected values on "Business details" dropdowns fails to retain during OBW.

## Environment:
Woocommerce Version: WooCommerce 5.1 and 5.2 RC 1
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 86.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Go to Onboarding setup wizard.
1. setup a US based address on Store details step.
1. Select "Food and Drinks" on Industry step.
1. Select any options on Product types step.
1. Now select any values on the Business details dropdowns and click Continue.
1. Note that Free features tab opens.
1. Now go back to Business details step.
1. Observe that  "Business details" dropdown values get reset.

## Actual Result:
Selected values on "Business details" dropdowns fails to retain during OBW.

## Expected Result:
Selected values on "Business details" dropdowns should be retained during OBW.

## Video:

https://user-images.githubusercontent.com/41110392/113180576-81ff9280-926e-11eb-89b1-182a235d78f6.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://human-maple.jurassic.ninja
Site address (URL): https://human-maple.jurassic.ninja
WC Version: 5.2.0
REST API Version: ✔ 5.2.0
WC Blocks Version: ✔ 4.7.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.4
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Total Database Size: 4.99MB
Database Data Size: 3.47MB
Database Index Size: 1.52MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.34MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 8
nav_menu_item: 6
page: 14
post: 2
product: 23
product_variation: 13
revision: 6
shop_order: 4
shop_order_refund: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Query Monitor: by John Blackbourn – 3.6.7
Code Snippets: by Code Snippets Pro – 2.14.1
Companion Plugin: by Osk – 1.18
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Facebook for WooCommerce: by Facebook – 2.3.4
Gutenberg: by Gutenberg Team – 10.2.1
Jetpack by WordPress.com: by Automattic – 9.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Amazon Pay: by WooCommerce – 1.12.2 (update to version 1.13.1 is available)
WooCommerce Shipping & Tax: by Automattic – 1.25.10
WooCommerce: by Automattic – 5.2.0-RC.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 34
Oldest: 2021-03-31 07:33:30 +0000
Newest: 2021-03-31 15:59:41 +0000


### Status report information ###

Generated at: 2021-03-31 16:28:38 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by joelclimbsthings**
Fixes #6718

Refactor of the business details step in the OBW to ensure that the selected items are saved when moving forward to the "Free Details" section and then back again.

### Detailed test instructions:

-   Likely best to start out with a clean store, with OBW values uninitialized
-   Checkout branch
- Move through OBW to the business details step, and then "Free "Features"
- Before moving past "Free Features," got back to the "Business Details" tab by selecting it above
- The previously selected values should still be filled out

<!--- Please add a Changelog note

Enter a changelog note using the following CLI command `npm run changelogger -- add` and commit changes.

### CODE REVIEW

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js [hunk 1]
```diff
@@ -388,7 +395,10 @@ class BusinessDetails extends Component {
 									</Button>
 									{ hasInstallActivateError && (
 										<Button
-											onClick={ () => goToNextStep() }
+											onClick={ () => {
+												this.pushProfileUpdates();
```
Comment (joshuatf) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/index.js:399]: I think this will also need to be added to the "Continue" button.  In https://github.com/woocommerce/woocommerce-admin/issues/6718 the issue noted was anytime we switch over to the free extensions, selected options are not persisted.

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js [hunk 2]
```diff
@@ -153,6 +129,37 @@ class BusinessDetails extends Component {
 			} );
 	}
 
+	async pushProfileUpdates( additions = {} ) {
```
Comment (joshuatf) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/index.js:132]: I was a little caught off guard by this name `pushProfileUpdates`, but I get that `updateProfileItems` would create conflicts.

Maybe `persistProfileItems`?

File: TESTING-INSTRUCTIONS.md [hunk 3]
```diff
@@ -2,6 +2,14 @@
 
 ## Unreleased
 
+### Making business details sticky in OBW #7426
+
+1. Start out with fresh store
```
Comment (joshuatf) [inline TESTING-INSTRUCTIONS.md:7]:
```suggestion
1. Start out with a fresh store
```

File: TESTING-INSTRUCTIONS.md [hunk 4]
```diff
@@ -2,6 +2,14 @@
...
+2. Start the on-boarding wizard and move through to the "Business details" step
+3. Fill out items, and then hit Continue to move to "Free features" tab
```
Comment (joshuatf) [inline TESTING-INSTRUCTIONS.md:9]:
```suggestion
3. Fill out items, and then hit Continue to move to the "Free features" tab
```

File: TESTING-INSTRUCTIONS.md [hunk 5]
```diff
@@ -2,6 +2,14 @@
...
+4. Then, before hitting Continue again, click "Business details" tab above to move back to that step
```
Comment (joshuatf) [inline TESTING-INSTRUCTIONS.md:10]:
```suggestion
4. Then, before hitting Continue again, click the "Business details" tab above to move back to that step
```

**Review by joshuatf — COMMENTED** [review]
Thanks for working on this one, Joel!

Left a few nitpicky semantic comments, but I think we can also add your fix to other buttons to fully knock out the issue in https://github.com/woocommerce/woocommerce-admin/issues/6718.

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js [hunk 6]
```diff
@@ -153,6 +129,37 @@ class BusinessDetails extends Component {
...
+			other_platform_name:
+				otherPlatform === 'other' ? otherPlatformName : '',
+			product_count: productCount,
+			revenue,
+			selling_venues: sellingVenues,
+			...additions,
+		};
+
+		// Remove possible empty values like `revenue` and `other_platform`.
+		Object.keys( updates ).forEach(
```
Comment (samueljseay) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/index.js:154]: I get that reduce can be less readable but its often safer not to mutate. 

For example, now `updates` is a different structure than when it was defined above due to props being deleted, but we have no idea what the shape is. It's not great for the next person coming to this code. 

As a general rule I would avoid inline mutation in a for each because leads to danger. If we assign a new variable it's clearer and we don't need to use `delete`.

```
const finalUpdates = Object.entries(myObj).reduce((acc, [key,val]) => {
  if (val !== '') {
    return {
      ...acc,
      [key]: val
    }
  }

  return acc
}, {})
```

We could also easily turn the above example into a utility and re-use it. For example we have some collection manipulation stuff in this file: https://github.com/woocommerce/woocommerce-admin/blob/5d56f4254b3f4118337e6f4b011960a3f0cb3e20/client/lib/collections/index.js?plain=1#L29

The other upside of that is its much easier to test there that our code does what's expected, than testing it with React present.

**Review by samueljseay — COMMENTED** [review]
Just a small suggestion from me.

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js (hunk 6 above)
Comment (mattsherman) [reply client/profile-wizard/steps/business-details/flows/selective-bundle/index.js:154]: I agree that in general we should avoid mutation.

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js (hunk 1 above)
Comment (joelclimbsthings) [reply client/profile-wizard/steps/business-details/flows/selective-bundle/index.js]: Right, I _did_ have it executing on that action but must have meddled with it before committing 🤭 . Fixed.

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js (hunk 6 above)
Comment (joelclimbsthings) [reply client/profile-wizard/steps/business-details/flows/selective-bundle/index.js]: Thanks @samueljseay , to be clear this code was preexisting this PR, but I agree. Just updated 👍🏻

**Comment by joelclimbsthings** [comment]
Thanks @joshuatf , just committed those changes and updated a few things. Let me know what you think.

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js [hunk 7]
```diff
@@ -153,6 +129,47 @@ class BusinessDetails extends Component {
...
+					};
+				}
+
+				return acc;
+			},
+			{}
+		);
+
+		return updateProfileItems( finalUpdates ).catch( () => {
+			throw new Error();
```
Comment (joshuatf) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/index.js:169]: I think we'll need to handle this error, possibly by creating an error notice.  This was previously handled by the promises array, but since `persistProfileItems` is called outside of that now, we need to make sure this error is also handled properly.

**Review by joshuatf — APPROVED** [review]
Testing well and pre-approving pending adding a notice in the event of error.

Thanks for the changes, Joel!

**Review by joshuatf — APPROVED** [review]
Testing well and pre-approving pending adding a notice in the event of error.

Thanks for the changes, Joel!

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js (hunk 7 above)
Comment (joelclimbsthings) [reply client/profile-wizard/steps/business-details/flows/selective-bundle/index.js]: Thanks @joshuatf , added in https://github.com/woocommerce/woocommerce-admin/pull/7426/commits/3201eb50d1eb0794527fd3bdc1c6b78d0be93eb3.
