### PR TITLE
Redirect to shipping settings page when task is completed

### LINKED ISSUE #6387: 'Set up shipping' page does not retrieve values of previously saved shipping details
**Describe the bug**
In the 'Set up shipping' page, when you enter the shipping cost for US and Rest of the world, and save it, and then return to the 'Set up shipping' page, you would notice that the entire 'Set shipping costs' form is reset to their initial state instead of showing you the previous values you entered.

**Precondition**
1. Jetpack is installed and activated.
2. The selected 'Country/Region' in the Setup Wizard was 'United States - California' or any other US region.

**To Reproduce**

1. Go to 'Home'
4. Click on 'Set up shipping'
5. Type '1.23' in the 'Shipping cost' input box under the 'United States (US)' label.
3. Click the 'Rest of the world' toggle to toggle it on.
4. Type '4.56' in the 'Shipping cost' input box under the 'Rest of the world' label
5. Click on 'Complete task'.
6. Click on 'Set up shipping' again
7. Notice that the first 'Shipping cost' input box still shows '0.00'.
8. Notice that the 'Rest of the world' section is toggled off.
9. Click on the 'Rest of the world' toggle.
10. Notice that the 'Shipping cost' of the input box in the 'Rest of the world' section is also '0.00'.

**Expected behavior**
1. The 'Shipping cost' input box in the US section shows '1.23'.
2. The 'Shipping cost' input box in the 'Rest of the world' section shows '4.56'.
3. The 'Rest of the world' toggle is toggled 'ON'.

**Screenshots**
See screen video here:
https://user-images.githubusercontent.com/4509348/108621584-74d0d600-746e-11eb-8f2c-9b9eeeb3dcb5.mp4

**Desktop:**

* OS: Windows 10 64-bit
* Browser Firefox, Chrome
* Version FF v85.0.2 (64-bit), Chrome Version 88.0.4324.182 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #6387 

When the shipping task list is finished we redirect users to the shipping settings page instead, as suggested by @timmyc in https://github.com/woocommerce/woocommerce-admin/issues/6387#issuecomment-811476672.

### Accessibility

-   [x] I've tested using only a keyboard (no mouse)

### Screenshots

shipping-task

### Detailed test instructions:

- Create a new store, and finish the Onboarding flow
- Go to **WooCommerce > Home** and select the **Set up shipping costs** task, it should show the standard stepper
- Type some number in the 'Shipping cost' input
- Click the 'Rest of the world' toggle to toggle it on.
- Type some number in the 'Shipping cost' input box under the 'Rest of the world' label 
- Finish the set up, but don't need to install the shipping label plugin
- Once on home screen the **Set up shipping costs** task should show as finished
- Click on the task again
- It should now redirect to the shipping settings page.

### CODE REVIEW

File: client/task-list/tasks.js [hunk 1]
```diff
@@ -226,8 +227,15 @@ export function getAllTasks( {
 			title: __( 'Set up shipping costs', 'woocommerce-admin' ),
 			container: <Shipping />,
 			onClick: () => {
-				onTaskSelect( 'shipping' );
-				updateQueryString( { task: 'shipping' } );
+				if ( shippingZonesCount > 0 ) {
+					window.location = getLinkTypeAndHref( {
```
Comment (joshuatf) [inline client/task-list/tasks.js:231]: One very minor issue with this is that we can't ctrl/cmd + click to open this up in a new tab.  This would require some updates to the task list to allow links instead of click handlers, so I'm not sure it's worth the time at the moment to add this for a single task.

**Review by joshuatf — APPROVED** [review]
Looks good and is testing well.  Left a comment just to make note of a potential issue, but I don't think changes are warranted right now.

File: client/task-list/tasks.js (hunk 1 above)
Comment (louwie17) [reply client/task-list/tasks.js:231]: Yeah that would indeed be nice, there is some task list refactoring coming down the pipe, this one being the first: https://github.com/woocommerce/woocommerce-admin/pull/6787
So hopefully we could add it with that refactor.
