### PR TITLE
Fix business step auto installing

### LINKED ISSUE #7564: WC 5.7 & WC Admin 2.6 - Business Features step: auto-installing extensions who were excluded from the bundle
### Describe the bug
Google Ads and Mailchimp are being auto-installed in the business features step

### To Reproduce

1. Create a new store with WC 5.7 beta installed
2. In the store details step, select a country where we should be promoting all the extensions to make sure they're being displayed in the business features step (eg. US)
3. Complete all the steps until the business features step
4. See that we mention Google Ads and Mailchimp in the footnote but they're not included in the bundle
5. Visit the marketing task
6. See that the Google Ads and Mailchimp were installed in the business features step

### Actual behavior:
We're installing Google Ads and Mailchimp in the business features step

### Screenshots
https://www.loom.com/share/fa71c99a82e04fe4827d2828626ad9ac

### Expected behavior
Google Ads and Mailchimp should not be installed in the business features step. Just in the marketing task

Epic about this initiative: #7195

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #7564 

Makes use of the installable extensions instead of the free extensions to handle free extension state.

### Screenshots

Screen Shot 2021-08-29 at 5 07 27 PM

### Detailed test instructions:

1. Create a new store wit this branch
2. In the store details step, select a country where we should be promoting all the extensions to make sure they're being displayed in the business features step (eg. US or CA)
3. Complete all the steps until the business free features step, expand the free feature list
4. See that the footer (feature plugins will be installed: ) list matches that of the items listed with checkboxes. Google Ads and Mailchimp should not be included in the footnote.
5. Visit the marketing task
6. See that the Google Ads and Mailchimp are not installed

### CODE REVIEW

File: client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+				is_installed: false,
+			},
+		],
+	},
+];
+
+describe( 'Selective extensions bundle', () => {
+	it( 'should list installable free extensions in footer only basics', () => {
+		useSelect.mockReturnValue( {
+			freeExtensions: freeExtensions,
```
Comment (becdetat) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js:90]: @louwie17 Note that there's a lint error here

File: client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+			)
+		).not.toBeInTheDocument();
+		expect(
+			queryByText( new RegExp( pluginNames.random ) )
+		).not.toBeInTheDocument();
+	} );
+
+	it( 'should list installable extensions when dropdown is clicked', () => {
+		useSelect.mockReturnValue( {
+			freeExtensions: freeExtensions,
```
Comment (becdetat) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js:114]: and here

**Review by becdetat — APPROVED** [review]
@louwie17  Looks great and works as described. I just had two notes about link failing on CI, pre-approving 🚢

File: client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js (hunk 1 above)
Comment (louwie17) [reply client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js]: Thanks, I fixed those in https://github.com/woocommerce/woocommerce-admin/pull/7585/commits/398f46a8726ace7f7c13440b6bef6985dff495ed

**Comment by louwie17** [comment]
@moon0326 @ilyasfoo this PR will have to be included in 2.6.3, it was missed in the original release I guess.
