### PR TITLE
Fix column used to JOIN products to their categories.

### LINKED ISSUE #4492: Analytics by Category is using wrong term_taxonomy_id = category_id relation.
**Describe the bug**

I got wrong analytics report by category. After digging the code I found that there is wrong left join clause for category relations. Here it is:

https://github.com/woocommerce/woocommerce-admin/blob/41baa85d4705e58e0e8a84ce40a1cb6b0b597c1e/src/API/Reports/Categories/DataStore.php#L97

So tables are joined on `term_taxonomy_id = category_id` what is wrong as `term_taxonomy_id` may not match `category_id`.

For some reason we have mismatching `term_taxonomy_id` and `term_id` in `term_taxonomy` table.

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #4492.

Match `term_id` to `category_id` after `JOIN`ing through the term taxonomy table.

Note: I'd like to add a test for this, but that's been proving time consuming. _(looks like I'll have to directed insert into the DB to create the proper test conditions)_

### Detailed test instructions:

- Verify the accuracy of the Categories report
- Verify the accuracy of the Categories report when comparing 2+ categories
- Verify the response of `/wp-json/wc-analytics/reports/products/stats` with `?segmentby=category`
- Verify the response of `/wp-json/wc-analytics/reports/orders/stats` with `?segmentby=category`
- Verify the response of `/wp-json/wc-analytics/reports/coupons/stats` with `?segmentby=category`

### Changelog Note:

Fix: category querying in legacy WordPress installs that still have shared terms.

### CODE REVIEW

File: src/API/Reports/Categories/DataStore.php [hunk 1]
```diff
@@ -94,7 +94,9 @@ protected function add_sql_query_params( $query_args ) {
 		// join wp_order_product_lookup_table with relationships and taxonomies
 		// @todo How to handle custom product tables?
 		$this->subquery->add_sql_clause( 'left_join', "LEFT JOIN {$wpdb->term_relationships} ON {$order_product_lookup_table}.product_id = {$wpdb->term_relationships}.object_id" );
-		$this->subquery->add_sql_clause( 'left_join', "LEFT JOIN {$wpdb->wc_category_lookup} ON {$wpdb->term_relationships}.term_taxonomy_id = {$wpdb->wc_category_lookup}.category_id" );
+		// Adding this (inner) JOIN as a LEFT JOIN for ordering purposes. See comment in add_order_by_params().
+		$this->subquery->add_sql_clause( 'left_join', "JOIN {$wpdb->term_taxonomy} ON {$wpdb->term_taxonomy}.term_taxonomy_id = {$wpdb->term_relationships}.term_taxonomy_id" );
```
Comment (joshuatf) [inline src/API/Reports/Categories/DataStore.php:98]: Should this be a `join` type?

```suggestion
		$this->subquery->add_sql_clause( 'join', "JOIN {$wpdb->term_taxonomy} ON {$wpdb->term_taxonomy}.term_taxonomy_id = {$wpdb->term_relationships}.term_taxonomy_id" );
```

**Review by joshuatf — APPROVED** [review]
One minor comment, but testing well and pre-approving.  Really nice work figuring out the source of this bug. 🏅

File: src/API/Reports/Categories/DataStore.php (hunk 1 above)
Comment (jeffstieler) [reply src/API/Reports/Categories/DataStore.php:98]: It's intentionally a `left_join` for statement ordering purposes - see the comment :)

Comment (joshuatf) [reply src/API/Reports/Categories/DataStore.php:98]: Completely skipped over that comment- thanks for the explanation (and comment) here!
