### PR TITLE
Fixed Link component prop

### LINKED ISSUE #5651: Link prop warning
**Describe the bug**
There is a JS warning related to a prop we send to a `Link` component.
```
Warning: React does not recognize the `linkType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `linktype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Link)
    in Link (created by QuickLink)
    in div (created by QuickLink)
    in QuickLink (created by StoreManagementLinks)
    in div (created by QuickLinkCategory)
    in QuickLinkCategory (created by StoreManagementLinks)
    in div (created by Context.Consumer)
    in BodyUI (created by CardBody)
    in CardBody (created by StoreManagementLinks)
    in div (created by Context.Consumer)
    in CardUI (created by Card)
    in Card (created by StoreManagementLinks)
    in StoreManagementLinks (created by Layout)
    in div (created by Column)
    in Column (created by Layout)
    in div (created by Layout)
    in Layout (created by WithDispatch(Layout))
    in WithDispatch(Layout)
    in Unknown (created by WithSelect(WithDispatch(Layout)))
    in WithSelect(WithDispatch(Layout)) (created by Homescreen)
    in Homescreen
    in Unknown (created by WithSelect(Homescreen))
    in WithSelect(Homescreen)
    in Unknown (created by Controller)
    in Suspense (created by Controller)
    in Controller (created by _Layout)
    in div (created by _Layout)
    in div (created by PrimaryLayout)
    in PrimaryLayout (created by _Layout)
    in div (created by _Layout)
    in _Layout
    in Unknown (created by WithSelect(_Layout))
    in WithSelect(_Layout)
    in Unknown (created by Context.Consumer)
    in Route (created by _PageLayout)
    in Switch (created by _PageLayout)
    in Router (created by _PageLayout)
    in _PageLayout
    in Unknown
    in Unknown
    in Unknown
    in Unknown
```
It looks like we should replace the prop `linkType` with `linktype` in [this line](https://github.com/woocommerce/woocommerce-admin/blob/main/client/store-management-links/quick-link/index.js#L22).

**To Reproduce**

1. Go to the `Home` screen.
2. The console warning should be visible.

**Expected behavior**
No console warning

**Screenshots**
Captura de Pantalla 2020-11-17 a la(s) 09 59 24

**Desktop (please complete the following information):**

* OS: MacOS
* Browser chrome

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #5651

This PR fixes an error with a Link component prop name. We were sending the Link component the prop name `linkType` instead of sending `linktype`.

### Detailed test instructions:

- Go to `Home` screen.
- Verify there aren't any console warnings.

### Changelog Note:
Fix: Link component prop

### CODE REVIEW

File: client/store-management-links/quick-link/index.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ export const QuickLink = ( { icon, title, href, linkType, onClick } ) => {
 			<Link
 				onClick={ onClick }
 				href={ href }
-				linkType={ linkType }
+				linktype={ linkType }
```
Comment (jeffstieler) [inline client/store-management-links/quick-link/index.js:22]: This should be [`type`](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/link/index.js#L62), no?

**Review by jeffstieler — DISMISSED** [review]

File: client/store-management-links/quick-link/index.js (hunk 1 above)
Comment (octaedro) [reply client/store-management-links/quick-link/index.js]: Thanks @jeffstieler, nice catch! This was changed in the commit 8050514

**Review by joshuatf — APPROVED** [review]
Thanks for the fix, @octaedro!  LGTM :shipit:

**Comment by octaedro** [comment]
Cherry picked into `release/1.7.2`
