### PR TITLE
Fixed associated Order Number for refunds

### LINKED ISSUE #5867: Refunds: Associated Order Number Not Displayed
**Describe the bug**

At **Analytics > Orders**, `Refunds` do not display the originating `Order #` in the table.

**To Reproduce**

1. Go to **Analytics > Orders** and select a time period during which there was a refund.
2. Check `Order #` column to see the value missing

**Expected behavior**

I expect the original order number associated with the refund to be displayed.

**Screenshots**

Screenshot
*Link to image: https://d.pr/i/rPJj8P*

**Desktop (please complete the following information):**

* OS: macOS 
* Browser: Chrome
* Version: 87.0.4280.88

**Additional context**

<details><summary>System status</summary>
`
### WordPress Environment ###

WordPress address (URL): redacted
Site address (URL): redacted
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.25
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 7.08MB
Database Data Size: 3.38MB
Database Index Size: 3.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.28MB + Index: 0.23MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 0.19MB + Index: 0.30MB + Engine InnoDB
wp_wps_key: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wps_object_term: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 28
aw_workflow: 2
bookable_person: 2
bookable_resource: 3
customize_changeset: 1
page: 10
post: 1
product: 56
product_variation: 46
revision: 2
shop_coupon: 9
shop_order: 15
shop_order_refund: 1
shop_subscription: 1
wc_booking: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Jetpack by WordPress.com: by Automattic – 9.2.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30
WooCommerce: by Automattic – 4.8.0

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Bookings Helper: by WooCommerce – 1.0.3 – Installed version not tested with active version of WooCommerce 4.0
Code Snippets: by Code Snippets Pro – 2.14.0
WooCommerce Blocks: by Automattic – 4.0.0
WP Crontrol: by John Blackbourn & crontributors – 1.8.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: ❌ Page does not contain the shortcode.
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.9.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 78
Oldest: 2020-11-11 09:05:17 -0500
Newest: 2020-12-11 17:08:52 -0500

Pending: 3
Oldest: 2020-12-11 18:08:52 -0500
Newest: 2020-12-14 14:28:58 -0500

`
</details>

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #5867

This PR fixes the error related to not showing the associated order number when the order has a `refund` status.
This was happening in `Analytics` > `Orders` .

### Accessibility

-   [x] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader
-   [x] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots
**Before**
screenshot-constitutional-cow jurassic ninja-2021 02 23-10_36_49

**Ater this PR**
screenshot-constitutional-cow jurassic ninja-2021 02 23-10_37_36

### Detailed test instructions:

0. In a store with refunded orders.
1. Check out the `main` branch.
2. Go to `Analytics` > `Orders`
3. Set the `Date Range` filter in order to cover the refunded order date.
4. Verify the associated Order Number for refunds is not visible.

5. Check out this branch (`git checkout fix/5867`).
6. Disable the report cache. You can do it by installing and activating [this plugin](https://gist.github.com/octaedro/693f3d64c201cc061fc936adf3c64429).
7. Verify that now the associated order number and the related products are visible.
8. Verify also that there aren't any JS warnings related to an `undefined` value for `totalResults`.

### CODE REVIEW

File: client/analytics/components/report-table/index.js [hunk 1]
```diff
@@ -323,7 +323,7 @@ const ReportTable = ( props ) => {
 	const isLoading =
 		isRequesting || tableData.isRequesting || primaryData.isRequesting;
 	const totals = get( primaryData, [ 'data', 'totals' ], {} );
-	const totalResults = items.totalResults;
+	const totalResults = items.totalResults || 0;
```
Comment (octaedro) [inline client/analytics/components/report-table/index.js:326]: `totalResults` will be 0 by default in order to avoid a JS warning in the `Analytics` > `Orders` view.

File: src/API/Reports/Controller.php [hunk 2]
```diff
@@ -190,7 +190,7 @@ public function get_items( $request ) {
 	public function get_order_number( $order_id ) {
 		$order = wc_get_order( $order_id );
 
-		if ( ! $order instanceof \WC_Order ) {
+		if ( ! $order instanceof \WC_Order && ! $order instanceof \WC_Order_Refund ) {
```
Comment (octaedro) [inline src/API/Reports/Controller.php:193]: I added this code to not return `null` if the order is a refunded order.

File: src/API/Reports/Orders/DataStore.php [hunk 3]
```diff
@@ -354,6 +355,11 @@ protected function include_extended_info( &$orders_data, $query_args ) {
 			}
 
 			$mapped_data[ $product['order_id'] ]['products'][] = $product_data;
+
+			// If this product's order has another related order, it will be added to our mapped_data.
+			if ( isset( $related_orders [ $product['order_id'] ] ) ) {
+				$mapped_data[ $related_orders[ $product['order_id'] ]['order_id'] ] ['products'] [] = $product_data;
+			}
```
Comment (octaedro) [inline src/API/Reports/Orders/DataStore.php:362]: If the order is refunded, it will have a parent id and won't get products. We will use the parent id to get the original order products and show them later.

File: src/API/Reports/Orders/DataStore.php [hunk 4]
```diff
@@ -325,6 +325,7 @@ protected function normalize_order_by( $order_by ) {
 	 */
 	protected function include_extended_info( &$orders_data, $query_args ) {
 		$mapped_orders    = $this->map_array_by_key( $orders_data, 'order_id' );
+		$related_orders   = $this->get_orders_with_parent_id( $mapped_orders );
 		$products         = $this->get_products_by_order_ids( array_keys( $mapped_orders ) );
```
Comment (louwie17) [inline src/API/Reports/Orders/DataStore.php:329]: @octaedro I think we also want to pass in the `$related_orders` id's into the `get_products_by_order_ids`.
Probably just combine `array_keys( $mapped_orders )` and `array_keys( $related_orders )`.

Currently the related order products only show if the original order is part of the date range, if not it won't show the products. This might likely happen if someone ordered it a week ago and decided to return, see screenshots:

List without the original order (see no products):
Screen Shot 2021-03-02 at 4 41 08 PM

List with the original order in the date range (see the refund has products now):
Screen Shot 2021-03-02 at 4 42 23 PM

**Review by louwie17 — CHANGES_REQUESTED** [review]
@octaedro overall looks good, just ran into one issue when testing, see the inline comment, for when the original order isn't in the date range, but the refunded one is.
It should be an easy fix though.

File: src/API/Reports/Orders/DataStore.php (hunk 4 above)
Comment (octaedro) [reply src/API/Reports/Orders/DataStore.php]: Nice catch! I fixed it in the commit a523a4b

**Comment by octaedro** [comment]
Thank you @louwie17 for your review!
I addressed the suggested changes. Could you take another look at this PR?

**Review by louwie17 — APPROVED** [review]
Thanks for updating this @octaedro, it tested great 👍 
Ready to 🚢 
One last thing, not a blocker, but writing a unit test for this use case would be 🔥  😄

**Comment by octaedro** [comment]
> One last thing, not a blocker, but writing a unit test for this use case would be 🔥 😄

That's a good idea! I added the tests in the commit 6add45b

 I'd really appreciate another look @louwie17

**Comment by louwie17** [comment]
Thanks for writing the test @octaedro, looks great, appreciate it :) All good to merge 🚀
