### PR TITLE
Fix track properties and add warning for wrong track format

### LINKED ISSUE #7630: Rejected tracks event props
### Describe the bug
A number of our events are being rejected by tracks, mostly due to failed event prop types that should be in snake case instead of camel case.

It would be great to have our linter catch these event props or convert event props from camel case to snake case.

Here are **some of the events, but there may be more** and there may be different reasons for each failing:

* `wcadmin_activity_panel_visible_panels`
* `wcadmin_page_view`
* `wcadmin_analytics_table_download`
* `wcadmin_aw_workflow_before_run`
* `wcadmin_order_edit_recalc_totals`
* `wcadmin_analytics_filters_filter`

### To Reproduce

1. Go to Tracks Live View
2. Search for `wcadmin_%` and filter by rejected events (checkbox)
3. Note the event and the `etlmessage` under each event

### Actual behavior:
Events fail due to bad props.

### Expected behavior
Expected events to not be rejected.

### Tasks

- [ ] Fix Tracks events listed above in description

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #7630 

Update track properties to follow snake case format.

Cases from the original ticket:
* `wcadmin_activity_panel_visible_panels` - fixed
* `wcadmin_page_view` - looks to be an old version of WC fixed here: https://github.com/woocommerce/woocommerce-admin/pull/4533
* `wcadmin_analytics_table_download` - fixed
* `wcadmin_aw_workflow_before_run` - can't find this, triggered on `/wp-admin/admin-ajax.php?action=as_async_request_queue_runner` urls?
* `wcadmin_order_edit_recalc_totals` - in [wc core](https://github.com/woocommerce/woocommerce/blob/69203f29243ad66bdf4c7ce94cf295f38b66dce9/assets/js/admin/meta-boxes-order.js#L817-L820) [issue](https://github.com/woocommerce/woocommerce/issues/30736)
* `wcadmin_analytics_filters_filter` - fixed in previous WC version - https://github.com/woocommerce/woocommerce-admin/pull/5079

### Detailed test instructions:

-  Load this branch and run this in your console `localStorage.setItem( 'debug', 'wc-admin:*' );`
-  Check if both the event name and properties are in snake case for the events listed below:

`wcadmin_activity_panel_visible_panels`
- Go to **WooCommerce > Home** and hide the task list
- Refresh the page (you might want to add products to see at-least one of the panels)

`wcadmin_analytics_table_download`
- Go to one of the analytics tables and trigger a in browser download ( make sure there is no pagination)

- Change one of the event names to a none snake case or property key's
- A warning should show in the console.

### CODE REVIEW

File: packages/tracks/src/index.js [hunk 1]
```diff
@@ -14,8 +14,8 @@ const tracksDebug = debug( 'wc-admin:tracks' );
  * @param {string} eventName The name of the event to record, don't include the wcadmin_ prefix
  * @param {Object} eventProperties event properties to include in the event
  */
-
 export function recordEvent( eventName, eventProperties ) {
+	checkEventNameAndPropsCase( eventName, eventProperties );
```
Comment (joshuatf) [inline packages/tracks/src/index.js:18]: I'm a little hesitant to introduce this here for 2 reasons:

1. It may go unnoticed in the console.  If we can get a linting approach here, we can catch it while editing and prior to commit.
2. This appears to run in all environments (including non-dev environments).

**Review by joshuatf — COMMENTED** [review]
Thanks for tackling and auditing the events, @louwie17!

Left a comment about catching these.  I know we talked about a follow-up PR for this, but I think it would help us sniff out all the issues (though I think you caught all the current ones) and would prefer this to a console warning.

File: packages/tracks/src/index.js (hunk 1 above)
Comment (mattsherman) [reply packages/tracks/src/index.js:18]: Let's split any checking/linting out to a separate PR, so we can get the fixes merged right away.

Comment (louwie17) [reply packages/tracks/src/index.js:18]: Separating it out sounds good to me, we can further the discussion there. I was thinking about the linting approach a little more and not sure if that will work, given we pass the properties as variables sometimes in dynamically created objects, which I am not sure a linter can catch.

**Review by joshuatf — APPROVED** [review]
Testing well.  Thanks for the fixes, @louwie17!
