### PR TITLE
Empty chart message

### LINKED ISSUE #582: Chart with empty data set
If dates are selected on the Product Reports chart with no order history, an emtpy chart is shown.  This may be confusing or look broken to users.

screen shot 2018-10-18 at 4 49 57 pm

#### Options

Should we:

* Show a message or something here?  E.g., "There is no data for your selected range."
* Hide the chart
* Something else?

#### Additional context
Depends on empty product data returned from API - #581

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #582.

Updates the design of empty charts according to https://github.com/woocommerce/wc-admin/issues/582#issuecomment-459209125.

A couple of notes:
- I changed the color from `light-grey-700` to `grey-dark-300` in order to comply with the minimum contrast ratio.
- In narrow viewports (mobile) I reduced the font size of the message, otherwise it was overlapping the chart y-axis lines.

### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots
image
image

### Detailed test instructions:
- Go to the _Products_ report and select a day with no orders in the day picker.
- Verify a message `No data for the selected date range` appears in the chart.
- Reset the date selection to include some results and verify the message disappears.
- In the table, search for a product that doesn't exist, for example introduce `adfads` in the table search input.
- Verify the chart displays a message `No data for the current search`.

### CODE REVIEW

File: client/analytics/components/report-chart/index.js [hunk 1]
```diff
@@ -222,6 +228,7 @@ export default compose(
 
 		if ( query.search && ! ( query[ endpoint ] && query[ endpoint ].length ) ) {
```
Comment (psealock) [inline client/analytics/components/report-chart/index.js]: Check if the value is an array

```suggestion
		if ( query.search && ! ( Array.isArray( query[ endpoint ] ) && query[ endpoint ].length ) ) {
```

File: packages/components/src/chart/d3chart/chart.js [hunk 2]
```diff
@@ -124,6 +128,11 @@ class D3Chart extends Component {
 		const xLineScale = getXLineScale( uniqueDates, adjWidth );
 		const xScale = getXScale( uniqueDates, adjWidth, compact );
 		const xTicks = getXTicks( uniqueDates, adjWidth, mode, interval );
+
+		this.setState( {
+			isEmpty: yMax === 0,
```
Comment (psealock) [inline packages/components/src/chart/d3chart/chart.js]: I know this is likely to catch all instances for our purposes, but since we are releasing `<Chart />` as a package, it could be used for display of entirely negative numbers. Is there another check that may be more explicit?

**Review by psealock — COMMENTED** [review]
Nice, working as expected. Just a small suggestion and a comment about how `isEmpty` is derived.

File: client/analytics/components/report-chart/index.js (hunk 1 above)
Comment (joshuatf) [reply client/analytics/components/report-chart/index.js]: I think this is always returned as a comma delimited string, but if I'm wrong we'll also need to update this in all other areas.

**Review by joshuatf — APPROVED** [review]
Looks good and is testing well.  After addressing @psealock's question about a negative `yMax` I think this is good to merge.

**Comment by timmyc** [comment]
Tested this out and it is looking waaaay better then before

_Before_
zero-bar-chart

_After_
image

Nice work @Aljullu

File: client/analytics/components/report-chart/index.js (hunk 1 above)
Comment (Aljullu) [reply client/analytics/components/report-chart/index.js]: Right, like @joshuatf said, `query[ endpoint ]` is a comma-separated string.

File: packages/components/src/chart/d3chart/chart.js (hunk 2 above)
Comment (Aljullu) [reply packages/components/src/chart/d3chart/chart.js]: Good point. Currently the `<Chart />` component is not prepared to display negative values, but if at some point we want to support it, it makes sense to implement new features with that in mind.

I refactored completely the way we check whether the chart is empty in c24bbba226b2112f859fcea98afb9e31b9040e3f. This way, I could also remove the state from the component.

**Comment by Aljullu** [comment]
Thanks for the review @psealock @joshuatf @timmyc!

@psealock, would you like to take another look?

**Review by psealock — APPROVED** [review]
LGTM 🚢
