### PR TITLE
Fix inbox letters truncator to support multi characters

### LINKED ISSUE #8005: Inbox 2.0 character limit calculation support for multi-characters Unicode letters
### Describe the bug
Currently, our inbox notes HTML truncator will suffer from miscalculation when handling multi-character Unicode letters. The most common use case would be emojis, such as `🏳️‍🌈` will result in 6 characters count when in fact, it's represented as 1 letter visually. Another common use case would be languages that heavily use combining marks in their letters, such as Hindi's `अनुच्छेद` 8-characters 5 letter word.

Since we're using lodash's truncate, I should also add while it could handle the emoji case correctly, it is still susceptible to this issue as truncating the Hindi word would cut mid-way into the word.

Credits to @rjchow for discovering and surfacing the issue.

### To Reproduce

1. In your local repo, add the following test case to `client/inbox-panel/test/utils.js`:
    ```js
    test( 'it should work with multi-char letters', () => {
      const sampleWithUnicode = '<div>🏳️‍🌈</div>';
      expect( truncateRenderableHTML( sampleWithUnicode, 1 ) ).toBe(
        '<div>🏳️‍🌈</div>'
      );

      const hindiSample = '<div>अनुच्छेद</div>';
      expect( truncateRenderableHTML( hindiSample, 5 ) ).toBe(
      '<div>अनुच्छेद</div>'
      );
    } );
    ```
2. Run `npm run test:client -- client/inbox-panel/test/utils.js`
3. Observe the failed test case

### Suggestions for a fix

@rjchow also raised possible 2 ways to fix this:
1. Using the [grapheme-splitter](https://github.com/orling/grapheme-splitter) library
2. Use [polyfill for a proposed API](https://href.li/?https://www.npmjs.com/package/intl-segmenter-polyfill). However, we may have to add our own dictionaries if we use this.

I should also mention that while we can fix calculating character lengths without too much difficulty, truncating may require additional complexity since we can't simply re-combine letters after we've split them since combining marks may be lost.

Additionally, instead of using lodash's truncate, we'd also have to re-implement the truncate functionality to handle word preserving.

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #8005

This PR updates the inbox notes HTML truncator to support multi-characters.

- Added [grapheme-splitter](https://github.com/orling/grapheme-splitter) to `package.json`

### Screenshots

Screen Shot 2022-03-03 at 17 05 59

Screen Shot 2022-03-03 at 17 16 42

### Detailed test instructions:

- Change `wc-admin-wc-helper-connection` note (`src/Notes/WooSubscriptionsNotes.php`) content to 

--

`Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!͖̬̰̙̗̿̋ͥͥ̂ͣ̐́́͜͞Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!͖̬̰̙̗̿̋ͥͥ̂ͣ̐́́͜͞Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!͖̬̰̙̗̿̋ͥͥ̂ͣ̐́́͜͞Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!͖̬̰̙̗̿̋ͥͥ̂ͣ̐́́͜͞Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!̿̋ͥ`

--363 length in js

- Use a fresh site
- Go to WooCommerce > Home
- You should see the "Connect to WooCommerce.com" note with the content above without being truncated.
- Update note content in db table `wp_wc_admin_notes`with the results of `'🌷🎁😜👍🏳️‍🌈'.repeat(70)`
- You should see the truncated note.

### CODE REVIEW

File: client/inbox-panel/utils.js [hunk 1]
```diff
@@ -52,37 +73,40 @@ export function hasValidNotes( notes ) {
...
 			truncatedNode.appendChild( clone );
+			truncatedTextLength += cloneNodeLetters.length;
+			continue;
+		}
+
+		const charactersRemaining = limit - truncatedTextLength;
+		const isNodeOnlyTextContent =
+			! clone.innerHTML ||
+			clone.textContent.slice( 0, charactersRemaining ) ===
+				clone.innerHTML.slice( 0, charactersRemaining );
```
Comment (ilyasfoo) [inline client/inbox-panel/utils.js:95]: @chihsuan This is susceptible to miscalculation as it uses JS's native `slice` function which would not respect multi-letter characters

```js
let element = document.createElement('div')
element.textContent = '🏳️‍🌈🏳️‍🌈'
element.textContent.slice(0, 8)

> '🏳️‍🌈🏳'
```

File: client/inbox-panel/utils.js [hunk 2]
```diff
@@ -42,6 +43,26 @@ export function hasValidNotes( notes ) {
...
 }
 
+/**
+ * Truncates array of text characters.
+ *
+ * @param {Array} letters The letter array to truncate.
+ * @param {number} limit number of characters to limit to
+ * @param {string} separator The separator string to truncate to.
+ */
+const truncate = ( letters, limit, separator = ' ' ) => {
```
Comment (ilyasfoo) [inline client/inbox-panel/utils.js:53]: I think it'll be great to add a unit test for this function

File: client/inbox-panel/utils.js [hunk 3]
```diff
@@ -52,37 +73,40 @@ export function hasValidNotes( notes ) {
...
-					separator: ' ',
-					omission: '',
-				} );
-			} else {
-				// If it does, then we'd need to recursively run this with balance of characters remaining.
-				clone = truncateElement( clone, charactersRemaining );
-			}
-			truncatedNode.appendChild( clone );
-			// Exceeded limit at this point, safe to exit loop.
-			break;
```
Comment (ilyasfoo) [inline client/inbox-panel/utils.js:84]: Neat, thanks for simplifying this!

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Overall this tested well! I just think there may still be 1 flaw in using slice:

File: client/inbox-panel/utils.js (hunk 1 above)
Comment (chihsuan) [reply client/inbox-panel/utils.js]: Good point! I used `hasChildNodes()` to check if we should call `truncateElement` instead in https://github.com/woocommerce/woocommerce-admin/pull/8404/commits/6424de37f20f2a5e3e6609d03a77832efac5bad3. 

Although it might have an additional function call compared to checking content with `charactersRemaining`. But I think this is more simple.

File: client/inbox-panel/utils.js (hunk 2 above)
Comment (chihsuan) [reply client/inbox-panel/utils.js]: Sounds good. Added in https://github.com/woocommerce/woocommerce-admin/pull/8404/commits/ae4ec6c504fac7504bc62eae5b3ea96d44c55a8a.

**Review by ilyasfoo — APPROVED** [review]
Nice, it's working great! LGTM! 🚢 🚢

File: client/inbox-panel/utils.js (hunk 1 above)
Comment (ilyasfoo) [reply client/inbox-panel/utils.js]: Sounds good to me!
