### PR TITLE
Fix persisted queries being lost when navigating to excluded page (such as Homescreen)

### LINKED ISSUE #6581: Persisted queries lose context when navigating to excluded page in Woo navigation
**Describe the bug**
When you change the query on an Analytics report, that should persist between views. This works to some degree, but you currently lose the persisted query when navigation to a page that doesn't utilize them (ie homescreen). 

**To Reproduce**

1. Go to Analytics Report
2. Change Time period
3. Navigate to homescreen
4. Navigate back to Analytics Report
5. Notice that the time period is reset again

**Expected behavior**
Time period should remain to the period set.

**Notes**

After looking at this for the bulk of the day, I've figured out that the issue stems from the fact that the `NavigationPlugin`, where the persisted queries logic lies, is now being remounted on every history change (react navigation). This causes the persisted query state to be reset. 

After some digging, I found that this started happening after [this PR](https://github.com/woocommerce/woocommerce-admin/pull/6247) that reconfigured various parts of the app in order to consolidate logic/styles governing the Header component and the rest of the page. 

In this PR the component that the `NavigationPlugin` is rendered in was moved from it's own React root element at the base of the page, to within the Header. I believe this was to bring together the elements (header bar and navigation) that need to stay fixed on the page. Unfortunately the base router causes all content within this React root to be remounted every time the route changes. 

_Two options to address this_:
- Move the root of the NavigationPlugin _back_ out of the header and to it's own React root element. This will avoid remounting and return the original function. The downside is that the styles will be impacted and we won't be able to keep all fixed elements in the same place, as per the aforementioned PR. 
- Use some kind of persistence within the NavigationPlugin to allow the persisted query logic to not be impacted by remounts

### PR DESCRIPTION
**Pull request by joelclimbsthings**
Fixes woocommerce/woocommerce-admin#6581 

As per the original issue discussion, this PR employs one possible fix for the fact that persisted queries are no longer working as expected in the new navigation feature. 

In short, there was a change made in an [unrelated PR](https://github.com/woocommerce/woocommerce-admin/pull/6247) that resulted in the `NavigationPlugin` component being remounted on every router change, which causes the component to lose state that was being used to implement the persisted queries.

This PR resolves the issue by moving the state around persisted queries in `wp.data`. This allows us to retain the state over router changes, but not over page refreshes (which could get messy). 

### Detailed test instructions:

1. Go to Analytics Report
2. Change Time period
3. Navigate to another report
4. Notice that the time period stays the same
5. Navigate to Homescreen
6. Navigate back to Analytics Report
7. Ensure that the time period is _still_ what you set on step 2

### CODE REVIEW

File: packages/data/src/navigation/actions.js [hunk 1]
```diff
@@ -16,6 +16,13 @@ export function setMenuItems( menuItems ) {
 	};
 }
 
+export function setPersistedQuery( persistedQuery ) {
```
Comment (joshuatf) [inline packages/data/src/navigation/actions.js:19]: I would love to see these actions more "event" driven.  We haven't done a great job of this in the past when creating data stores, but I have some prior art in the nav favorties data store.

I'm thinking the event driving the persisted query might be `PAGE_LOADED` or `HISTORY_CHANGED` or a combo potentially.

File: client/layout/navigation.js [hunk 2]
```diff
@@ -22,15 +24,24 @@ import { isWCAdmin } from '../dashboard/utils';
...
 
 const NavigationPlugin = () => {
-	const [ persistedQuery, setPersistedQuery ] = useState(
-		getPersistedQuery()
-	);
+	const { persistedQuery } = useSelect( ( select ) => {
+		return {
+			persistedQuery: select(
+				NAVIGATION_STORE_NAME
+			).getPersistedQueryFromStore(),
```
Comment (joshuatf) [inline client/layout/navigation.js:31]: Can we go ahead and use this same persisted queries in other components?  Or did you want to do a follow-up PR for this?

File: client/layout/navigation.js [hunk 3]
```diff
@@ -22,15 +24,24 @@ import { isWCAdmin } from '../dashboard/utils';
...
+
+	const { setPersistedQuery } = useDispatch( NAVIGATION_STORE_NAME );
 
 	const pathIsExcluded = ( path ) =>
 		getQueryExcludedScreens().includes( getScreenFromPath( path ) );
 
 	// Update the persisted queries when history is updated
 	useEffect( () => {
+		if ( Object.keys( getPersistedQuery() ).length ) {
+			setPersistedQuery( getPersistedQuery() );
```
Comment (joshuatf) [inline client/layout/navigation.js:43]: Event driven setting resolves this, but if we do plan to use this in other components we would want to make sure this is not only set in the navigation as it could be toggled off.

File: packages/data/src/navigation/selectors.js [hunk 4]
```diff
@@ -16,3 +16,7 @@ export const getFavorites = ( state ) => {
 export const isNavigationRequesting = ( state, selector ) => {
 	return state.requesting[ selector ] || false;
 };
+
+export const getPersistedQueryFromStore = ( state ) => {
```
Comment (joshuatf) [inline packages/data/src/navigation/selectors.js:20]:
```suggestion
export const getPersistedQuery = ( state ) => {
```

`FromStore` seems a little redundant.

**Review by joshuatf — COMMENTED** [review]
This is an awesome solution, Joel.  💯 

Testing well and fixes the issue on my end.  Left a few comments about how we could structure this for use in other components.

File: packages/data/src/navigation/selectors.js (hunk 4 above)
Comment (joelclimbsthings) [reply packages/data/src/navigation/selectors.js:20]: This is actually what I originally had, but then I ended up with two separate `getPersistedQuery()` functions within the `NavigationPlugin` component (the other imported from Nav utils), which seemed confusing. So I made this one more specific.

**Comment by joelclimbsthings** [comment]
Hey @joshuatf ,

I believe I've addressed your comments primarily with 925834d9ecaab675e44fb7ef123817d844ab886c. 

Testing instructions remains the same, but everything is now managed through the data store. I had to move `addHistoryListener()` to the navigation package as well. Let me know if you had something else in mind!

File: client/layout/navigation.js (hunk 2 above)
Comment (joelclimbsthings) [reply client/layout/navigation.js:27]: I've been looking at this a bit, although there are ~22 files that reference persisted queries and I'm a little uncertain about switching everything over before I vet this revised approach. Let me know what you think.

File: packages/navigation/src/index.js [hunk 5]
```diff
@@ -197,6 +207,48 @@ export function updateQueryString(
 	getHistory().push( newPath );
 }
 
+/**
+ * Adds a listener that runs on history change.
+ *
+ * @param {Function} listener Listener to add on history change.
+ * @return {Function} Function to remove listeners.
+ */
+export const addHistoryListener = ( listener ) => {
```
Comment (joshuatf) [inline packages/navigation/src/index.js:216]: Nice decision to move this over.  I think this may be something that could potentially benefit others.

File: packages/navigation/src/index.js [hunk 6]
```diff
@@ -61,6 +61,16 @@ export const getQueryExcludedScreens = () =>
...
 
+/**
+ * Given a path, return whether it is an excluded screen
+ *
+ * @param {Object} path Path to check
+ *
+ * @return {boolean} Boolean representing whether path is excluded
+ */
+export const pathIsExcluded = ( path ) =>
+	getQueryExcludedScreens().includes( getScreenFromPath( path ) );
```
Comment (joshuatf) [inline packages/navigation/src/index.js:72]: Just thinking out loud here (and definitely not within the scope of this PR)- wondering if this should have been included screens instead of excluded.  May be hard to maintain as more WCA pages are registered.

File: packages/data/src/navigation/reducer.js [hunk 7]
```diff
@@ -25,6 +26,12 @@ const reducer = (
 				menuItems: [ ...state.menuItems, ...menuItems ],
 			};
 			break;
+		case TYPES.SET_PERSISTED_QUERY:
```
Comment (joshuatf) [inline packages/data/src/navigation/reducer.js:29]: I think we can forego the `setPersistedQuery` entirely and use the events directly here instead of creating a setter.

```suggestion
		case TYPES.ON_HISTORY_CHANGE:
		case TYPES.ON_LOAD:
```

**Review by joshuatf — COMMENTED** [review]
Fantastic work here, Joel.  Left one small change we can make to move away from setters and towards events, but this looks perfect otherwise.

File: packages/navigation/src/index.js (hunk 6 above)
Comment (joelclimbsthings) [reply packages/navigation/src/index.js:72]: 💯 . I was actually thinking this last time I was working on persisted queries, but was a little uncertain since there is a filter associated with it, `TIME_EXCLUDED_SCREENS_FILTER`, that I assume we'd still have to support.

I definitely think a whitelist would be more appropriate here.

File: packages/navigation/src/index.js (hunk 5 above)
Comment (joelclimbsthings) [reply packages/navigation/src/index.js:216]: 👍🏻

**Comment by joelclimbsthings** [comment]
Thanks @joshuatf , made that change and another tweak or two in d103563869918ec0613e2cd9f21dcf754e032b32.

File: packages/data/src/navigation/reducer.js (hunk 7 above)
Comment (joelclimbsthings) [reply packages/data/src/navigation/reducer.js]: Good call, done in d103563869918ec0613e2cd9f21dcf754e032b32

File: packages/data/src/navigation/actions.js [hunk 8]
```diff
@@ -89,6 +90,23 @@ export function removeFavoriteSuccess( favorite, error ) {
 	};
 }
 
+export function* onLoad() {
+	yield onHistoryChange();
+}
+
+export function* onHistoryChange() {
+	const persistedQuery = getPersistedQuery();
```
Comment (joshuatf) [inline packages/data/src/navigation/actions.js:98]: Just making a note here (doesn't need to be fixed for this PR), in hindsight I guess the original `getPersistedQuery` should have been something more along the lines of `getPersistedQueryFromParams`.

This may be a tiny bit confusing going forward since we have `getPersistedQuery` in the data store as well as a util method to get from params.  But we can tackle this in a follow-up.

**Review by joshuatf — APPROVED** [review]
Testing perfectly.  Really elegant solution here, Joel. 

Added a comment for a potential follow-up and it would be great to get an issue to follow-up on using this store elsewhere in the app.  But this branch LGTM 🎉 ✅ 💯

**Comment by joelclimbsthings** [comment]
Great! 🥳  Just created an issue for follow-up -> woocommerce/woocommerce#32262
