### PR TITLE
Match stock status value in CSV download to the table

### LINKED ISSUE #7283: [GlobalStep] CSV downloaded from Analytics->Stocks screen has "Stock" status as single word.
## Bug Description:
CSV downloaded from Analytics->Stocks screen has "Stock" status as single word e.g "out of stock" displayed as "outofstock" for all status for Stocks CSV.

## Environment:
Woocommerce Version : WooCommerce 5.5 RC 1 and 5.4.1
WordPress version: (v5.8 Beta 3)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Add Some Products.
1. Note that user has enabled stock for products.
1. Place orders from front end.
1. Go to Analytics->>Stocks.
1. Click on download CSV button and open the CSV.
1. Observe that "Status" of product is displayed as single word.

## Actual Result:
CSV downloaded from Analytics->Stocks screen has "Stock" status as single word .

## Expected Result:
Stock status should be appear properly in CSV.

## Screenshot:

#7283_Products_CSV_Refrence

#7283_Stock_CSV

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #7283 

This PR replaces the following status values in CSV download to match the value displayed on the table.

instock -> In stock
lowstock -> Low stock
onbackordered  On Backordered
outofstock -> Out of stock

### Detailed test instructions:

**Testing client-side**

1. Clone this branch and run `npm start`
2. Add some products and set stock value.
3. Navigate to Analytics -> Stocks
4. Click the Download button.
5. Open the downloaded file and confirm the status values match the table.

**Testing server-side**

1. Clone this branch and run `npm start`
2. Install [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) plugin
2. Add at least two products with `manage stock?` option checked in the `Inventory` tab.
3. Open `client/report/stock/table.js`. Locate `tableQuery` object. Add `per_page` value. The object should look like below with `per_page` added.

```
tableQuery={ {
	orderby: query.orderby || 'stock_status',
	order: query.order || 'asc',
	type: query.type || 'all',
	per_page: 1,
} }
```

4. Navigate to Analytics -> Stocks
5. Click the Download button.
6. Navigate to Tools -> WP Mail Log and check the recently sent email. 
7. Click the download link in the email and confirm the status value is correct.

### CODE REVIEW

File: client/analytics/report/stock/table.js [hunk 1]
```diff
@@ -25,6 +26,29 @@ class StockReportTable extends Component {
 		this.getHeadersContent = this.getHeadersContent.bind( this );
 		this.getRowsContent = this.getRowsContent.bind( this );
 		this.getSummary = this.getSummary.bind( this );
+		this.customizeStockStatusForCSVDownload();
+	}
+
+	customizeStockStatusForCSVDownload() {
+		addFilter(
+			'woocommerce_admin_report_table',
```
Comment (jeffstieler) [inline client/analytics/report/stock/table.js:34]: This filter gets passed the result of the `getRowsContent()` call. Can we just modify this line instead of using a filter? https://github.com/woocommerce/woocommerce-admin/blob/2bc265c137c45b1cf33b797f3038943d2c3845b5/client/analytics/report/stock/table.js#L146

**Review by jeffstieler — CHANGES_REQUESTED** [review]

File: client/analytics/report/stock/table.js (hunk 1 above)
Comment (moon0326) [reply client/analytics/report/stock/table.js]: Thank you @jeffstieler. That's a simpler solution 👍 Updated in https://github.com/woocommerce/woocommerce-admin/pull/7284/commits/86c75017fb2241d9f405a1fe804f88e5d0578cf9

**Comment by jeffstieler** [comment]
@moon0326 we also need to make a change here to handle server-side exports: https://github.com/woocommerce/woocommerce-admin/blob/bc41de197187a4f37597b39302fb388e1a48ebcf/src/API/Reports/Stock/Controller.php#L552

**Comment by moon0326** [comment]
> @moon0326 we also need to make a change here to handle server-side exports:
> 
> https://github.com/woocommerce/woocommerce-admin/blob/bc41de197187a4f37597b39302fb388e1a48ebcf/src/API/Reports/Stock/Controller.php#L552

Thank you @jeffstieler I wasn't aware of server-side export for the stock. I'll look into it.

**Comment by moon0326** [comment]
> @moon0326 we also need to make a change here to handle server-side exports:
> 
> https://github.com/woocommerce/woocommerce-admin/blob/bc41de197187a4f37597b39302fb388e1a48ebcf/src/API/Reports/Stock/Controller.php#L552

@jeffstieler Updated in https://github.com/woocommerce/woocommerce-admin/pull/7284/commits/d5b2b2c0582b943f9bf4e6b81236e4f29265e803

File: src/ReportCSVExporter.php [hunk 2]
```diff
@@ -209,6 +209,7 @@ public function prepare_data_to_export() {
 		$rest_server = rest_get_server();
 		$report_data = $rest_server->response_to_data( $response, true );
 		remove_filter( 'woocommerce_rest_check_permissions', '__return_true' );
+		$report_data = $this->update_stock_status_for_export( $report_data );
```
Comment (jeffstieler) [inline src/ReportCSVExporter.php:212]: I'm not sure why this route was taken - in my previous comment I linked directly to the line that needed to be changed.

**Review by jeffstieler — CHANGES_REQUESTED** [review]
I could have provided more context with my last review, my apologies.

Here's what I was thinking: https://gist.github.com/jeffstieler/867d218c9a07e6133f9fe6c91291a5cd

File: src/ReportCSVExporter.php (hunk 2 above)
Comment (moon0326) [reply src/ReportCSVExporter.php]: Thanks @jeffstieler Updated https://github.com/woocommerce/woocommerce-admin/pull/7284/commits/6cdecbaf8c560ca0c2adf096e1beb34a7f8ff240

Comment (moon0326) [reply src/ReportCSVExporter.php]: It looks like I don't have to call the parent's constructor. Removed it in https://github.com/woocommerce/woocommerce-admin/pull/7284/commits/f3f56d89f857a08c76dd919788f38bfce57a6e46

**Review by jeffstieler — APPROVED** [review]
Looks good - tested both the client and server side exports. 👍
