### PR TITLE
Fix setup wizard free features checkbox re-check itself

### LINKED ISSUE #8163: Setup wizard free features checkbox re-check itself
### Describe the bug

Reproduced this in 3.1.0-rc.1. It seems after installing extensions via free features in the business features tab, all checkboxes are automatically checked just before navigating to the next step. I confirm the plugin is not actually installed, this is only a visual bug. However, users may think it's installed along, so I think this should be prioritized.

### To Reproduce

1. Go to Business Features tab in Setup Wizard
2. Deselect all extensions and reselect only 1
3. Click continue
4. Observe the other extensions are re-selected just before it navigates to the next screen

### Expected behavior
Checkbox stays the same until the end

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #8163

This PR fixes the unexpected setup wizard free features checkbox re-check issue.

### Screenshots

Issue:

### Detailed test instructions:

1. Go to Business Features tab in Setup Wizard
2. Deselect all extensions and reselect only 1
3. Click continue
4. Observe the other extensions are **NOT** re-selected before it navigates to the next screen

### CODE REVIEW

File: client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js [hunk 1]
```diff
@@ -191,21 +191,26 @@ export const ExtensionSection = ( {
 	);
 };
 
-export const createInstallExtensionOptions = ( extensions = [] ) => {
-	const defaultInstallExtensionOptions = { install_extensions: true };
-	return extensions.reduce( ( acc, curr ) => {
-		const plugins = curr.plugins.reduce(
-			( pluginAcc, { key, selected } ) => {
-				return { ...pluginAcc, [ key ]: selected ?? true };
```
Comment (chihsuan) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js:199]: I removed the unnecessary `selected` check since it doesn't exist in the plugin object and API source.

File: client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js [hunk 2]
```diff
@@ -263,11 +268,16 @@ export const SelectiveExtensionsBundle = ( {
...
-			setInstallExtensionOptions(
-				createInstallExtensionOptions( installableExtensions )
+			setInstallExtensionOptions( ( currInstallExtensionOptions ) =>
+				createInstallExtensionOptions( {
+					installableExtensions,
+					prevInstallExtensionOptions: currInstallExtensionOptions,
+				} )
 			);
 		}
-	}, [ installableExtensions, isInstallingActivating ] );
```
Comment (chihsuan) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js:270]: The root cause is the `isInstallingActivating` will be changed after the user clicks the "Continue" button and this function call will reset the options state.

**Review by octaedro — APPROVED** [review]
Great job @chihsuan, this is testing well here and code LGTM 🚀
