### PR TITLE
Fix/5872 nav back btn color

### LINKED ISSUE #5872: Navigation: WP 5.6 duplicate "back" buttons and wrong color
With WP 5.6 there are two "back" buttons, which are also blue.

Screen Shot 2020-12-14 at 1 46 55 PM

## Deliverables

* Buttons should be white.
* Make sure there is only one "back" button and it has the correct text.
* Ensure that the button color isn't something affecting all of wc-admin and address it app-wide if it is.

### PR DESCRIPTION
**Pull request by joelclimbsthings**
Fixes #5872

~~The issue appears in this branch, which this PR is based off of: `fix/wp-components-unbundle`, from [this PR.](https://github.com/woocommerce/woocommerce-admin/pull/5753)~~

Due to recent changes in the `Navigation` component within gutenberg, we're now seeing two back buttons on root level. The original issue also reports an incorrect color for the nav links, although I haven't been able to reproduce that part. 

This PR fixes the duplicate back button.

### Screenshots

Before Fix:
image

### Detailed test instructions:

-  Check out this branch
-  Navigation to `Woocommerce -> Home`
- Ensure that only a single backbtn is displayed (unlike the screenshot above)
- Observe that the text for the back btn is "WordPress Dashboard", and it works as expected.

### CODE REVIEW

**Comment by psealock** [comment]
@joelclimbsthings, I tried to rebase this branch unsuccessfully. I'm not sure whats happened but maybe its best to start over?

File: client/navigation/components/container/index.js [hunk 1]
```diff
@@ -114,6 +114,8 @@ const Container = ( { menuItems } ) => {
 		} );
 	};
 
+	const isRootLevel = activeLevel === 'woocommerce' && rootBackUrl;
```
Comment (joshuatf) [inline client/navigation/components/container/index.js:117]: Nitpick: this variable name may be slightly misleading (just worried someone else may try to reuse it without noticing the `rootBackUrl` at the end.

Maybe `isRootBackVisible` or something along those lines.

**Review by joshuatf — APPROVED** [review]
Testing and working well for me.  One nitpick, but pre-approving.

Also had trouble rebasing, but a fresh branch and `git cherry-pick 513dc05e6fecdc67ceb5f7520404a34915bd3f06` does the trick.

File: client/navigation/components/container/index.js (hunk 1 above)
Comment (joelclimbsthings) [reply client/navigation/components/container/index.js]: Good call, fixed :+1:
