### PR TITLE
Usage of URLSearchParams breaks in IE11

### LINKED ISSUE #4497: Inbox: Usage of URLSearchParams breaks in IE11
**Describe the bug**
While testing out the inbox panel in the home screen in IE11, the page loads initially, but an exception is thrown:

image

Which is due to, TIL, that IE does not have support for this method: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

The usage was introduced in the inbox refactor #4218 cc @octaedro 

**To Reproduce**

Using IE11

1. Go to the home page
2. Once inbox beings to load data, the error should occur

**Desktop (please complete the following information):**

* Browser IE11

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #4497

This PR removes the method `URLSearchParams` (not compatible with IE 11) to use something compatible.
This method was used on the new `Inbox notes` and on the `layout controller`.

### Detailed test instructions:
- Using IE 11.
- Go to `WooCommerce`| `Documentation` | `search-list-control` (URL `/wp-admin/admin.php?page=wc-admin&path=%2Fdevdocs&component=search-list-control`)
- Verify the page loaded normally.
- Press the `Inbox` button that is in the header.
- Verify the error `'URLSearchParams' is undefined ` is not present in the console.

### Changelog Note:
Fix: Removed URLSearchParams method

### CODE REVIEW

File: client/layout/controller.js [hunk 1]
```diff
@@ -50,13 +50,24 @@ export const getPages = ( homepageEnabled ) => {
 	const pages = [];
 	const initialBreadcrumbs = [ [ '', wcSettings.woocommerceTranslation ] ];
 
+	const getUrlParams = ( locationSearch ) =>
```
Comment (timmyc) [inline client/layout/controller.js:53]: Instead of having this code twice, what do you think about extracting it to a util method and adding some tests around it?

Comment (octaedro) [reply client/layout/controller.js]: It's a great idea @timmyc!
As it will be a `util` used in the header and in the layout components, I created a new folder `client/utils` to keep the utils that are used by different pages of the client.
If you think that it should be different just let me know and I will change it.
Also I added some tests 🙂
The changes are in the commit 9e81c5a

**Review by timmyc — APPROVED** [review]
Verified the fix in IE11 on browserstack. Thanks for creating the util and adding tests @octaedro
