### PR TITLE
Fix/8251 woocommerce payments task list logic

### LINKED ISSUE #8251: Store setup - WooCommerce Payment Flow
### Describe the bug
While setting up the store, I clicked on “Get paid with WooCommerce Payments” from the checklist on the home page and completed the flow. 

image

But once I finished the flow, I was redirected to an error page that stated “Sorry, you’re not allowed to access this page”.

image

In addition to that, the "Set up payment" task was still marked as a to-do and the task “Set up additional payment providers” from the section “Things to do next” disappeared (never dismissed). I double-checked in the settings and WooCommerce Payment was enabled correctly. 

image

### To Reproduce

1. Go to 'Home Page'
2. Click on 'Get paid with WooCommerce Payment'
3. Complete the flow
4. See the error message once completed the flow
5. Go to 'Home Page' and see the unchecked task + “Set up additional payment providers” disappeared.

### Expected behavior
Once completed the flow, the user is supposed to be addressed to the home page and see the WooCommerce Payment task as done.
The “Set up additional payment providers” from the section “Things to do next” is not supposed to disappear if not dismissed by the user.

### Desktop (please complete the following information):

* MacOS Monterey
* Chrome

CC @pmcpinto

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #8251

These changes refactor the task list logic to allow for more customizability and allowing task lists to share tasks.
Here are the specific changes:
- Removing the use of `getParentId` in the individual tasks to determine which task list they are part of. This function is still present, but now links back to it's `parent` task list.
- Task lists now define which tasks they contain and each individual task has a reference to it's parent task list (see `$task_list`).
- Instead of relying on the task list `ids` for track events, each task list has a `prefix_event` function that handles this, and a `event_prefix` is passed in the json to the front-end to make use of that instead of an `id` and specific logic there.
- Two extra task lists are added for the experimental task list (`setup_two_column` and `extended_two_column`, these mostly make use of the already present tasks ), currently these are filtered on the front-end, but in theory we could move that logic to the back-end and filter them upon request, I decided not to do this yet, because it will require the explat experiment logic to be moved as well, which is already working well on the front-end (and testing it on the front end is easier when it comes to explat). Having said that, we should move it, as it will keep our front-end a lot cleaner, and we already have a `is_visible` function for task lists which would make this pretty straight forward.
- I added an extra param for `ids` to the task list endpoint, if we wanted to keep the experiments client facing, then we could more easily filter which tasks we want. I was going to make heavier use of this, but then I didn't because it would make the task list show up slightly later given it has to wait for the experiment to load first.

### Detailed test instructions:

- Install the latest of [WooCommerce Admin test helper](https://github.com/woocommerce/woocommerce-admin-test-helper)
- Walk through our current task list and make sure tasks are being completed correctly and the necessary tracks are being fired, you can check for task list related tracks in the tracks-* log added by the WC Admin test helper.
- Hide the task list and extended one, and make sure you can show them again through the `help` menu (anywhere but the WooCommerce Home page)
- Now follow the same steps as above for the experimental task list, to quickly show this, you can run this in your console -> `localStorage.setItem('explat-experiment--woocommerce_tasklist_progression_headercard_2022_02', '{"experimentName":"woocommerce_tasklist_progression_headercard_2022_02","variationName":"treatment","retrievedTimestamp":' + Date.now() + ',"ttl":7200}');`

### CODE REVIEW

File: client/homescreen/layout.js [hunk 1]
```diff
@@ -337,7 +337,7 @@ export default compose(
 			shouldShowWelcomeModal,
 			shouldShowWelcomeFromCalypsoModal,
 			isTaskListHidden: getTaskList( 'setup' )?.isHidden,
-			hasTaskList: taskLists.find( ( list ) => list.isVisible ),
+			hasTaskList: !! taskLists.find( ( list ) => list.isVisible ),
```
Comment (louwie17) [inline client/homescreen/layout.js:340]: Unrelated to the bulk of this PR, but I alway notice a warning on the home page that `hasTaskList` expects a boolean, but instead got an object, this fixes that.

File: packages/data/src/onboarding/reducer.js [hunk 2]
```diff
@@ -28,24 +28,30 @@ export const defaultState = {
 	paymentMethods: [],
 	productTypes: [],
 	requesting: {},
-	taskLists: [],
+	taskLists: {},
```
Comment (louwie17) [inline packages/data/src/onboarding/reducer.js:31]: Updated this to be a key/value store to make retrieving individual task lists easier and also make it easier if we are requesting individual task lists.

File: packages/data/src/onboarding/resolvers.js [hunk 3]
```diff
@@ -71,6 +71,10 @@ export function* getTaskLists() {
 	}
 }
 
+export function* getTaskListsByIds() {
+	yield resolveSelect( STORE_NAME, 'getTaskLists' );
```
Comment (louwie17) [inline packages/data/src/onboarding/resolvers.js:75]: Making use of the `getTaskLists` resolver for now, this does retrieve every task list. This could be changed if we wanted to be more specific.

File: packages/data/src/onboarding/selectors.ts [hunk 4]
```diff
@@ -16,27 +21,42 @@ export const getProfileItems = (
...
-export const getTaskLists = ( state: OnboardingState ): TaskListType[] => {
-	return state.taskLists || initialTaskLists;
-};
+
+export const getTaskLists = createSelector(
+	( state: OnboardingState ): TaskListType[] => {
+		return Object.values( state.taskLists );
+	},
+	( state: OnboardingState ) => [ state.taskLists ]
+);
```
Comment (louwie17) [inline packages/data/src/onboarding/selectors.ts:31]: Making use of `createSelector` here to keep memoization.

**Review by jacob-sewell — APPROVED** [review]
Tested as described, everything looks good.
