### PR TITLE
Fix payments extensions displayed below the offline payments options

### LINKED ISSUE #8230: Payments task: display the offline options always below the extensions
### Describe the bug
In some countries, at least one payments extension is displayed below the offline payments options. 

### To Reproduce

1. Create a new store
2. Select India or Australia as country
3. Visit the Payments task
4. See that one of the payment extension is displayed below the offline payments options

### Actual behavior:
Some payment extensions are being displayed below the CoD and Direct Bank Transfer options

### Expected behavior
To show the offline payments options always below the payments extensions

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #8230

Sort the payment gateways by the "plugins" property to ensure the offline payments options are always below the payments extensions

### Screenshots

Before:

before

After:

Screen Shot 2022-01-31 at 15 34 34

### Detailed test instructions:

1. Create a new store
2. Go to the setup wizard and choose the "Australia" or "India" as **Country / Region**
3. Go to **WooCommerce > Home** and visit the "Set up payments" task
4. Observe that offline payments options are below the payments extensions.

### CODE REVIEW

File: client/tasks/fills/PaymentGatewaySuggestions/index.js [hunk 1]
```diff
@@ -165,27 +166,43 @@ export const PaymentGatewaySuggestions = ( { onComplete, query } ) => {
...
-						enabled.push( gateway );
-					} else {
-						additional.push( gateway );
+			Array.from( paymentGateways.values() )
+				.sort( ( a, b ) => {
+					if ( a.hasPlugins === b.hasPlugins ) {
+						return (
+							a.recommendation_priority -
+							b.recommendation_priority
+						);
```
Comment (louwie17) [inline client/tasks/fills/PaymentGatewaySuggestions/index.js:175]: Nice!!
We do have the same sort logic just above this here: https://github.com/woocommerce/woocommerce-admin/blob/main/client/tasks/fills/PaymentGatewaySuggestions/index.js#L139-L149

It doesn't appear we can make use of `additionalGateways` there instead, so maybe we just want to move the sorting function into a helper function and use that in both of these sort methods. That way if we ever update the sort logic it will be updated for both instances.

**Review by louwie17 — DISMISSED** [review]
Tested well, and thanks for adding tests for this as well 💯 
I just left a couple small suggestions.

File: client/tasks/fills/PaymentGatewaySuggestions/test/index.js [hunk 2]
```diff
@@ -0,0 +1,165 @@
...
+				query={ query }
+			/>
+		);
+
+		const paymentTitles = container.querySelectorAll(
+			'.woocommerce-task-payment__title'
+		);
+
+		expect( paymentTitles.length ).toBe( 5 );
+		expect( container ).toMatchSnapshot();
```
[the remark this answers is not in the document]
Comment (chihsuan) [reply client/tasks/fills/PaymentGatewaySuggestions/test/index.js]: Got it! Updated in e71c236c7dc14915d76c8117df671826c178428b.

File: client/tasks/fills/PaymentGatewaySuggestions/index.js (hunk 1 above)
Comment (chihsuan) [reply client/tasks/fills/PaymentGatewaySuggestions/index.js]: Sounds good. Changed in b6c27f5349f5738567745dd6f19a7c2de7137260.

**Review by ilyasfoo — APPROVED** [review]
Tested well, LGTM! 🚢
