### PR TITLE
Remove WooCommerce Tax copies if it is already installed

### LINKED ISSUE #5712: Detect if WCTax is installed for tax task
**Describe the bug**
Can we detect if WCTax is already installed and change the copy in the tax task? I had gone through and installed WCShip&Tax during onboarding, but in the tax task it seemed like the extension hadn't been installed which could cause confusion. 

**To Reproduce**
Create a new site with WCShip & Tax installed but Jetpack not connected.

1. Go to the Home screen
2. Click on 'Set up task'
3. See that the copy shows "Install Jetpack and WC Tax"

**Expected behavior**
If WCTax is already installed, the copy should only say "Install Jetpack"

**Screenshots**
detect if WCTax is installed

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #5712 

This PR removes WC Shipping & Tax copies if it is already installed.

### Detailed test instructions:

**Without WooCommerce Shipping & Tax installed:**

1. Install & Activate WooCommerce
2. Navigate to WooCommerce -> Home and click "Set up tax"
3. Set store location and move to step 2.
4. You should see "Install Jetpack and WooCommerce Tax"

Screen Shot 2020-11-24 at 3 07 38 PMth_

**With WooCommerce Shipping & Tax installed:**
1. Install & Activate WooCommerce
2. Navigate to WooCommerce -> Home and click "Set up tax"
3. Set store location and move to step 2.
4. You should see "Install Jetpack" without any mention of WooCommerce Tax.

Screen Shot 2020-11-24 at 3 08 28 PMth_

### CODE REVIEW

File: client/task-list/tasks/tax.js [hunk 1]
```diff
@@ -508,6 +520,8 @@ export default compose(
 			[ 'jetpack', 'woocommerce-services' ],
 			activePlugins
 		);
+		window.activePlugins = activePlugins;
```
Comment (timmyc) [inline client/task-list/tasks/tax.js:523]: Are these two lines needed or perhaps some debugging code?

Comment (moon0326) [reply client/task-list/tasks/tax.js:523]: @timmyc My apologies and thank you for catching. Yes, they were for debugging. I will remove them.

Comment (moon0326) [reply client/task-list/tasks/tax.js]: Removed from the latest commit https://github.com/woocommerce/woocommerce-admin/commit/27330e602118a08e4548ce9132e00d7a873290a3

**Review by ilyasfoo — APPROVED** [review]
I have tested this as well, LGTM 🚀
