### PR TITLE
Fix setup wizard title and flash of content

### LINKED ISSUE #6598: Flash of content on profile wizard initial load
**Describe the bug**
There is a flash of content on the initial load when the profile wizard is loaded.

This results in a header that contains `/setup-wizard` for the title and looks a little janky.

Previously this was hidden prior to client load by a full screen class, but appears to no longer be working.

**To Reproduce**

1. Throttle your browser speed to see the content.
2. Load the setup wizard.
3. Note the header shown prior the profile wizard taking over.

**Expected behavior**
Expected the profile wizard to take over the screen immediately and not show the WCA header.

**Screenshots**
Screen Shot 2021-03-15 at 7 33 28 PM

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #6598 

* Fixes the setup wizard title
* Adds the full screen class to hide content while the page is loading

Note that the `woocommerce-admin-is-loading` class still works by adding a body class to the page.  However, since the chunks are now lazily loaded, `woocommerce-admin-is-loading` gets removed prior to the chunks loading causing the flash.

### Detailed test instructions:

1. Navigate to `wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard` directly via your browser's address bar
2. Note that the page content underneath (header, menu, etc) is not shown while the profile wizard is loading
3. In your browser's console run `document.body.classList.remove('woocommerce-admin-full-screen');` 
4. This will result in a broken layout, but the important item to note here is that the header title is now "Store details" instead of "/setup-wizardStoreDetails"
3. Navigate to other pages to make sure no regressions have occurred

### CODE REVIEW

File: src/Features/Onboarding.php [hunk 1]
```diff
@@ -731,19 +731,24 @@ public static function get_allowed_themes() {
...
-	 * Let the app know that we will be showing the onboarding route, so wp-admin elements should be hidden while loading.
+	 * Set the admin full screen class when loading to prevent flashes of unstyled content.
 	 *
-	 * @param bool $is_loading Indicates if the `woocommerce-admin-is-loading` should be appended or not.
-	 * @return bool
+	 * @param bool $classes Body classes.
+	 * @return array
 	 */
-	public function is_loading( $is_loading ) {
-		$show_profiler = self::should_show_profiler();
```
Comment (louwie17) [inline src/Features/Onboarding.php:740]: Is there a specific reason you didn't use this helper function anymore?

The slight flash does still happen when the onboarding wizard hasn't been completed yet and it auto redirects from **WooCommerce > Home**, not sure if this is also preventable?
I tried making use of the `self::should_show_profiler();` locally again but that didn't make a difference there.

**Review by louwie17 — APPROVED** [review]
This looks good and tested well! Nice work on this @joshuatf.

Approving this, but I was kinda curious if there is also way to prevent the small flash that happens when the onboarding hasn't been finished yet and it auto redirects to the setup wizard?

File: src/Features/Onboarding.php (hunk 1 above)
Comment (joshuatf) [reply src/Features/Onboarding.php:740]: `should_show_profiler()` will return `true` even on other pages besides the homepage and profiler.

I think it's original meaning has been lost over iterations and needs updating semantically, but I'll save that for another PR.

**Comment by joshuatf** [comment]
>Approving this, but I was kinda curious if there is also way to prevent the small flash that happens when the onboarding hasn't been finished yet and it auto redirects to the setup wizard?

Good question.  I went ahead and forced the redirect on server-side which both catches this and will allow slightly faster loading bypassing some of the homepage logic.

This required a small extraction of logic in https://github.com/woocommerce/woocommerce-admin/pull/8201/commits/5b7b7c68f85488c5954b373c880330db8266ec09 to separate functions, but the logic itself remains mostly unchanged.  Could you give this another look, @louwie17?

**Review by louwie17 — APPROVED** [review]
Awesome, thanks for the update @joshuatf, this tested great! Also nice work on creating the two helper functions for the profile_wizard and homepage 💯
