### PR TITLE
Fix country/region selection not preserved in store details task

### LINKED ISSUE #8225: Country/Region selection not preserved
### Describe the bug

On returning to the Store Details step of the OBW, the "Country / Region" field is blank. The other parts of the address are still populated with the values entered during the first time through Store Details.

Initially found on a JN site during 3.2.0-beta.1 smoke test, but reproduced locally on Woo core 6.1.0 WC Admin 3.0.3.

### To Reproduce

1. Create a new store
2. Go through the Store Details screens. I used:
     * a Kansas address
     * no mailing list
     * no usage tracking
     * CBD products
     * Downloads
     * 1-10 products, not selling elsewhere, not setting up a store for a client
     * no recommended business features
     * Boutique theme
3. When you arrive at WooCommerce / Home, click the Store Details task again and note which fields are populated
4. Navigate to WooCommerce / Settings / General and observe the Store Address section

### Actual behavior:

* All the address fields in Store Details are still populated except Country / Region.
* The Country / State field under Store Address in WooCommerce / Settings / General does match what was entered for Country / Region in the first time through Store Details.

#### Store Details task:
Screen Shot 2022-01-27 at 12 54 47

#### WooCommerce / Settings / General / Store Address
Screen Shot 2022-01-27 at 13 05 57

### Expected behavior

* On revisiting the Store Details task the Country / Region field should still be populated (with "United States (US) -- Kansas" in this example).
* The Store Details fields should match what's displayed in the Store Address section of WooCommerce / Settings / General.

### Desktop (please complete the following information):

* OS: macOS 12.1
* Browser: Chrome
* Version: 97.0.4692.99

### Additional context

I found this while trying to test that WooCommerce Payments would be suggested for stores with US addresses, but that may be a separate issue.

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #8225

This PR fixes the country/region preserved issue with the following changes:

- Instead of using the regular expression to match the state label, compare the strings directly to avoid ambiguity.

This issue is that we used the regular expression to match state but the `/Kansas$/i` also matches "Arkansas".

https://github.com/woocommerce/woocommerce-admin/blob/281ae241d0c6d15f696c74cd6bd28294dee16a0f/client/dashboard/components/settings/general/store-address.tsx#L167-L170

And the`filteredOptions` length is two so `countryState` won't be updated.

https://github.com/woocommerce/woocommerce-admin/blob/281ae241d0c6d15f696c74cd6bd28294dee16a0f/client/dashboard/components/settings/general/store-address.tsx#L218-L224

- Handle the special region cases:  `China — Beijing / 北京`, `Iran — Tehran (تهران)`, etc.
- Simplify the logic of the functions in the `useEffect`.
- Update & add more tests
- Add typescript "typings" to function props.
- Fixed "tabIndex" string warning.

### Screenshots

Before:

https://user-images.githubusercontent.com/4344253/151507869-f64af582-43b9-460e-9cb2-b72667f2cff0.mov

After:

https://user-images.githubusercontent.com/4344253/151505034-15d46d98-a872-45e4-80a5-cdd2803865b0.mov

### Detailed test instructions:

1. Create a new store
2. Go to the setup wizard
3. Choose "United States (US) — Kansas" as the "Country/Region"
4. Complete the setup wizard
5. Go to **WooCommerce > Home** click the Store Details task again
6. "Country/Region" should be populated with "United States (US) -- Kansas"
7. Navigate to **WooCommerce > Settings > General**
8. Observe that the "Country / State" value under the Store Address section should be the same.

Since this PR also refactor the autocomplete parts, it would be great to test it as well:

Reference: https://github.com/woocommerce/woocommerce-admin/pull/7497

- Start a new WooCommerce store and go to **WooCommerce > Home** (make sure you have autofill enabled and some addresses configured) - [chrome settings](https://support.google.com/chrome/answer/142893?hl=en&co=GENIE.Platform%3DDesktop&oco=0)
- The onboarding flow should start, asking for the store address
- Do an autofill of the store address and make sure the Country/Region is correctly selected
- Now try each of these cases:
     - After using autocomplete, search for and select a country/region manually, it should change on click
     - Clear the fields and make sure one of your auto-complete addresses uses an abbreviated region (California -> CA) and see if it correctly selects the region with the country
- Feel free to try other things with the type ahead field and see if any odd behavior happens and in other browsers like Safari or Firefox

### CODE REVIEW

**Comment by mattsherman** [comment]
@louwie17 I think it would be good to cherry-pick this in 3.2.0-beta.2. We already touched this part of the flow with the localization updates, and GS will be running through things, so I think this would be a safe update.

**Review by jacob-sewell — APPROVED** [review]
Looks good to me. Thanks for tracking this down so quickly!

File: client/dashboard/components/settings/general/store-address.tsx [hunk 1]
```diff
@@ -16,14 +16,21 @@ import { useSelect } from '@wordpress/data';
...
  * Check if a given address field is required for the locale.
  *
  * @param {string} fieldName Name of the field to check.
  * @param {Object} locale Locale data.
  * @return {boolean} Field requirement.
  */
-export function isAddressFieldRequired( fieldName, locale = {} ) {
+export function isAddressFieldRequired(
+	fieldName: string,
+	// eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (mattsherman) [inline client/dashboard/components/settings/general/store-address.tsx:31]: I am not very familiar with TypeScript. But, isn't there a way to handle this without using `any` and the corresponding `eslint-disable-next-line`?

File: client/dashboard/components/settings/general/store-address.tsx [hunk 2]
```diff
@@ -130,98 +189,101 @@ export function getCountryStateOptions() {
...
+			if (
+				newCountry !== autofillCountry ||
+				newState !== autofillState
+			) {
+				setAutofillCountry( newCountry );
+				setAutofillState( newState );
+			}
 		}
 		isAutofillChange.current = false;
+		// eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (mattsherman) [inline client/dashboard/components/settings/general/store-address.tsx:222]: Why is this needed? Is there a way to avoid this?

File: client/dashboard/components/settings/general/store-address.tsx [hunk 3]
```diff
@@ -130,98 +189,101 @@ export function getCountryStateOptions() {
...
 		}
-
 		if (
 			filteredOptions.length === 1 &&
 			countryState !== filteredOptions[ 0 ].key
 		) {
 			isAutofillChange.current = true;
 			setValue( 'countryState', filteredOptions[ 0 ].key );
 		}
+		// eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (mattsherman) [inline client/dashboard/components/settings/general/store-address.tsx:286]: Same comment as above.

File: client/dashboard/components/settings/general/store-address.tsx [hunk 4]
```diff
@@ -244,21 +306,31 @@ export function useGetCountryStateAutofill( options, countryState, setValue ) {
...
-				tabIndex="-1"
+				tabIndex={ -1 }
 				autoComplete="address-level1"
 			/>
 		</>
 	);
 }
 
+type StoreAddressProps = {
+	// eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (mattsherman) [inline client/dashboard/components/settings/general/store-address.tsx:317]: Is there a way to avoid this?

**Review by mattsherman — DISMISSED** [review]
I didn't fully review this. However, I noticed a number of `eslint-disable-next-line`, which feels like something to be avoided unless there are very good reasons.

I'd like to better understand why these were used as opposed to other approaches that would have not required them.

File: client/dashboard/components/settings/general/store-address.tsx (hunk 2 above)
Comment (chihsuan) [reply client/dashboard/components/settings/general/store-address.tsx:222]: I disabled this because we also update the `autofillCountry` and `autofillState` in this `useEffect`. If we include them in the dependency array, we will have an unnecessary function call whenever the `countryState` is changed.

We probably can remove these lines to avoid this, however, we then will have unnecessary state update calls.

```js
if (
  newCountry !== autofillCountry ||
  newState !== autofillState
) {
```

File: client/dashboard/components/settings/general/store-address.tsx (hunk 3 above)
Comment (chihsuan) [reply client/dashboard/components/settings/general/store-address.tsx:286]: Similar here. We both read and update the `countryState`

File: client/dashboard/components/settings/general/store-address.tsx (hunk 1 above)
Comment (chihsuan) [reply client/dashboard/components/settings/general/store-address.tsx]: Thank you for bringing this up. I used `any` here because this is a complex object and there is no type defined in the data source. If we want to define a type for it, we need to trace the source but it is only used in this function, which I think it's not worthy.   However, I just changed this to `unknown` so we don't need the `eslint-disable-next-line`.

File: client/dashboard/components/settings/general/store-address.tsx (hunk 4 above)
Comment (chihsuan) [reply client/dashboard/components/settings/general/store-address.tsx:316]: I think `any` is best for now because we don't have the defined type for `getInputProps` from the source (`component/From` still uses JavaScript only). And we cannot use `unknown` here since many variables are derived from it.

**Comment by chihsuan** [comment]
@mattsherman Thanks for the review, I've replied to your comments and added the `Disable reason:` to the file.

**Review by louwie17 — DISMISSED** [review]
Sorry for being the third person to tag on to the review list. I just left one comment in relation to the `any` type, aside from that things looked good and tested well!

**Comment by louwie17** [comment]
@chihsuan I merged this for now, as it does fix a bug and it tests well. It would be great if you could create a follow up PR to address the `any` usage in TypeScript: https://github.com/woocommerce/woocommerce-admin/pull/8228#discussion_r796011773
