### PR TITLE
Enqueue beta features scripts on enqueue_scripts action instead of filter 

### LINKED ISSUE #6258: New "wp_enqueue_style used incorectly" notice appearing
**Describe the bug**

This notice started appearing in our tests but AFAICS this could also happen on a real store too. It looks like the `woocommerce_get_settings_advanced` filter is actually evaluated during `WC_Install::install()`. So this notice will be triggered when WooCommerce is first installed.

The code: https://github.com/woocommerce/woocommerce-admin/blame/488ed6776c0217f421e42b8623f7f3046bf802cf/src/Features/Features.php#L245-L257

```
Notice: wp_enqueue_style was called <strong>incorrectly</strong>. Scripts and styles should not be registered or enqueued until the <code>wp_enqueue_scripts</code>, <code>admin_enqueue_scripts</code>, or <code>login_enqueue_scripts</code> hooks. This notice was triggered by the <code>wc-admin-beta-features-tracking-modal</code> handle. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in /private/var/folders/sv/btxj39j51_54gtrvzxzt0q1w0000gp/T/wordpress/wp-includes/functions.php on line 5311
PHP Notice:  wp_enqueue_script was called <strong>incorrectly</strong>. Scripts and styles should not be registered or enqueued until the <code>wp_enqueue_scripts</code>, <code>admin_enqueue_scripts</code>, or <code>login_enqueue_scripts</code> hooks. This notice was triggered by the <code>wc-admin-beta-features-tracking-modal</code> handle. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in /private/var/folders/sv/btxj39j51_54gtrvzxzt0q1w0000gp/T/wordpress/wp-includes/functions.php on line 5311
```

**Backtrace**

```
#0  Automattic\WooCommerce\Admin\Features\Features::maybe_load_beta_features_modal(Array ([0] => Array ([title] => ,[type] => title,[desc] => ,[id] => legacy_api_options),[1] => Array ([title] => Legacy API,[desc] => Enable the legacy REST API,[id] => woocommerce_api_enabled,[type] => checkbox,[default] => no),[2] => Array ([type] => sectionend,[id] => legacy_api_options)), legacy_api) called at [/private/var/folders/sv/btxj39j51_54gtrvzxzt0q1w0000gp/T/wordpress/wp-includes/class-wp-hook.php:287]
#1  WP_Hook->apply_filters(Array ([0] => Array ([title] => ,[type] => title,[desc] => ,[id] => legacy_api_options),[1] => Array ([title] => Legacy API,[desc] => Enable the legacy REST API,[id] => woocommerce_api_enabled,[type] => checkbox,[default] => no),[2] => Array ([type] => sectionend,[id] => legacy_api_options)), Array ([0] => Array ([0] => Array ([title] => ,[type] => title,[desc] => ,[id] => legacy_api_options),[1] => Array ([title] => Legacy API,[desc] => Enable the legacy REST API,[id] => woocommerce_api_enabled,[type] => checkbox,[default] => no),[2] => Array ([type] => sectionend,[id] => legacy_api_options)),[1] => legacy_api)) called at [/private/var/folders/sv/btxj39j51_54gtrvzxzt0q1w0000gp/T/wordpress/wp-includes/plugin.php:212]
#2  apply_filters(woocommerce_get_settings_advanced, Array ([0] => Array ([title] => ,[type] => title,[desc] => ,[id] => legacy_api_options),[1] => Array ([title] => Legacy API,[desc] => Enable the legacy REST API,[id] => woocommerce_api_enabled,[type] => checkbox,[default] => no),[2] => Array ([type] => sectionend,[id] => legacy_api_options)), legacy_api) called at [/Users/dan/Developer/automatewoo/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-advanced.php:402]
#3  WC_Settings_Advanced->get_settings(legacy_api) called at [/Users/dan/Developer/automatewoo/wp-content/plugins/woocommerce/includes/class-wc-install.php:606]
#4  WC_Install::create_options() called at [/Users/dan/Developer/automatewoo/wp-content/plugins/woocommerce/includes/class-wc-install.php:305]
#5  WC_Install::install() called at [/Users/dan/Developer/automatewoo/wp-content/plugins/automatewoo/tests/bootstrap-class.php:151]
```

**To Reproduce**
I've struggled to reproduce this in a real outside of a unit test env but theoretically it's possible and it would be nice if this notice didn't appear when we call `WC_Install::install()` before running phpunit.

**Expected behavior**
No notices are triggered.

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #6258 

Updated the `maybe_load_beta_features_modal` to be triggered on the `admin_enqueue_scripts` action as the function add's different scripts to the page. Previously it was triggered on the `woocommerce_get_settings_advanced` filter, which didn't only happen on the settings page.

### Screenshots

No warnings as mentioned in the original ticket:
Screen Shot 2021-02-17 at 10 49 34 AM

Modal still correctly appears when trying to enable the new nav when tracking is disabled:
Screen Shot 2021-02-17 at 10 49 54 AM

### Detailed test instructions:

- Checkout this branch and run `npm run test:php` in your console, the `Notice: wp_enqueue_style was called...` log should not appear (pretty noticable if they do, try running the tests on `main`).
- Make sure the option `woocommerce_allow_tracking` is set to `no` or removed.
- Navigate to **WooCommerce > Settings > Advanced > Features**
- Try to enable one of the **Features** like the new navigation
- The **Build a Better WooCommerce** modal should popup (`beta-features-tracking-modal`)
- Set the `woocommerce_allow_tracking` to `yes` and reload the **Advanced > Features** settings page
- Try to enable one of the **Features**
- The **Build a Better WooCommerce** modal should not pop up

### CODE REVIEW

**Comment by louwie17** [comment]
@joshuatf would the beta features tracking modal be used anywhere else outside of the advanced settings feature page?

**Review by adrianduffell — APPROVED** [review]
This tested perfectly for me. Love seeing the clean PHPUnit output ❤️

File: src/Features/Features.php [hunk 1]
```diff
@@ -232,14 +232,18 @@ public static function add_features_settings( $settings, $current_section ) {
...
 	 * Conditionally loads the beta features tracking modal.
 	 *
-	 * @param array $settings Settings.
-	 * @return array
+	 * @param string $hook Page hook.
 	 */
-	public static function maybe_load_beta_features_modal( $settings ) {
+	public static function maybe_load_beta_features_modal( $hook ) {
+		if (
+			'woocommerce_page_wc-settings' !== $hook
```
Comment (joshuatf) [inline src/Features/Features.php:239]: This will load on all the settings pages.  Maybe we could check if we're on the right tab and section before enqueuing this script?

`isset( $_GET['tab'] ) && 'advanced' === $_GET['tab'] && isset( $_GET['section'] ) && 'features' === $_GET['section'] `

**Review by joshuatf — APPROVED** [review]
Thanks for the fix here, @louwie17!  This works well, just left one quick change to only load this on the features section.

File: src/Features/Features.php (hunk 1 above)
Comment (louwie17) [reply src/Features/Features.php:239]: Thanks, will do that.
Not that it's super important atm, but would the above also work for when we use the new settings?

Comment (louwie17) [reply src/Features/Features.php]: @joshuatf Updated in https://github.com/woocommerce/woocommerce-admin/pull/6358/commits/bcd4f337c64625ba2ba8f73493d43d3937776035
