### PR TITLE
Show management links when the task list is complete (even if its not hidden).

### LINKED ISSUE #6592: [GlobalStep] On WooCommerce->Home page, "Store Management" section fails to appear once "Finish Setup" section is completed.
## Bug Description:
On WooCommerce->Home page, "Store Management" section fails to appear once "Finish Setup" section is completed. 

## Test Instructions:
Smoke Test Checklist->Store Management Links:
https://github.com/woocommerce/woocommerce-admin/wiki/Smoke-Test-Checklist#store-Management-links

## Environment:
Woocommerce Version: WooCommerce 5.1 and 5.0
WordPress version: (v5.7)
WooCommerce Admin version: v2.1.3 and v2.0.2

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate the WP Crontrol plugin.
1. Install and activate the WP phpMyAdmin plugin.
1. Install and activate the WooCommerce plugin.
1. SKIP the onboarding wizard after WooCommerce is activated.
1. Install and activate the WooCommerce Admin v2.1.3 plugin
1. Go to WooCommerce->Settings->Help and click on "Setup Wizard" button
1. Complete the onboarding wizard
1. On WooCommerce->Home page complete all the checklist present under "Finish Setup" section
1. Observe that "Store Management" section fails to appear once "Finish Setup" section is completed. 

**Note:**
On WooCommerce->Home page,"Store Management" section appears only when we hide the "Finish Setup" section by clicking on "Hide this" option  

## Actual Result:
On WooCommerce->Home page, "Store Management" section fails to appear once "Finish Setup" section is completed. 

## Expected Result:
As per test instructions, "Store Management" section should appear once "Finish Setup" section is completed on WooCommerce->Homepage

## Video:

https://user-images.githubusercontent.com/41110392/111171926-62f4d580-85cb-11eb-850b-ff9898b26b3c.mov

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://straightforward-parakeet.jurassic.ninja
Site address (URL): https://straightforward-parakeet.jurassic.ninja
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.3
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 6.02MB
Database Data Size: 4.48MB
Database Index Size: 1.54MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 4
page: 7
post: 2
product: 4
product_variation: 38
revision: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (12) ###

Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.3
Facebook for WooCommerce: by Facebook – 2.3.2
Jetpack by WordPress.com: by Automattic – 9.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
WooCommerce Admin: by WooCommerce – 2.1.3
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Shipping & Tax: by Automattic – 1.25.8
WooCommerce: by Automattic – 5.1.0
WP Crontrol: by John Blackbourn & crontributors – 1.10.0
WP phpMyAdmin: by Puvox.software – 5.0.4.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2021-03-15 07:38:32 +0000
Newest: 2021-03-15 10:59:53 +0000


### Status report information ###

Generated at: 2021-03-15 11:07:49 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by samueljseay**
Fixes #6592 

There was some confusion around what the correct behaviour should be here. It turns out that the setup task list should stay visible even after tasks are done, thats because we have some data showing users go back to these tasks after completing them to do things like adding additional payment providers.

However a side effect of the current behaviour was that you never see store management links until you hide the task list which seems counter-intuitive. I confirmed with Pedro that we should fix this.

I've changed the logic so that the store management links now show if the task list has been hidden *or* if you've completed all the tasks.

Also note, the tests for the Homescreen `<Layout>` component were all broken and reporting false positives due to ambiguous matchers. There were a number of reasons for this that I've addressed as part of this. I've gone to using the jest dom matcher `toBeInTheDocument()` and I've also had to take an alternative approach to mock out the `lazy` component.

### Detailed test instructions:

1. With a site that has not completed all the setup task list tasks, go through and complete them all.
2. Once the last task is completed you should see the "Store Management" section displayed in the right hand column.
3. With a site that has not completed all the setup tasks, dismiss the task list.
4. Again verify that "Store Management" is visible.

I've left off testing instructions for this, as its a minor adjustment to behaviour and wasn't really considered a bug.

### CODE REVIEW

File: client/homescreen/test/index.js [hunk 1]
```diff
@@ -9,30 +9,37 @@ import { useUserPreferences } from '@woocommerce/data';
  */
 import { Layout } from '../layout';
 
-// Rendering <StatsOverview /> breaks tests.
 jest.mock( 'homescreen/stats-overview', () =>
-	jest.fn().mockReturnValue( '[StatsOverview]' )
+	jest.fn().mockReturnValue( <div>[StatsOverview]</div> )
```
Comment (samueljseay) [inline client/homescreen/test/index.js:13]: I took this approach so we can use the text queries in combination with `toBeInTheDocument` to confirm that the component would have been rendered. Before these changes none of these were actually being rendered and it reported false positives because `null` passes the `toBeDefined` check.

File: client/homescreen/test/index.js [hunk 2]
```diff
@@ -268,26 +267,26 @@ describe( 'Homescreen Layout', () => {
...
+		).not.toBeInTheDocument();
 		expect(
-			within( secondColumn ).queryByText( /\[InboxPanel\]/ )
-		).toBeNull();
+			within( secondColumn ).queryByText( '[InboxPanel]' )
+		).not.toBeInTheDocument();
 
 		expect(
-			within( secondColumn ).getByText( /\[StatsOverview\]/ )
+			within( secondColumn ).getByText( '[StatsOverview]' )
```
Comment (samueljseay) [inline client/homescreen/test/index.js:283]: I went for text instead of the regex, because its less to type and easier to edit later.

File: client/homescreen/layout.js [hunk 3]
```diff
@@ -83,6 +83,7 @@ export const Layout = ( {
 	}, [ maybeToggleColumns ] );
 
 	const shouldStickColumns = isWideViewport.current && twoColumns;
+	const shouldShowStoreLinks = taskListComplete || ! isTaskListEnabled;
```
Comment (louwie17) [inline client/homescreen/layout.js:86]: Would it still be worth to keep the `isTaskListHidden` and add it onto this `||` case?
That way if the user hides the task list without completing it, it will still show the store management links.

(side note, kinda unrelated) `isTaskListEnabled` kinda confused me, I guess just means if both task lists are hidden (but that might never happen if the user doesn't have a plugin with custom tasks).

**Review by louwie17 — COMMENTED** [review]
@samueljseay nice work on the test updates 👍 
Just left one comment, to still show the store management links if the user hides the task list without completing it.

File: client/homescreen/layout.js (hunk 3 above)
Comment (samueljseay) [reply client/homescreen/layout.js:86]: @louwie17 yeah in testing isTaskListEnabled seemed fine without custom tasks, but I agree it might make more sense to check `isTaskListHidden` instead. I'll investigate this.

Comment (samueljseay) [reply client/homescreen/layout.js]: I have resolved this by just using `isTaskListHidden` here: https://github.com/woocommerce/woocommerce-admin/pull/6657/commits/a568e6614fa81cb4abdceaea46f51b6ad4e97a8d tests well for me. I don't think we need both since `isTaskListEnabled` is determined by `isTaskListHidden` and another specific option. 

Thanks for suggesting this, I think its a lot better.

**Comment by samueljseay** [comment]
@louwie17 Keen for a re-review when you get a chance.

File: client/homescreen/layout.js [hunk 4]
```diff
@@ -83,6 +84,7 @@ export const Layout = ( {
 	}, [ maybeToggleColumns ] );
 
 	const shouldStickColumns = isWideViewport.current && twoColumns;
+	const shouldShowStoreLinks = taskListComplete || isTaskListHidden;
```
Comment (joshuatf) [inline client/homescreen/layout.js:87]: Nice.  Seems like a good move.

**Review by joshuatf — APPROVED** [review]
Testing well for me and I think @louwie17's concerns have been addressed.  LGTM!
