### PR TITLE
Fix shipping rate error message overlaps with the 'Proceed' button

### LINKED ISSUE #6389: Error message for negative shipping cost overlaps with the 'Complete task' or 'Proceed' button
**Describe the bug**
In the "Set shipping costs' section, when you enter a negative value in the 'Shipping cost' input field in the 'Rest of the world' section, you would see a message saying 'Shipping rates can not be negative numbers.' which overlaps with the 'Complete task' button.

**To Reproduce**

1. Go to 'Home'
2. Click on 'Set up shipping'
3. Toggle the 'Rest of the world' on.
4. In the 'Shipping cost' input field inside the 'Rest of the world' section, enter '-4'.
5. Click anywhere outside the 'Shipping cost' input field.
6. Notice that the error message _'Shipping rates can not be negative numbers.'_ appears, but overlaps with the 'Complete task' or 'Proceed' button

**Expected behavior**
The 'Shipping rates can not be negative numbers.' error message should not overlap with the 'Complete task' or 'Proceed' button.

**Screenshots**
err message overlaps with Proceed button 2

**Desktop:**

* OS: Windows 10 Pro 64-bit
* Browser: Firefox, Chrome
* Version: FF v85.0.2 (64-bit), Chrome Version 88.0.4324.182 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #6389

This PR fixes the issue that the shipping rate error message overlaps with the 'Proceed' button.

I also refactored the shipping rate component by splitting it into small components since the rendering part was too large to view.

### Screenshots

Before:

before

After:

Screen Shot 2022-01-13 at 14 55 58

### Detailed test instructions:

Use a new store and finish the 'Setup Wizard'.

1. Go to 'Home'
2. Click on 'Set up shipping'
3. Toggle the 'Rest of the world' on.
4. In the 'Shipping cost' input field inside the 'Rest of the world' section, enter '-4'.
5. Click anywhere outside the 'Shipping cost' input field.
6. Notice that the error message 'Shipping rates can not be negative numbers.' appears and it does **not** overlap with the 'Complete task' or 'Proceed' button

### CODE REVIEW

File: client/tasks/fills/shipping/rates.js [hunk 1]
```diff
@@ -229,80 +307,34 @@ class ShippingRates extends Component {
...
-															)
-														);
-													} }
-													prefix={ this.renderInputPrefix() }
-													suffix={ this.renderInputSuffix(
-														values[
-															`${ zone.id }_rate`
-														]
-													) }
-													className="muriel-input-text woocommerce-shipping-rate__control-wrapper"
```
Comment (chihsuan) [inline client/tasks/fills/shipping/rates.js:303]: The root cause is the **className** from `getInputProps` is overwritten by this class name. I fixed this in line 59.

**Review by ilyasfoo — APPROVED** [review]
Tested well, thanks for improving the readability of the code. LGTM! 🚢  🚢
