### PR TITLE
Use tab char instead of single quote to prevent CSV injection

### LINKED ISSUE #7040: Negative values are not being exported correctly by csv-export module
**Describe the bug**
Presently if you try to export CSV which has negative values it adds an `'` in front of the value, this due to the `escapeCSVValue` function appends `'` in front of the `-` character to prevent CSV vulnerabilities.

Function responsible: https://github.com/woocommerce/woocommerce-admin/blob/e9879f3727433a9e11567e35c043bba2e6944df1/packages/csv-export/src/index.js#L13-L14

**To Reproduce**

1. Go to the Transactions page.
2. Make sure you have some -ve values, you can do this by creating a refund test transaction.
2. Click on Download.
3. You'll see a negative value represented as for example(`-70` as `'-70`) 

**Expected behavior**
Negative values should be rendered as-is during CSV export.

**Screenshots**
Screenshot 2021-05-21 at 3 17 20 PM

**Desktop (please complete the following information):**
* OS: Mac
* Browser: Chrome
* Version: Latest

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #7040

This PR replaces a single quote to a tab char that is used to prevent CSV injection.

For the CSV injection details, please refer to the following articles.

https://www.contextis.com/blog/comma-separated-vulnerabilities
http://georgemauer.net/2017/10/07/csv-injection.html
https://owasp.org/www-community/attacks/CSV_Injection

Both a single quote and tab char work, but some CSV viewers display a single quote visually.  This PR uses a tab char to prevent that. 

### Detailed test instructions:

You will need both WooCommerce Admin and Payments to test this change.

1. Clone this repository and run `npm start` to build the change.
2. Install & activate WooCommerce Payments
3. Open your terminal and cd to WooCommerce Admin directory.
4. Copy `packages/csv-export` directory and replace `node_modules/@woocommerce/csv-export` in your WooCommerce Payments plugin.
5. Run `npm start` in WooCommerce Payments.
6. Go through WooCommerce Payments setup process.
7. Place a new order using WooCommerce Payments
8. Refund the order
9. Navigate to Payments -> Transactions and click the download button.
10. Observe that the - value doesn't have a single quote.

### CODE REVIEW

**Comment by moon0326** [comment]
Hey @naman03malhotra ✋ 

Would you test this PR when you get a chance, please? I figured you would be the best person to test since you already have the test environment 🙇‍♂️

File: packages/csv-export/src/test/index.js [hunk 1]
```diff
@@ -31,6 +31,29 @@ describe( 'generateCSVDataFromTable', () => {
...
+						{
+							display: 'value',
+							value: val + 'test',
+						},
+					],
+				]
+			);
+			expect( result ).toBe( expected );
+		} );
+	} );
```
Comment (naman03malhotra) [inline packages/csv-export/src/test/index.js:56]: Thank you for this. ❤️

**Review by naman03malhotra — APPROVED** [review]
LGTM! Thank you for taking this up 😄 .

I can confirm that it works well with the Number app on mac and google sheet, I am able to add and find the correct sum of numbers present in a column when a negative number is present. Also, the numbers are aligned as well visually.

I don't have MS Excel, but if you have access to that, I've attached a link to the output file just in case!
[transactions_2021-06-10 (1).csv](https://github.com/woocommerce/woocommerce-admin/files/6631429/transactions_2021-06-10.1.csv)

**Comment by naman03malhotra** [comment]
One of the workflows is failing due to the missing changelog, please have a look.

**Comment by jeffstieler** [comment]
The [OWASP site](https://owasp.org/www-community/attacks/CSV_Injection) says to remove tab characters from the beginning of cells:

> ensure that no cells begin with any of the following characters:
> 
> Equals to (`=`)
> Plus (`+`)
> Minus (`-`)
> At (`@`)
> Tab (`0x09`)
> Carriage return (`0x0D`)

Have you tested this against a malicious cell value?

**Comment by moon0326** [comment]
> The [OWASP site](https://owasp.org/www-community/attacks/CSV_Injection) says to remove tab characters from the beginning of cells:
> 
> > ensure that no cells begin with any of the following characters:
> > Equals to (`=`)
> > Plus (`+`)
> > Minus (`-`)
> > At (`@`)
> > Tab (`0x09`)
> > Carriage return (`0x0D`)
> 
> Have you tested this against a malicious cell value?

I completely missed that. Interesting....I will look into the tab value.

**Comment by moon0326** [comment]
@jeffstieler @naman03malhotra 

I initially tested this change on Microsoft excel online and Numbers on Mac OS and the test worked as expected. It turned out that I google sheet doesn't work. Google Sheets still treats a cell with a tab character as a fomula. 

We actually need to use double quotes around the cell and add a tab character. This fix works for Google Sheets, Numbers, and Microsoft excel online.

**Current**: \tValue
**It should be** :"\tValue"

I'm gonna also test this change with Libre Office and Microsoft Excel (offline version).

File: packages/csv-export/src/test/index.js (hunk 1 above)
Comment (moon0326) [reply packages/csv-export/src/test/index.js]: Added changelog and updated code to surround cells with a double 
quotation.

I'm also including CSV files for testing purposes.

One thing to note is a cell with a negative number is aligned to the left since it is treated as a string. You can check it with `with-fix-number.csv` file.

[with-fix.csv](https://github.com/woocommerce/woocommerce-admin/files/6634803/with-fix.csv)
[with-fix-number.csv](https://github.com/woocommerce/woocommerce-admin/files/6634804/with-fix-number.csv)
[without-fix.csv](https://github.com/woocommerce/woocommerce-admin/files/6634805/without-fix.csv)

**Comment by naman03malhotra** [comment]
>The OWASP site says to remove tab characters from the beginning of cells:

Thanks Jeff, good catch, it got missed!

>Google Sheets still treats a cell with a tab character as a formula.
Somehow it was working well for me, I will have to re-check, I'll take this for a test drive in the early coming week.

File: packages/csv-export/src/test/index.js (hunk 1 above)
Comment (naman03malhotra) [reply packages/csv-export/src/test/index.js]: >One thing to note is a cell with a negative number is aligned to the left since it is treated as a string

Can you please share a screenshot, with numbers on mac they are aligned to the right. 🤔 

image


Also I've tested it once again, it is working well with google sheets and numbers.

image

**Comment by naman03malhotra** [comment]
>It turned out that the change doesn't work on Google Sheets. Google Sheets still treats a cell with a tab character as a formula.

Interestingly the cell with a tab character is working normally for me with Google Sheets, maybe I am missing something?

File: packages/csv-export/src/test/index.js (hunk 1 above)
Comment (moon0326) [reply packages/csv-export/src/test/index.js]: @naman03malhotra Thank you for the review 👍 

My apologies for the confusion. The left-aligned number only appears on Microsoft Excel, not on Google Sheets.

Microsft Excel also treats the cell as a string with the tab char included as you see on the screenshot. 

Sceenshot:

Screen Shot 2021-06-16 at 7 07 39 PM

**Comment by moon0326** [comment]
@naman03malhotra Hi ✋ I just wanted to let you know that `csv-export` 1.3.2 has been published [here](https://www.npmjs.com/package/@woocommerce/csv-export/v/1.3.2). I noticed that `woocommerce-payments` is installing `@woocommerce/components` version 5. You need to install `@woocommerce/components` version 6.1.2 and up to use `csv-export` 1.3.2.
