### PR TITLE
Fix marketing extensions tracks

### LINKED ISSUE #7903: Business features step: tracks not working with marketing extensions
### Describe the bug
The `install_mailpoet` and `install_google_listings_and_ads` of `wcadmin_storeprofiler_store_business_features_continue` are not being fired when the extensions are installed in the Business features step

### To Reproduce

1. Create a new store and opt-in to share usage tracking
2. Fill the store profiler until the business features step
3. Install the Mailpoet and Google Listing and Ads extensions in the business step
4. See that `wcadmin_storeprofiler_store_business_features_continue` fires without the `install_mailpoet` and `install_google_listings_and_ads` event props

### Actual behavior:
Some event props of `wcadmin_storeprofiler_store_business_features_continue` are showing the value `undefined` when the extensions are installed, namely: `install_mailpoet` and `install_google_listings_and_ads`	

### Expected behavior
The value should be true or false, depending if the extension is installed

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #7903

This PR fixes the marketing extensions tracks.

### Screenshots

screenshot-one wordpress test-2021 11 07-17_11_45

### Detailed test instructions:

1. Open the browser devtools, go to the `Console` and enable the debug messages, you can do it by following the steps detailed here(P90Yrv-1Wj-p2 #debug-devtools).
2. Go to the 4th step of the Onboarding wizard (Business Details) and click `Free features`.
3. Verify the event `wcadmin_storeprofiler_store_business_features_continue` is recorded with the props `install_google_listings_and_ads` and `install_mailpoet` after pressing `Continue`.

### CODE REVIEW

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js [hunk 1]
```diff
@@ -92,7 +92,10 @@ class BusinessDetails extends Component {
 				extensionInstallationOptions[
 					'woocommerce-services:shipping'
 				] || extensionInstallationOptions[ 'woocommerce-services:tax' ],
+			install_google_listings_and_ads:
+				extensionInstallationOptions[ 'google-listings-and-ads' ],
 			install_jetpack: extensionInstallationOptions.jetpack,
+			install_mailpoet: extensionInstallationOptions.mailpoet,
 			install_wcpay:
 				extensionInstallationOptions[ 'woocommerce-payments' ],
 		} );
```
Comment (louwie17) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/index.js:101]: Just noting here that it would be great to refactor this, so we don't have to specify the specific plugin names in the track. As this would still require us to rely on wc admin release sequence if we wanted to add a new plugin, when every thing else relies on the free features config.
Given this might get cherry picked we shouldn't do this as part of this PR, but maybe we should create a separate issue for this? @octaedro

**Review by louwie17 — APPROVED** [review]
This tested well, thanks for fixing this @octaedro. I did leave one comment for something we should address in another PR, let me know what you think and if you want me to create the issue instead?

**Comment by mattsherman** [comment]
@octaedro @louwie17 I agree that we should refactor things to make this more robust. I've created #7912 to track this refactoring. This PR can be merged. Thanks for the fix!

**Comment by octaedro** [comment]
Thank you @louwie17 for the review,
I agree, it's a good idea to improve this part of the code. With this fix, I just wanted to have this working as soon as possible, keeping in mind that it will be refactored in the near future.

**Comment by octaedro** [comment]
Thanks @mattsherman for creating the follow-up issue 🙂
