### PR TITLE
Sync the category lookup table when a new category gets created

### LINKED ISSUE #6613: [GlobalStep] "Categories" fails to appear under Categories section on "Analytics->Categories" screen.
## Bug Description:
"Categories" fails to appear under Categories section on "Analytics->Categories" screen.

## Environment:
Woocommerce Version: WooCommerce 5.1 and 5.0
WordPress version: (v5.7)
WooCommerce Admin version: v2.0.2

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Add some Products.
1. Place some orders from frontend with different categories.
1. Go to "Analytics->Categories" screen.
1. Observe that "Categories" fails to appear under Categories section

## Actual Result:
"Categories" fails to appear under Categories section on "Analytics->Categories" screen.

## Expected Result:
"Categories" should be displayed under Categories section on "Analytics->Categories" screen.

## ScreenShot:

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://petite-stag.jurassic.ninja
Site address (URL): https://petite-stag.jurassic.ninja
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 4.01MB
Database Data Size: 2.53MB
Database Index Size: 1.48MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
nav_menu_item: 5
page: 7
post: 2
product: 19
product_variation: 7
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Query Monitor: by John Blackbourn – 3.6.7
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.3
Facebook for WooCommerce: by Facebook – 2.3.2
Jetpack by WordPress.com: by Automattic – 9.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Payments: by Automattic – 2.1.0
WooCommerce Shipping & Tax: by Automattic – 1.25.8
WooCommerce: by Automattic – 5.0.0 (update to version 5.1.0 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 13
Oldest: 2021-03-17 07:49:03 +0000
Newest: 2021-03-17 13:27:59 +0000

`

```
</details>

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #6613 

This PR syncs the category lookup table when a new category gets created.

The issue described in 6613 is caused due to missing category values in the lookup table.
We never created a new row when a new category gets added.

For those users who are already having the category lookup sync issue, they can deactivate and activate the plugin again. It should sync the table.

### Detailed test instructions:

Testing the table

1. Start with `trunk` branch to see the issue.
2. Open `wp_wc_category_lookup` table.
2. Navigate to Products -> Categories
3. Add a new category.
4. Confirm that the table doesn't have a matching record for the category you just created.
5. Switch to `fix/6613-new-categories-are-not-being-displayed` branch
6. Repeat the same step and confirm that you now have a matching row in the table.

Testing the Analytics data

1. Navigate to Products -> Add New
2. Add a new category on the Add New page and assign the product to it.
3. Place an order with the product
4. Navigate to Analytics -> Categories
5. You should see the category.

### CODE REVIEW

File: src/CategoryLookup.php [hunk 1]
```diff
@@ -130,6 +132,15 @@ public function on_edit( $category_id ) {
 		$this->update( $category_id );
 	}
 
+	/**
+	 * When a product category gets created, add a new lookup data.
```
Comment (joshuatf) [inline src/CategoryLookup.php:136]:
```suggestion
	 * When a product category gets created, add a new lookup row.
```

**Review by joshuatf — APPROVED** [review]
Really nicely done, @moon0326!  Small typo, but pre-approving as this is testing well.  🚢

File: src/CategoryLookup.php (hunk 1 above)
Comment (moon0326) [reply src/CategoryLookup.php]: Thank you 👍 Fixed in https://github.com/woocommerce/woocommerce-admin/pull/7290/commits/ae90368f5ca2f7a1ad652042c00eeff353366036
