### PR TITLE
Onboarding: Fix new business step error

### LINKED ISSUE #6127: Onboarding: New Business Step Fails to Set Installed Extensions in Option
**Describe the bug**
When testing out the new [Business Features Step](https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.0#business-features-install-free-extensions), @tammullen encountered an issue with being redirected from the OBW flow to the Mailchimp setup flow when using the beta of 5.0 with 1.9 RC.

I was able to reproduce this bug on a new JN site using the steps linked above in the 5.0 testing wiki ( https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.0#business-features-install-free-extensions ).

I also confirmed my hunch as to why this is happening - it seems the new business extensions flow is not updating the `woocommerce_onboarding_profile` site option with the values of the extensions installed on the new business step. Tam confirmed this too by going through the old/existing business details step and installing Mailchimp through that approach.

Mailchimp, and Creativemail both use this site option to sniff out if their extension was installed through the Woo OBW, and prevent their standard setup redirects if so. Here is [the code that mailchimp uses](https://github.com/mailchimp/mc-woocommerce/blob/9b13927dba53ef81db5794e3940f5ced7c4f8198/includes/class-mailchimp-woocommerce-options.php#L38-L45) to detect this to give you an idea of why this bug is happening.

When looking at the `woocommerce_onboarding_profile` produced from the new Business Step - it shows that the `business_extensions` array is not set at all:

```
userd1728360@jurassic-ninja2:~/apps/userd1728360/public$ wp option get woocommerce_onboarding_profile
array (
  'setup_client' => false,
  'industry' => 
  array (
    0 => 
    array (
      'slug' => 'food-drink',
    ),
  ),
  'product_types' => 
  array (
    0 => 'physical',
    1 => 'memberships',
  ),
  'theme' => 'twentytwentyone',
  'completed' => true,
)
``` 

**To Reproduce**
Steps to reproduce the behavior - you will need to do this on a new site, or delete the `woocommerce_onboarding_profile` site option value on your test environment.

1. Follow the test instructions [here](https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.0#business-features-install-free-extensions)
2. Be sure to either accept all default extensions, or make sure you have Mailchimp selected
3. After completing the theme step, note you are redirected to the Mailchimp setup flow.

**Expected behavior**

That all extensions installed as part of the business step in the OBW populate the `business_extensions` array, and to not be redirected to Mailchimp setup during the Woo OBW.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #6127

This PR fixes the empty string filtering in OBW.

There was a problem when filtering empty values before updating `woocommerce_onboarding_profile `, in the new business step of the OBW. The filtering was changing the object structure.
With this fix, the filtering of empty values should work normally. 

### Screenshots
screenshot-five wordpress test-2021 01 21-15_36_38

### Detailed test instructions:
1. Follow the test instructions [here](https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.0#business-features-install-free-extensions)
2. Be sure to either accept all default extensions or make sure you have Mailchimp selected.
3. Finish the OBW.
4. Verify you're not being redirected to the Mailchimp setup during the Woo OBW.
5. Confirm that all extensions installed as part of the business step in the OBW populate the `business_extensions` array. You can check that using `wp-cli`:
```
wp option get woocommerce_onboarding_profile
```
or executing the SQL statement:
```
SELECT * FROM `wp_options` WHERE `option_name` = 'woocommerce_onboarding_profile';
```

### CODE REVIEW

File: client/profile-wizard/steps/business-details/flows/selective-bundle/index.js [hunk 1]
```diff
@@ -117,9 +117,9 @@ class BusinessDetails extends Component {
 		};
 
 		// Remove possible empty values like `revenue` and `other_platform`.
-		const updates = Object.entries( _updates ).filter( ( { value } ) => {
-			return value !== '';
-		} );
+		Object.keys( updates ).forEach(
```
Comment (louwie17) [inline client/profile-wizard/steps/business-details/flows/selective-bundle/index.js:120]: Nice catch @octaedro

**Review by louwie17 — APPROVED** [review]
Looks good, and tested well, nice work @octaedro
Seeing the business extensions now:
Screen Shot 2021-01-21 at 3 18 50 PM
