### PR TITLE
Show parent as default back button label

### LINKED ISSUE #5434: Third level in navigation doesn't show correct back button label
**Describe the bug**
When navigating 3 levels deep in the navigation, the back button is not showing the parent menu, but still shows "WooCommerce Home."

**To Reproduce**

1. Enable the navigation.
1. Activate the plugin from this PR https://github.com/woocommerce/woocommerce-admin/pull/5425
1. Navigate to Marketing-> Example Marketing Category.1
1. Note the back button.

**Expected behavior**
Expected the default back button label to be the parent menu.

**Screenshots**
Screen Shot 2020-10-20 at 5 13 18 PM

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #5434

Shows the parent menu as the default back button label if none is supplied by the category.

### Screenshots

Screen Shot 2020-10-20 at 5 22 42 PM

### Detailed test instructions:

1. Enable the navigation.
1. Activate the plugin from this PR https://github.com/woocommerce/woocommerce-admin/pull/5425
1. Navigate to Marketing-> Example Marketing Category.1
1. Note the back button label is "Marketing."
1. Make sure no other regressions have occurred with other categories.

### CODE REVIEW

File: client/navigation/components/container/index.js [hunk 1]
```diff
@@ -86,7 +86,11 @@ const Container = ( { menuItems } ) => {
 						title={ category.title }
 						menu={ category.id }
 						parentMenu={ category.parent }
-						backButtonLabel={ category.backButtonLabel }
+						backButtonLabel={
```
Comment (becdetat) [inline client/navigation/components/container/index.js:89]: Is this really needed?

If it is, `backButtonLabel={ category.backButtonLabel || null }` would be more succinct and easier to grok.

**Review by becdetat — APPROVED** [review]
Everything looks great, I just had one minor nitpick. Pre-approving this.

File: client/navigation/components/container/index.js (hunk 1 above)
Comment (joshuatf) [reply client/navigation/components/container/index.js:89]: It is needed to show "WooCommerce Home" that is defined by the server, but agreed that your recommended syntax is more succinct- thanks for the suggestion!
