### PR TITLE
Display the store setup link on the homescreen if the task list is incomplete.

### LINKED ISSUE #5137: Activity panel appearing with incomplete setup tasks
**Describe the bug**
With the current core release (4.5.2) I'm seeing the activity panel (with Orders, Stock, and Reviews links) in the app bar on the home screen when the Setup tasks are still incomplete.

**To Reproduce**

1. Create a new test site and update to the latest release
2. Click on 'WooCommerce Home'
3. See error (activity panel appears)

**Expected behavior**
When store setup tasks haven't been completed and the setup card hasn't been dismissed, the activity panel should not appear on the Home screen.

**Screenshots**
Screen Shot 2020-09-13 at 8 47 34 PM

**Desktop (please complete the following information):**

* OS: Mac OS 10.15.6
* Browser: Firefox 80.0.1 and Chrome 85.0.4183.102

### PR DESCRIPTION
**Pull request by samueljseay**
Fixes #5137 

The original PR that implemented the store setup link made some assumptions about when it should be shown. This fixes the incorrect assumptions made there (See the comments in #5137 for more details).

The original PR assumed that we wouldn't want to show the store setup link on the home screen, but that was incorrect. The desire is not to show the other options and *just* show the setup link if the setup task list is not complete yet.

### Detailed test instructions:

1. On a woocommerce site that has not had the task list complete yet, go to the homescreen
2. Observe that the only tab displayed is the store setup link
3. Finish the task list
4. Observe that now the orders stock and reviews tabs are available but the store setup link is no longer displayed.

Also note that the existing display logic should be respected such as:

1. The store setup link will not display when you're performing a setup task
2. reviews should only display if reviews are enabled
3. stock should only display if the manage stock setting is enabled
4. help should only display when performing setup tasks

### Changelog Note:
Fix: display the store setup link on the homescreen if the task list is incomplete.

### CODE REVIEW

**Comment by samueljseay** [comment]
@timmyc I know Pedro was keen for this to make it in to 1.6

File: client/header/activity-panel/test/index.js [hunk 1]
```diff
@@ -120,4 +120,32 @@ describe( 'Activity Panel', () => {
 		// Expect that "Help" tab is absent.
 		expect( screen.queryByText( 'Help' ) ).toBeNull();
 	} );
+
+	it( 'should only render the store setup link when TaskList is not complete', () => {
```
Comment (timmyc) [inline client/header/activity-panel/test/index.js:124]: 🥇

**Review by timmyc — APPROVED** [review]
Thanks Sam, this is testing out well for me, and really appreciate the tests added here too.

**Comment by timmyc** [comment]
Cherry picked to release/1.6.0 in https://github.com/woocommerce/woocommerce-admin/commit/bef6d5858285e2113d5196f83d6ad55afb2e0d3c
