### PR TITLE
Make individual note classes internal

### LINKED ISSUE #8267: All individual note classes should be made internal
Generic note classes and traits should remain public.

Also go through `Note` and `Notes` and make functions private where possible, keep `NotesUnavailableException` public.

My estimate: 2 hours

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #8267
This PR makes individual notes classes internal.

The classes that [remain public](https://github.com/woocommerce/woocommerce-admin/tree/dev/8267/src/Notes) are:

- [Note](https://github.com/woocommerce/woocommerce-admin/blob/dev/8267/src/Notes/Note.php)
- [Notes](https://github.com/woocommerce/woocommerce-admin/blob/dev/8267/src/Notes/Notes.php)
- [NoteTraits](https://github.com/woocommerce/woocommerce-admin/blob/dev/8267/src/Notes/NoteTraits.php)
- [NotesUnavailableException](https://github.com/woocommerce/woocommerce-admin/blob/dev/8267/src/Notes/NotesUnavailableException.php)
- [DataStore](https://github.com/woocommerce/woocommerce-admin/blob/dev/8267/src/Notes/DataStore.php)
- [DeprecatedNotes](https://github.com/woocommerce/woocommerce-admin/blob/dev/8267/src/Notes/DeprecatedNotes.php)

Removed:

- Since the class `OnboardingTraits` is not being used, I removed it. It was added to [the "Getting started in Ecommerce" inbox note](https://github.com/woocommerce/woocommerce-admin/pull/6086) but now it has been removed.

### Detailed test instructions:

- Test every note, to be sure that everything is still working correctly.

### CODE REVIEW

File: src-internal/Admin/Events.php [hunk 1]
```diff
@@ -9,43 +9,43 @@
...
-use \Automattic\WooCommerce\Admin\Notes\TrackingOptIn;
+use \Automattic\WooCommerce\Internal\Admin\Notes\AddingAndManangingProducts;
+use \Automattic\WooCommerce\Internal\Admin\Notes\ChoosingTheme;
+use \Automattic\WooCommerce\Internal\Admin\Notes\CustomizingProductCatalog;
+use Automattic\WooCommerce\Internal\Admin\Notes\FirstDownlaodableProduct;
+use \Automattic\WooCommerce\Internal\Admin\Notes\InsightFirstProductAndPayment;
+use \Automattic\WooCommerce\Internal\Admin\Notes\MobileApp;
+use \Automattic\WooCommerce\Internal\Admin\Notes\NewSalesRecord;
+use \Automattic\WooCommerce\Internal\Admin\Notes\TrackingOptIn;
 use \Automattic\WooCommerce\Admin\Notes\OnboardingEmailMarketing;
```
Comment (louwie17) [inline src-internal/Admin/Events.php:20]: Can this import be deleted, given it's not used anymore? (OnboardingEmailMarketing)

**Review by louwie17 — APPROVED** [review]
Approving this, nice work @octaedro, notes still seemed to word as expected. I just left one suggestion for a line removal, but that shouldn't affect anything, so you got an approval from my end.
I feel like I need a day off now though after going through all the notes 😴

File: src-internal/Admin/Events.php (hunk 1 above)
Comment (octaedro) [reply src-internal/Admin/Events.php:20]: Thank you @louwie17 for your review. I like the removal idea but since this is a pretty big PR, if it's ok for you I'll merge this PR, create an issue and tackle this in a follow-up PR.

Comment (louwie17) [reply src-internal/Admin/Events.php:20]: Yeah that's fine with me

Comment (octaedro) [reply src-internal/Admin/Events.php:20]: I just created [a PR to remove the importation](https://github.com/woocommerce/woocommerce-admin/pull/8446) of `OnboardingEmailMarketing`.
