### PR TITLE
Use integers for add_menu_page priority

### LINKED ISSUE #8291: Wordpress 6.0 alpha fatals on loading Woocommerce admin
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In wordpress 6.0 i get this notification error on the latest woocommerce beta running

Notice: Function add_menu_page was called incorrectly. The seventh parameter passed to add_menu_page() should be an integer representing menu position. Please see Debugging in WordPress for more information

Version 6.2.0-rc.1

class-wc-admin-menus.php is not using a integer but a float on line 64 & 76

afbeelding

also in wp-content/plugins/woocommerce/packages/woocommerce-admin/src.WcPayWelcomePage.php line 51 & 75

afbeelding

also in/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/PageController.php line 441  should be intval($options['position'])

afbeelding

Please fix

### Expected behavior

change the float to a integer

### Actual behavior

just turn on debug mode and visit any admin page.

### Steps to reproduce

Just update to latest beta wp 6.0

### WordPress Environment

not needed

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #8291

In wordpress >= 6.0, the seventh parameter passed to `add_menu_page()` should be an integer representing menu position.

image

### Detailed test instructions:

1. Clone a copy of [latest Wordpress](https://github.com/WordPress/WordPress/), take note of the path that you cloned it to.
2. Make a copy of `.wp-env.json` and name it `.wp-env.override.json`
3. Change the value of the key "core" to the path of the Wordpress install above and use `Nightly` woocommerce, e.g:

```
{
	"phpVersion": "7.4",
	"core": "<replace-with-wordpress-path>",
	"plugins": [
		".",
		"https://github.com/woocommerce/woocommerce/releases/download/nightly/woocommerce-trunk-nightly.zip"
	],
	"config": {
		"JETPACK_AUTOLOAD_DEV": true,
		"WP_DEBUG_LOG": true,
		"WP_DEBUG_DISPLAY": true,
		"ALTERNATE_WP_CRON": true
	}
}
```
 We need to use Nightly WooCommerce core because the `class-wc-admin-menus.php` has been fixed in [this commit](https://github.com/woocommerce/woocommerce/commit/de57b39d8ec7afb76cd11fc52c8b81cd753ede66) for the same error, but not release yet.

4. Start the site and go to **WooCommerce > Home**
5. Should no errors and menus be added properly.

### CODE REVIEW

File: src-internal/Admin/WcPayWelcomePage.php [hunk 1]
```diff
@@ -72,7 +72,7 @@ public function register_payments_welcome_page() {
 				'admin.php?page=wc-admin&path=/wc-pay-welcome-page',
 				null,
 				$menu_icon,
-				55.7,
+				56,
```
Comment (ilyasfoo) [inline src-internal/Admin/WcPayWelcomePage.php:75]: Maybe try `57` instead?

**Review by ilyasfoo — APPROVED** [review]
A minor thing, it seems the menu position is changed. 

**Before:**
image


**After:**
image

Otherwise LGTM, pre-approving!

File: src-internal/Admin/WcPayWelcomePage.php (hunk 1 above)
Comment (chihsuan) [reply src-internal/Admin/WcPayWelcomePage.php:75]: Looks like `57` will make the menu item go down and `55` will somehow make it before WooCommerce. 

So I changed `Analytics`  position to `57` instead in https://github.com/woocommerce/woocommerce-admin/pull/8399/commits/aa888ed1efbed9a0ccebeeb5d06d0cb52e39a46f.

- `WooCommerce`: `55`
- `Products`: `55`
- `Payments `: `56`
- `Analytics`: `57` <-- changed
- `Marketing`: `58`

Results:

Screen Shot 2022-03-07 at 14 39 26

**Review by ilyasfoo — APPROVED** [review]
Good catch, @chihsuan!

I've re-tested this with WP 6.0 and WC nightly, the fix is working well:

image

LGTM :shipit:
