### PR TITLE
Include onboarding settings on the analytic pages

### LINKED ISSUE #7081: [GlobalStep] User navigates to "Blank" screen upon clicking "Continue" button on "Store details".
## Bug Description:
After visiting Analytics reports page and when user performs on boarding wizard, User navigates to "Blank" screen upon clicking "Continue" button on "Store details".

## Environment:
Woocommerce Version : WooCommerce 5.4 RC1 /5.3.0
WordPress version: (v5.7)

## PC:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Go to Analyatic report page.
1. Full refresh the page.
1. Go to Woocoomerce> Home.
1. Click on Store Details option.
1. Click on "Countinue" button.
1. Observe that  User navigates to "Blank" screen upon clicking "Continue" button.

## Actual Result:
After visiting Analytics reports page and when user performs on boarding wizard, User navigates to "Blank" screen upon clicking "Continue" button on "Store details".

## Expected Result:
User should redirected to next step upon clicking continue button.

## Video:

https://user-images.githubusercontent.com/41110392/119856498-60e6b580-bf30-11eb-84ac-4a935df0365c.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://vertical-junglefowl.jurassic.ninja
Site address (URL): https://vertical-junglefowl.jurassic.ninja
WC Version: 5.4.0
REST API Version: ✔ 5.4.0
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: ❌ 5.8-alpha-51015 - There is a newer version of WordPress available (5.8-alpha-51034)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.0
WC Database Prefix: wp_
Total Database Size: 10.06MB
Database Data Size: 7.45MB
Database Index Size: 2.61MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
mailpoet_page: 1
page: 10
post: 2
product: 22
product_variation: 11
revision: 7
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.8
Facebook for WooCommerce: by Facebook – 2.5.0
Google Listings and Ads: by WooCommerce – 0.5.6
Gutenberg: by Gutenberg Team – 10.7.1
Jetpack by WordPress.com: by Automattic – 9.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
MailPoet 3 (New): by MailPoet – 3.62.0
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Payments: by Automattic – 2.4.0
WooCommerce PayPal Payments: by WooCommerce – 1.3.1
WooCommerce: by Automattic – 5.4.0-rc.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.1.0

Test jQuery Updates: by The WordPress Team – 2.0.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 25
Oldest: 2021-05-26 06:56:13 +0000
Newest: 2021-05-27 11:00:32 +0000


### Status report information ###

Generated at: 2021-05-27 15:55:16 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #7081 

The underlying cause for the issue is that we don't add onboarding settings to JS `wcSettings` on the analytic pages. This PR adds JS onboarding settings on the analytics pages.

### Detailed test instructions:

1. Finish the onboarding wizard as usual.
2. Navigate to one of the analytic pages then refresh the page.
3. Navigate to WooCommerce -> Home and start OBW again.
4. Click the continue button.
5. OBW should continue without an error.

### CODE REVIEW

File: src/Features/Onboarding.php [hunk 1]
```diff
@@ -630,8 +630,23 @@ public static function delete_themes_transient() {
 	 *
```
Comment (ilyasfoo) [inline src/Features/Onboarding.php:630]: Nitpicky but maybe the comment can be updated

File: src/Features/Onboarding.php [hunk 2]
```diff
@@ -630,8 +630,23 @@ public static function delete_themes_transient() {
...
 	 * @return bool
 	 */
-	protected function is_home_or_setup_wizard_page() {
-		$allowed_paths = array( 'wc-admin', 'wc-admin&path=/setup-wizard' );
+	protected function is_wc_pages() {
+		$allowed_paths = array(
```
Comment (ilyasfoo) [inline src/Features/Onboarding.php:634]: I think having an exhaustive list like this is a bit problematic since we can't handle navigations from 3PDs whom built & register their pages via WCAdmin. An example of this is WCPay, I've tried and still able to reproduce the issue by navigating from `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fdeposits`.

I don't know the whole context for the usage of the function, but is using regex possible for our case? Or maybe generate the list using our page registry (I don't know if this is possible though)?

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
I confirmed this fixed analytics. However, I was able to reproduce using WCPay page. Maybe we need to change the method of generating the list.

File: src/Features/Onboarding.php (hunk 2 above)
Comment (moon0326) [reply src/Features/Onboarding.php:634]: Thank you @ilyasfoo. That's a really good point. I thought about the 3PDs use cases and I think this change is unrelated after all. This bug only happens if you're on a React router page then navigate to WooCommerce -> Home without a full refresh. Since 3PDs are not in our React router system, users will be forced to refresh when they navigate to WooCommerce -> Home.

Comment (ilyasfoo) [reply src/Features/Onboarding.php:634]: @moon0326 If I understand this correctly, WCPay registers their pages via our React router system, as seen [here](https://github.com/Automattic/woocommerce-payments/blob/develop/client/index.js#L28-L31) via a filter `woocommerce_admin_pages_list`. This means that any navigation between WCPay pages registered here to WCAdmin pages will not cause a refresh and reproduce the issue.

Comment (moon0326) [reply src/Features/Onboarding.php:634]: @ilyasfoo that's good to know. Thank you for letting me know 🙏 . I will test it out 👍

Comment (moon0326) [reply src/Features/Onboarding.php]: @ilyasfoo updated in https://github.com/woocommerce/woocommerce-admin/pull/7109/commits/a35bf6feecf464680fc8537e28848746e2b843b1

It now checks to see if the path starts with `wc-admin`. This should catch any pages that are registered under `wc-admin` path.

**Review by ilyasfoo — APPROVED** [review]
Changes make sense and tested well. Great work @moon0326! 🚢
