### PR TITLE
Fix dashboard task list menu placement

### LINKED ISSUE #4663: Task list ellipsis menu icon style issue
The task list ellipsis menu icon is centred, but it should be right-aligned.

**Screenshots**
image

### LINKED ISSUE #4675: Separate the home screen and dashboard styles
Per @joshuatf 's comments in #4664, we should separate the home screen and dashboard styles.

> Confirming that this fixes the issue, however I really think we should be separating out those styles specific to the homescreen and those used for the dashboard.

> This probably means that `woocommerce-homescreen-card` should be renamed to something like `woocommerce-dashboard-card` and separated into a dashboard stylesheet.

### PR DESCRIPTION
**Pull request by becdetat**
so it is styled correctly in the dashboard view.

Fixes #4663
Fixes #4675

The ellipsis menu on the task list in dashboard view is misaligned. This is because the new home screen styles weren't imported to the task list on the dashboard view.

### Screenshots
Before:
image

After:
image

### Detailed test instructions:

- Configure the home screen off in `/config/development.json` and restart `npm start`, or just build a zip from this branch and upload it to a fresh ephemeral site with the `woocommerce_task_list_hidden` option set to `no`
- Check the dashboard task menu style

### CODE REVIEW

File: client/task-list/index.js [hunk 1]
```diff
@@ -32,6 +32,7 @@ import {
  * Internal dependencies
  */
 import './style.scss';
+import '../homescreen/style.scss';
```
Comment (joshuatf) [inline client/task-list/index.js:35]: Confirming that this fixes the issue, however I really think we should be separating out those styles specific to the homescreen and those used for the dashboard.

This probably means that `woocommerce-homescreen-card` should be renamed to something like `woocommerce-dashboard-card` and separated into a dashboard stylesheet.

**Review by joshuatf — APPROVED** [review]
This is testing well to fix the issue.  Pre-approving, but I think we should create an issue around separating these styles prior to merging so we can follow-up on this.

**Comment by becdetat** [comment]
@joshuatf I did the followup in this PR as it was easier (and I can't merge yet anyway because of travis issues). Thanks for the suggestion :-)

**Comment by jeffstieler** [comment]
The merge blocking is my fault, sorry! I've removed that requirement from the `main` branch for now while I work with Travis support to restore our builds.

File: client/task-list/style.scss [hunk 2]
```diff
@@ -584,3 +584,27 @@
 		border-top-right-radius: 2px;
 	}
 }
+
+.woocommerce-dashboard-card {
```
Comment (joshuatf) [inline client/task-list/style.scss:588]: Let's move this to `dashboard/style.scss` since it's more generically used across dashboard items.

There's also one more reference to `woocommerce-homescreen-card` that we can update to `woocommerce-dashboard-card` and then we can remove the style block for `.woocommerce-homescreen-card`.

**Review by joshuatf — COMMENTED** [review]
>I did the followup in this PR as it was easier (and I can't merge yet anyway because of travis issues). Thanks for the suggestion :-)

Sounds good :)

One more suggestion and I think this is good to go.

**Comment by timmyc** [comment]
Going to close/reopen to get CI happy

**Comment by timmyc** [comment]
hi :)

**Comment by timmyc** [comment]
@becdetat since I commandeered this ship via the force push, I figured the polite thing to do was to also handle the feedback from Josh 😂 - could you verify all looks good here, and then we can merge and pick. Thanks!

**Comment by becdetat** [comment]
Looks good, I'll merge it now

**Comment by timmyc** [comment]
cherry picked to `release/1.3.0-rc.1` in f7a6deb34af4c950029973fa9d3a756b6d763ea5
