### PR TITLE
Fix for translation chunks not generated on plugin activation

### LINKED ISSUE #4615: Setup Wizard appears in other language than the WP one (es_ES)
Since last update (4.2.x) the installation/setup Wizard isn't in the WordPress Language.

I've tested it with the Spanish (Spain es_ES) that it's fully translated in GlotPress and in previous versions worked fine.

The onboarding tasks are in English too.

I must say that WooCommerce Admin plugin is always translated 100% to Spanish (Spain)

**To Reproduce**
1. Go to ¡Setup Wizard'
2. Click on 'Begin Setup
3. The first screen is in Spanish
4. Next screens are in English

**Screenshots**
First Wizard Screen (appears in Spanish): 
https://i.imgur.com/vmadVwp.png
Next Wizard Pages (suddenly in English):
https://i.imgur.com/bjMdR7S.png

**Expected behavior**
As the plugin (WooCommerce) is fully translated to es_ES the Wizard should be in Spanish

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WordPress 5.4.2 and WooCommerce 4.2.0
Site Default Language: Spanish (Spain) es_ES
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
`
### WordPress Environment ###

WordPress address (URL): https://aulawp.com/woo
Site address (URL): https://aulawp.com/woo
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.3.16
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wpj9_
Tamaño total de la base de datos: 8.33MB
Tamaño de los datos de la base de datos: 5.65MB
Tamaño del índice de la base de datos: 2.68MB
wpj9_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpj9_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpj9_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpj9_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpj9_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
fe0ffe_wpj9_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_options: Datos: 1.52MB + Índice: 0.08MB + Motor InnoDB
fe0ffe_wpj9_postmeta: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_posts: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
fe0ffe_wpj9_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
fe0ffe_wpj9_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
fe0ffe_wpj9_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
fe0ffe_wpj9_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
fe0ffe_wpj9_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
fe0ffe_wpj9_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
fe0ffe_wpj9_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
fe0ffe_wpj9_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_actionscheduler_actions: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wpj9_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wpj9_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_options: Datos: 2.28MB + Índice: 0.08MB + Motor InnoDB
wpj9_postmeta: Datos: 0.11MB + Índice: 0.03MB + Motor InnoDB
wpj9_posts: Datos: 0.06MB + Índice: 0.06MB + Motor InnoDB
wpj9_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpj9_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpj9_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpj9_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpj9_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpj9_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpj9_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpj9_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wpj9_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpj9_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpj9_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 20
custom_css: 1
customize_changeset: 1
nav_menu_item: 5
page: 10
post: 2
revision: 10
yith_wc_qof_1: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

ManageWP - Worker: por GoDaddy – 4.9.6
WooCommerce: por Automattic – 4.2.0
WP Reset: por WebFactory Ltd – 1.80

### Inactive Plugins (39) ###

Advanced Woo Search: por ILLID – 2.03
Autonomos: por Jose Conti – 1.4.0
Booster for WooCommerce: por Pluggabl LLC – 5.0.0 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
Campos de facturación en la página de registro de WooCommerce: por Fernando Tellado – 1.0 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
Contact Form 7: por Takayuki Miyoshi – 5.1.9
Control horas: por Superadmin – 1.0.1
Custom Product Tabs for WooCommerce: por YIKES
Inc. – 1.7.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0

Custom Related Products for WooCommerce: por Scott Nelle – 1.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
Jetpack by WordPress.com: por Automattic – 8.6.1
Join.chat: por Creame – 4.0.5
Kadence WooCommerce Email Designer: por Kadence WP – 1.4.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
Premmerce Permalink Manager for WooCommerce: por premmerce – 2.2.0 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
Sensei LMS: por Automattic – 3.1.1
SG Optimizer: por SiteGround – 5.5.6
Site Kit by Google: por Google – 1.9.0
wePOS - Point Of Sale (POS) for WooCommerce: por weDevs – 1.1.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce - MailerLite: por MailerLite – 1.4.8 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce - Show only lowest prices in variable products: por Fernando Tellado – 0.9.22
WooCommerce Admin: por WooCommerce – 1.2.4 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce Beta Tester: por WooCommerce – 2.0.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce Bulk Discount: por Rene Puchinger – 2.4.5 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce Checkout Manager: por QuadLayers – 5.1.2
WooCommerce Google Analytics Integration: por WooCommerce – 1.4.22
WooCommerce Menu Cart: por Jeremiah Prummer
Ewout Fernhout – 2.9.2

WooCommerce PayPal Checkout Gateway: por WooCommerce – 2.0.2 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.5.1
WooCommerce POS: por kilbot – 0.4.24 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce Price Based on Country (Basic): por Oscar Gare – 2.0.8
WooCommerce Redsys Gateway Light: por José Conti – 2.1.0
WooCommerce Services: por Automattic – 1.23.2
WooCommerce Shortcodes: por WooThemes
Claudio Sanches – 1.0.0 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0

WooCommerce Stripe Gateway: por WooCommerce – 4.4.0 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
Woo Out Of Stock Products: por Andrew Gunn – 2.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WP Mail SMTP: por WPForms – 2.1.1
YITH Quick Order Forms for WooCommerce Premium: por YITH – 1.2.2 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
YITH WooCommerce Multi-step Checkout Premium: por YITH – 1.9.2 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
YITH WooCommerce PDF Invoice and Shipping List Premium: por YITH – 2.0.14
YITH WooCommerce Subscription: por YITH – 1.4.3
Yoast SEO: por Team Yoast – 14.3

### Must Use Plugins (1) ###

ManageWP - Worker Loader: por GoDaddy –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: woocommerce/woocommerce#124 - /tienda/
Carrito: woocommerce/woocommerce#125 - /carrito/
Finalizar compra: woocommerce/woocommerce#11 - /finalizar-compra/
Mi cuenta: woocommerce/woocommerce#126 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Storefront
Version: 2.5.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completo: 34
Oldest: 2020-05-27 12:37:02 +0200
Newest: 2020-06-17 11:47:58 +0200

`
</details>

### PR DESCRIPTION
**Pull request by ilyasfoo**
Fixes https://github.com/woocommerce/woocommerce-admin/issues/4615 and https://github.com/woocommerce/woocommerce-admin/issues/6022.

Previously, combined JSON translation chunks are only generated on manually updating translation in WordPress' Updater via listening to `upgrader_process_complete` hook. However, when a plugin is installed **after** a site is set to another language, WordPress does not run `upgrader_process_complete` hook despite downloading the translation files after plugin installation (Correct me if I'm wrong, but I think it's because the plugin is not activated yet). As such, there will be cases where translated texts in JavaScript does not get translated.

This PR attempts to fix translation chunks not generated by listening to `activated_plugin` hook and combines the required chunks.

Requires https://github.com/woocommerce/woocommerce/pull/28698 to be merged in WooCommerce in order for the fix to work when WooCommerce Admin is an embedded package.

### Screenshot
image

### Steps to test
1. Create a test zip from this branch `npm run test:zip`
2. In a fresh JN site, set language to Español in `Settings > General`
3. Install & activate WooCommerce plugin
4. Upload zip plugin, install & activate
5. Go to WooCommerce store profiler screen and see that it is translated to Spanish

### CODE REVIEW

File: src/Loader.php [hunk 1]
```diff
@@ -634,6 +653,53 @@ public static function get_translation_chunk_data( $lang_dir, $domain, $locale )
...
+		if ( 'en_US' === $locale ) {
+			return;
+		}
+
+		if ( ! function_exists( 'get_filesystem_method' ) ) {
+			require_once ABSPATH . 'wp-admin/includes/file.php';
+		}
+
+		$access_type = get_filesystem_method();
+		if ( 'direct' === $access_type ) {
```
Comment (ilyasfoo) [inline src/Loader.php:681]: This is to prevent https://github.com/woocommerce/woocommerce-admin/issues/5062 from regressing. On installations where the default `FS_METHOD` is set to other than direct, wp_filesystem might not have the proper access.

File: src/Loader.php [hunk 2]
```diff
@@ -634,6 +653,53 @@ public static function get_translation_chunk_data( $lang_dir, $domain, $locale )
...
+			\WP_Filesystem();
+			global $wp_filesystem;
+
+			// Get all translation chunk data combined into a single object.
```
Comment (louwie17) [inline src/Loader.php:685]: @ilyasfoo could we consolidate lines 686-695 here with this piece of code as it is identical?: https://github.com/woocommerce/woocommerce-admin/blob/013e03e59fc27d297d3a3f3a688fd61e3f6bdede/src/Loader.php#L744-L754

File: src/Loader.php [hunk 3]
```diff
@@ -97,6 +97,25 @@ public function __construct() {
...
+	 *
+	 * @param string $filename Activated plugin filename.
+	 */
+	public static function activated_plugin( $filename ) {
+		$plugin_domain           = explode( '/', plugin_basename( __FILE__ ) )[0];
+		$activated_plugin_domain = explode( '/', $filename )[0];
+
+		// Ensure we're only running only on activation hook that originates from our plugin.
+		if ( $plugin_domain === $activated_plugin_domain ) {
+			self::generate_translation_strings();
```
Comment (louwie17) [inline src/Loader.php:117]: In this function would it also be worth to check if the files are already generated or not?
Given a user could now first activate WooCommerce, which generates the translations, and then activate WooCommerce admin separately, which would re-generate the translations again.

We can force update on `upgrader_process_complete`.

**Review by louwie17 — CHANGES_REQUESTED** [review]
Just left two refactor comments, aside from that everything looks good and tested well, saw the specific woocommerce-admin translations in the languages folder as well 👍 :
Screen Shot 2021-01-11 at 3 24 58 PM

File: src/Loader.php (hunk 2 above)
Comment (ilyasfoo) [reply src/Loader.php]: That's a good suggestion! Done in 6b0c557

File: src/Loader.php (hunk 3 above)
Comment (ilyasfoo) [reply src/Loader.php:117]: Actually, WooCommerce and WooCommerce Admin use different combined translations if both are installed. This is because the text domain `woocommerce` and `woocommerce-admin` is different for each, thus it's actually necessary to have both translations generated.

As an added point, I feel it's also better to be able to regenerate combined translations at will, for the following reasons:
1. It only runs on plugin activation, thus no perf overhead issues
2. In rare cases where the JSON file might get corrupted, a simple plugin reinstall would solve the problem

Comment (louwie17) [reply src/Loader.php:117]: Thanks, that sounds good to me.

**Review by louwie17 — APPROVED** [review]
Tested it one more time after the refactor, and everything still works as expected, it is good to 🚢  if you ask me 😄 

One bug I did notice, which I will create an issue (https://github.com/woocommerce/woocommerce-admin/issues/6063) for, is for the Notes. Once a note is up, it does not get translated anymore incase the language changes.
In the test case above, if I changed it back to english after seeing the Spanish translation the Note's would still be in Spanish.
