### PR TITLE
Fix industry tab not clickable after going back

### LINKED ISSUE #8440: Industry tab in setup wizard not clickable after going back
### Describe the bug
This is found using WCAdmin 3.3-beta.1, but I'm not sure if the bug existed prior. It seems when a user goes back to Store Details step via click its tab, Industry tab becomes unclickable.

### To Reproduce
1. Go to Setup Wizard
2. Go to the next step
3. Click on Store Details tab
4. Attempt to click Industry tab and observe it's not clickable

### Screenshots
https://d.pr/i/TKlGlU 
Full Size: https://d.pr/i/TKlGlU

### Expected behavior
Should be clickable

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #8440

This PR fixes the bug that the industry tab becomes unclickable when a user goes back to the Store Details step.

### Detailed test instructions:

- Go to Setup Wizard
- Go to the next step
- Click on the Store Details tab
- Confirm that Industry tab is clickable

### CODE REVIEW

File: client/profile-wizard/header.js [hunk 1]
```diff
@@ -71,29 +72,30 @@ export default class ProfileWizardHeader extends Component {
...
-		visibleSteps.map( ( step, index ) => {
+		visibleSteps.forEach( ( step, index ) => {
 			const previousStep = visibleSteps[ index - 1 ];
+			step.isComplete = step.isComplete || index < currentStepIndex;
 
-			if ( index < currentStepIndex ) {
-				step.isComplete = true;
-			}
+			const canClickStepLabel =
+				! previousStep || previousStep.isComplete || step.isComplete;
```
Comment (chihsuan) [inline client/profile-wizard/header.js:80]: Previously we used the `previousStep.isComplete` to decide whether the tab is clickable or not. This made the industry tab not clickable after going back.

File: client/profile-wizard/header.js [hunk 2]
```diff
@@ -71,29 +72,30 @@ export default class ProfileWizardHeader extends Component {
...
 
-			if ( ! previousStep || previousStep.isComplete ) {
-				step.onClick = ( key ) => {
```
Comment (chihsuan) [inline client/profile-wizard/header.js:82]: I simply moved this into a new class method.

File: client/profile-wizard/header.js [hunk 3]
```diff
@@ -71,29 +72,30 @@ export default class ProfileWizardHeader extends Component {
 			( step ) => step.key === currentStep
 		);
 
-		visibleSteps.map( ( step, index ) => {
+		visibleSteps.forEach( ( step, index ) => {
```
Comment (chihsuan) [inline client/profile-wizard/header.js:75]: Since we don't assign the return value to a variable, I think we just need to use the `forEach` here.

**Review by rjchow — APPROVED** [review]
Nice work, tests well! 🚢 
Thanks for adding a test!
