### PR TITLE
Fix task ID class check and add tests around tracking

### LINKED ISSUE #8183: Drop in wcadmin_tasklist_task_completed after 6.1 release
**Description:** there was a huge drop in the number `wcadmin_tasklist_task_completed` events after 6.1 release. I'm assuming that there's something wrong with this event, as all the other task list-related events show steady numbers.

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #8183 

Since updating the task API to use child classes instead of directly implementing a `Task` class, the list ID check was failing and not recording tracks.  This PR
* Fixes the list ID retrieval
* Adds tests around the list ID and the tracks to prevent this from happening again

### Detailed test instructions:

1. Delete the `woocommerce_task_list_tracked_completed_tasks` option in your database
2. Visit the homepage to trigger task list retrieval and tracks
3. Check that no errors appear in the error log
4. Visit `https://mc.a8c.com/tracks/live/?eventname=%25tasklist_%25&user=joshuaflow&useragent=` with your username and make sure the tracks come through `tasklist_task_completed` (may take up to ~20 min)
5. Make sure all tests pass

### CODE REVIEW

File: src/Features/OnboardingTasks/TaskTraits.php [hunk 1]
```diff
@@ -38,10 +38,14 @@ public function record_tracks_event( $event_name, $args = array() ) {
...
 
+		$prefixed_event_name = $this->prefix_event( $event_name );
+
 		wc_admin_record_tracks_event(
-			$this->prefix_event( $event_name ),
+			$prefixed_event_name,
 			$args
 		);
+
+		return $prefixed_event_name;
```
Comment (becdetat) [inline src/Features/OnboardingTasks/TaskTraits.php:48]: Can you document this return in the function doc above? Ta :-)

**Review by ilyasfoo — APPROVED** [review]
Tests well, LGTM! :ship
