### PR TITLE
Check if tax was successfully added before notice

### LINKED ISSUE #6031: [GlobalStep - WooCommerce 4.9 RC 2] "You've added your first tax rate" pop up is displayed for invalid entries.
## Bug Description:
"You've added your first tax rate" pop up is displayed for invalid entries.

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)
                
 
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Go to WooCommerce->Home.
1. Click on "Set up Tax" option present on Setup checklist.
1. Click on "Configure" button.
1. Now add a tax rate with invalid entries.
1. Click on "Save changes" button. 
1. Observe that "You've added your first tax rate" pop up is displayed and tax rate is not added.

## Actual Result:
"You've added your first tax rate" pop up is displayed for invalid entries.
 
## Expected Result:
"You've added your first tax rate" pop up should be display only if tax rate gets added.

## Video:

https://user-images.githubusercontent.com/41110392/104029389-ee2ea500-51ef-11eb-98eb-8f9b29660cef.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://wooden-marsupial.jurassic.ninja
Site address (URL): https://wooden-marsupial.jurassic.ninja
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.13
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.32-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 4.31MB
Database Data Size: 2.93MB
Database Index Size: 1.38MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Query Monitor: by John Blackbourn – 3.6.5
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.2.4 – Installed version not tested with active version of WooCommerce 4.0
Facebook for WooCommerce: by Facebook – 2.2.0
Jetpack by WordPress.com: by Automattic – 9.2.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.6
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
WooCommerce: by Automattic – 4.9.0-rc.2

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.0 (update to version 1.1 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-01-08 11:32:53 +0000
Newest: 2021-01-08 11:32:53 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #6031 

Check if tax was successfully added before notice.

### Screenshots
Invalid row
invalid
Doesn't render notice after click save changes
no notice
First valid row
螢幕快照 2021-01-28 下午8 18 06
Render notice
螢幕快照 2021-01-28 下午8 19 19

### Detailed test instructions:
- Set `add_onboarding_tax_notice_admin_script` condition to true.
- Go to WooCommerce settings -> Tax -> Standard rates.
- Insert row with invalid country code and save changes.
- Check that the "You've added your first tax rate!” message does not pop up.

-----------
- Insert row with valid country code and save changes.
- Check that the "You've added your first tax rate!” message pops up.

-----------

- Insert the second row with a valid country code and save changes.
- Check that the "You've added your first tax rate!” message does not pop up.

### CODE REVIEW

File: client/wp-admin-scripts/onboarding-tax-notice/index.js [hunk 1]
```diff
@@ -28,30 +27,36 @@ const saveCompleted = () => {
...
-				id: 'WOOCOMMERCE_ONBOARDING_TAX_NOTICE',
-				actions: [
-					{
-						url: getAdminLink( 'admin.php?page=wc-admin' ),
-						label: __( 'Continue setup.', 'woocommerce-admin' ),
-					},
-				],
+	saveCompleted().then( () => {
+		// Check if a row was added successfully after WooCommerce removes invalid rows.
+		setTimeout( () => {
```
Comment (louwie17) [inline client/wp-admin-scripts/onboarding-tax-notice/index.js:36]: I think we could prevent the use of `setTimeout` here by checking if the `saveButton` is disabled again.
When trying this locally it seemed that the `saveCompleted` function didn't work accurately anymore, it never hit the case where it found `.blockUI.blockOverlay`.
We could switch that to `if (saveButton.disabled) {`.
It looked like the invalid rows where removed after the save button was set back to disabled as well.

Comment (louwie17) [inline client/wp-admin-scripts/onboarding-tax-notice/index.js:36]: I think we could prevent the use of `setTimeout` here by checking if the `saveButton` is disabled again.
When trying this locally it seemed that the saveCompleted function didn't work accurately anymore, it never hit the case where it found `.blockUI.blockOverlay` .
We could switch that to `if (saveButton.disabled) {`.
It looked like the invalid rows where removed after the save button was set back to disabled as well.

File: client/wp-admin-scripts/onboarding-tax-notice/index.js [hunk 2]
```diff
@@ -28,30 +27,36 @@ const saveCompleted = () => {
...
+						},
+					],
+				}
+			);
+		}, 500 );
+	} );
 };
 
-domReady( () => {
+window.onload = () => {
```
Comment (louwie17) [inline client/wp-admin-scripts/onboarding-tax-notice/index.js:57]: Is there a particular reason you decided to use `window.onload` vs the `domReady` library?

File: client/wp-admin-scripts/onboarding-tax-notice/index.js [hunk 3]
```diff
@@ -28,30 +27,36 @@ const saveCompleted = () => {
...
 	const saveButton = document.querySelector( '.woocommerce-save-button' );
-	if ( saveButton ) {
+	if ( ! document.querySelector( '.tips' ) && saveButton ) {
```
Comment (louwie17) [inline client/wp-admin-scripts/onboarding-tax-notice/index.js:59]: Thanks for adding this extra check, it might be worth making this selector a little more specific.
Maybe use `.wc_tax_rates .tips`?

**Review by louwie17 — COMMENTED** [review]
Thanks for working on this @hsingyuc :)

I just left a couple small suggestions, and one slightly bigger one in relation to the `saveCompleted` method, as it doesn't seem to work effectively anymore, I think fixing this would prevent us from using `setTimeout`.
I added a potential suggestion in the comments.

File: client/wp-admin-scripts/onboarding-tax-notice/index.js (hunk 2 above)
Comment (hsingyuc) [reply client/wp-admin-scripts/onboarding-tax-notice/index.js:57]: If we use `domReady`, `.tips` is still loading so the notice won't work. So I used `window.onload` to wait until `.tips` is loaded.

Comment (louwie17) [reply client/wp-admin-scripts/onboarding-tax-notice/index.js:57]: Gotcha, I believe the biggest difference between `domReady` and `onload` is that it also waits for any assets to load (like images and such), which I guess allows enough of a delay.

That being said I think we should still stick with the original `domReady` use. Mostly because as I was testing I noticed that this script isn't loaded when a tax rate was added ([see here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks.php#L261)), so we don't need it for that.
And the jquery script makes use of a global `htmlSettingsTaxLocalizeScript`, which contains a array of `rates`, so we could double check by using this.
`htmlSettingsTaxLocalizeScript && htmlSettingsTaxLocalizeScript.rates && htmlSettingsTaxLocalizeScript.rates.length > 0`

File: client/wp-admin-scripts/onboarding-tax-notice/index.js [hunk 4]
```diff
@@ -28,30 +27,36 @@ const saveCompleted = () => {
...
-				],
-			}
-		)
-	);
+	saveCompleted().then( () => {
+		// Check if a row was added successfully after WooCommerce removes invalid rows.
+		if ( ! document.querySelector( '.tips' ) ) {
+			return;
+		}
+		if ( saveButton.disabled ) {
```
Comment (louwie17) [inline client/wp-admin-scripts/onboarding-tax-notice/index.js:39]: Thanks for removing the `setTimeout`, and replacing it with this.
My apologies if I was kinda vague with the `saveButton.disabled` suggestion. I meant to update the `saveCompleted` method with using the disabled state like this:
```
const saveCompleted = ( saveButton ) => {
	if ( saveButton && ! saveButton.disabled ) {
		const promise = new Promise( ( resolve ) => {
			window.requestAnimationFrame( resolve );
		} );
		return promise.then( () => saveCompleted( saveButton ) );
	}

	return Promise.resolve( true );
};
```
You did have to pass the saveButton in on line 34 -> `saveCompleted(saveButton).then(...`
Currently it does this check `document.querySelector( '.blockUI.blockOverlay' )` which I don't think is relevant anymore.

Comment (hsingyuc) [reply client/wp-admin-scripts/onboarding-tax-notice/index.js]: Thank you for the feedback and sorry that I completely miss read it! The changes have been pushed.

**Review by louwie17 — APPROVED** [review]
Thanks for addressing all the feedback @hsingyuc it is working well :)
Approving this 🚀 
I believe all that is left is fixing the merge conflict (and maybe running npm install again given it's in the `package.json`).
