### PR TITLE
Execute single order pending jobs immediately when wp_debug is enabled

### LINKED ISSUE #1580: Order information is delayed in analytics
**Describe the bug**
The action scheduler takes care of a bunch of heavy lifting in the background, which is awesome.  One downside, is that orders sometimes take a couple minutes to show up.

While I think this is probably okay in the context of a normal site, it does seem to add on a bit of time for manual testing during development.  Adding a temporary `add_action( 'save_post', 'action_being_tested' );` hook resolves the issue, but this is more error prone and needs to be removed.

Could we consider using `WC_Helper_Queue::run_all_pending();` in dev environments?  Or is there anything else that might be slowing down the processing?

/cc @jeffstieler 

**To Reproduce**

1. Create an order.
2. Note that it takes a minute or two sometimes to show up in the `wc_order_stats` table.

**Expected behavior**
Would be nice if information was synced right away.

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #1580 

Executes any single order pending jobs immediately to avoid the delay in order syncing when developing.

**Questions**
* Does this cause any issues for debugging the action scheduler itself?  My hunch is no, but want to make sure.

### Detailed test instructions:

1.  Save/update an order.
2.  Note the order is immediately updated.
3.  Run the rebuild tool at WooCommerce->Status->Tools->Rebuild Reports.
4.  Make sure the rebuild is not processed right away and is handled in the background.

### CODE REVIEW

**Review by timmyc — COMMENTED** [review]
Big fan of this change - having to pause while testing new orders was getting a tad bit annoying.

So some thoughts: Instead of adding a new hook, and the new method of `execute_jobs_in_debug_mode` - would it make more sense to add in the `WP_DEBUG` check to the existing hooked method `schedule_single_order_process`, right after the check to ensure the post type is a `shop_order` do something like:

```
if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
 self::orders_lookup_process_order( $order_id );
 return;
}
```

This would circumvent the queue altogether, and save some queries by not having to see if the job is there/pending. 

At least I think that would work, haven't tested it ;)

One other minor thought on the change is if we merge this in, then it would have an impact on a live site if someone like a developer forgot to turn WP_DEBUG off, but there would probably be bigger problems then the job running right away if that happened.

**Comment by rrennick** [comment]
The downside of doing this is it would interfere with testing work with Action Scheduler (https://github.com/woocommerce/wc-admin/issues/1528#issuecomment-464152453). If this were implemented as a filter instead as a WP_DEBUG check we would be able to turn it off & on as needed.

**Comment by jeffstieler** [comment]
> The downside of doing this is it would interfere with testing work with Action Scheduler ([#1528 (comment)](https://github.com/woocommerce/wc-admin/issues/1528#issuecomment-464152453)). If this were implemented as a filter instead as a WP_DEBUG check we would be able to turn it off & on as needed.

+1

**Comment by joshuatf** [comment]
@rrennick Thanks for the input.  Replaced this with a filter in https://github.com/woocommerce/wc-admin/pull/1581/commits/84d9b9c462c97ba185441ad99bcfc4e58da2cc28.

@timmyc I like the idea of bypassing the scheduler altogether, but in order to do this, we need to run the action on `save_post` instead of `save_post_shop_order`, otherwise it's run too early and information is not updated until the next save.  @jeffstieler are there any issues with changing this back to `save_post`?

**Comment by jeffstieler** [comment]
> in order to do this, we need to run the action on `save_post` instead of `save_post_shop_order`, otherwise it's run too early and information is not updated until the next save. @jeffstieler are there any issues with changing this back to `save_post`?

Are we dependent on other `save_post` hooks for this to work properly? `save_post_{$type}` is fired right before `save_post`: https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3940

**Comment by rrennick** [comment]
@jeffstieler if you use `save_post` then all actions hooked into `save_post_shop_order` will have executed. If you use `save_post_shop_order` then you would need to give it a high priority number to ensure that other save hooks are fired before this one.

**Comment by jeffstieler** [comment]
@rrennick @joshuatf oh duh. Time to make more ☕️ 😄

File: includes/class-wc-admin-reports-sync.php [hunk 1]
```diff
@@ -132,6 +132,11 @@ public static function schedule_single_order_process( $order_id ) {
 			return;
 		}
 
+		if ( apply_filters( 'woocommerce_disable_scheduling', false ) ) {
```
Comment (jeffstieler) [inline includes/class-wc-admin-reports-sync.php]: Optional nitpick: should this filter name include "order" since it only prevents order updates from being queued?

**Review by jeffstieler — APPROVED** [review]
On optional nitpick, otherwise this works as intended. Nice addition to the readme as well. 🛳 it!

File: includes/class-wc-admin-reports-sync.php (hunk 1 above)
Comment (joshuatf) [reply includes/class-wc-admin-reports-sync.php]: Hmm, good point.  My thought process was that we may want to use this same hook to easily allow disabling across wc-admin and maybe eventually core so I opted to keep it generic.

But since we don't have this anywhere else right now, it may be a good idea to make it more descriptive.  I'll update to `woocommerce_disable_order_scheduling` and we can modify in the future if we want to disable scheduling elsewhere.
