### PR TITLE
Fix php notice when selecting paid theme

### LINKED ISSUE #8478: PHP Notice when the `Purchase` task is visible
### Describe the bug
After selecting paid a theme in the OBW, the following PHP notice is visible in the `debug.log` when loading the `Home` screen.

```
PHP Notice:  Undefined index: description in /src/Features/OnboardingTasks/Tasks/Purchase.php on line 82
```

It seems like replacing `description` with `excerpt` in the [line 82](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks/Tasks/Purchase.php#L82) should fix the problem.

### To Reproduce

- Go to 'Setup Wizard'
- Click on 'Themes / Choose' and select a paid theme
- Go to the `Home` screen.
- Verify that the `PHP notice` has been added to the `debug.log` file. 

### Screenshots

screenshot-gross-ermine jurassic ninja-2022 03 16-11_42_26

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #8478 

Removes the PHP notice, but also fixes issue where the task would disappear after the user installs the paid theme.

I also added some initial E2E tests, but they are currently not being used yet. I could move that to a separate PR for now.

### Detailed test instructions:

- Go to 'Setup Wizard'
- Click on 'Themes / Choose' and select a paid theme (like Bloom)
- Go to the Home screen.
- Make sure the purchase task shows up with the theme name that requires purchasing
- Open your `debug.log` and make sure it doesn't show a PHP notice
- Install the paid theme (for dev's you can find Bloom under https://woocommerce.com/my-account/downloads/ ), you can install it under **Appearance > Themes**
- Go back to **WooCommerce > Home**, notice how the purchase task now say's: `Add paid extensions to my store` and shows as completed.

**Do a quick check if paid products still work**
- Go to the `Setup Wizard` again by clicking **Store details**
- On the product types select a paid product (like memberships)
- Finish the onboarding by selecting the same paid theme as before (should show as installed)
- Once on homescreen the purchase task should say **Add <product type> to my store**

### CODE REVIEW

File: client/profile-wizard/steps/theme/index.js [hunk 1]
```diff
@@ -92,7 +92,10 @@ class Theme extends Component {
...
 		} );
 
-		if ( slug !== activeTheme && getPriceValue( price ) <= 0 ) {
+		if (
+			slug !== activeTheme &&
+			( getPriceValue( price ) <= 0 || isInstalled )
+		) {
 			if ( isInstalled ) {
 				this.activateTheme( slug );
 			} else {
```
Comment (octaedro) [inline client/profile-wizard/steps/theme/index.js:101]: Nitpick: I think that we could simplify this a  little bit by taking the `if ( isInstalled ) {`  out of the other `if`. It's frankly minimal, so I'm totally ok if you want to keep it like now.
The code would look like this:
```
	    if ( isInstalled ) {
			this.activateTheme( slug );
		} else {
			if ( slug !== activeTheme && getPriceValue( price ) <= 0 ) {
				this.installTheme( slug );
			} else {
				updateProfileItems( { theme: slug } );
			}
		}
```

File: packages/admin-e2e-tests/src/sections/onboarding/ThemeSection.ts [hunk 2]
```diff
@@ -13,4 +13,17 @@ export class ThemeSection extends BasePage {
...
+		const card = await title?.evaluateHandle( ( element ) => {
+			return element.closest( '.components-card' );
+		} );
+		const chooseButton = await card
+			?.asElement()
+			?.$x( `//button[contains(text(), "Choose")]` );
+		if ( chooseButton && chooseButton.length > 0 ) {
+			await chooseButton[ 0 ].click();
+		}
+	}
```
Comment (octaedro) [inline packages/admin-e2e-tests/src/sections/onboarding/ThemeSection.ts:28]: ❤️

**Review by octaedro — APPROVED** [review]
You did a great job fixing this bug @louwie17. I just left a small suggestion, but this is testing well on my end and the code looks good, so I'm going to pre-approve this PR.
