### PR TITLE
Fix country region select with autocomplete

### LINKED ISSUE #5523: Setup Wizard Address Inputs conflict with browser autocomplete
During initial store setup in the wizard, the store address fields (specifically the country/region field) act strangely in combination with browser autocomplete, and is difficult to use.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Expected behavior**
When filling in the store address:

1. The country list should be visible as I type and not be obscured by browser autocomplete.
2. After selecting something, it would be nice to jump to that position in the list if reopening the dropdown.
3. If autocomplete runs, it should either match against the correct country where possible, or leave the field blank - not default to the wrong country which is easily missed.

**Actual behavior**
This is more easy to replicate if you setup an address is chrome autofill settings and then use it during setup. 

**The browser doesn't seem to use COUNTRY for the country field** - it's using county (state) which doesn't match the country options in the dropdown which causes it to match against the wrong country on blur. In my case (UK) we don't have states.

**If browser autocomplete shows options, the options block the country dropdown making it difficult to make a selection.**

Setup Wizard ‹ WooCommerce ‹ one wordpress test — WooCommerce 2020-11-03 10-49-41

**If you type the full country name, it doesn't match on blur, it discards your input**

**If you choose the wrong country, you have to scroll through the list again, it doesn't start from your selection**

_This could likely be improved_ by adjusting which autocomplete fields are used when populating the fields (for some reason it uses county/state instead of COUNTRY in my case), and having a blank option (please select a country) to default to instead of the top country which is Afghanistan or some obscure match.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
I am testing on latest WC 4.8-dev default branch, and WP 5.5.3. Clean install, no other extensions active.

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #5523 

Fixes some issues with the country / region dropdown field, in particular when using auto complete.
Issues that should be fixed:
- After using autocomplete, not being able to change the country/region anymore manually
- Having the chrome auto fill overlap the typeahead search results of the country/region field
- Region didn't support abbreviations (my autocomplete has NS for Nova Scotia, but the dropdown defaulted to New Brunswick)

### Screenshots

country-region-autofill

### Detailed test instructions:

- Start a new WooCommerce store and go to **WooCommerce > Home** (make sure you have autofill enabled and some addresses configured)
- The onboarding flow should start, asking for the store address
- Do a autofill of the store address and make sure the Country/Region is correctly selected
- Now try each of these cases:
     - After using autocomplete, search for and select a country/region manually, it should change on click
     - Chrome should not show it's autofill ([as shown here](https://user-images.githubusercontent.com/90977/97976265-4f866200-1dc2-11eb-8546-e96f70cb9fad.png)) 
     - Clear the fields and make sure one of your auto complete addresses uses a abbreviated region (California -> CA) and see if it correctly selects the region with the country
- Feel free to try other things with the type ahead field and see if any odd behaviour happens and in other browsers like Safari or Firefox

### CODE REVIEW

File: client/dashboard/components/settings/general/store-address.js [hunk 1]
```diff
@@ -200,6 +215,7 @@ export function StoreAddress( props ) {
 			<SelectControl
 				label={ __( 'Country / Region', 'woocommerce-admin' ) }
 				required
+				autoComplete="new-password" // disable autocomplete and autofill
```
Comment (louwie17) [inline client/dashboard/components/settings/general/store-address.js:218]: This seems to be the only way to have the chrome autofill now show up. Chrome ignores the use of `autoComplete='off'` 😢

File: client/dashboard/components/settings/general/store-address.js [hunk 2]
```diff
@@ -86,6 +86,18 @@ export function useGetCountryStateAutofill( options, countryState, setValue ) {
...
+		const option = options.find( ( opt ) => opt.key === countryState );
+		const labels = option ? option.label.split( /\u2013|\u2014|\-/ ) : [];
+		const newCountry = ( labels[ 0 ] || '' ).trim();
+		const newState = ( labels[ 1 ] || '' ).trim();
+
+		if ( newCountry !== autofillCountry || newState !== autofillState ) {
+			setAutofillCountry( newCountry );
+			setAutofillState( newState );
+		}
+	}, [ countryState ] );
```
Comment (louwie17) [inline client/dashboard/components/settings/general/store-address.js:99]: Handle the `countryState` (user typing) state differently from the auto complete fields.
This makes it easier to know which is actually happening.

File: client/dashboard/components/settings/general/store-address.js (hunk 1 above)
Comment (joshuatf) [reply client/dashboard/components/settings/general/store-address.js:218]: Nice workaround!

File: client/dashboard/components/settings/general/store-address.js [hunk 3]
```diff
@@ -99,12 +111,15 @@ export function useGetCountryStateAutofill( options, countryState, setValue ) {
 		}
 		if ( autofillCountry.length && autofillState.length ) {
 			const stateSearch = new RegExp(
-				escapeRegExp( autofillState.replace( /\s/g, '' ) ),
+				escapeRegExp( autofillState.replace( /\s/g, '' ) ) + '$', // Always match the end of string for region.
 				'i'
 			);
+			const isStateAbbreviation = autofillState.length < 3;
```
Comment (joshuatf) [inline client/dashboard/components/settings/general/store-address.js:117]: Do we need to consider country abbreviations?

File: client/dashboard/components/settings/general/store-address.js (hunk 2 above)
Comment (joshuatf) [reply client/dashboard/components/settings/general/store-address.js:99]: I'm having some trouble parsing what this hook is for.  Could you elaborate a bit on this?

**Review by joshuatf — COMMENTED** [review]
Love the workaround here, @louwie17!  Left a few questions in the code.

I also noticed that if the field is already filled, autocomplete doesn't work when selecting a new address.  This feels a bit odd to me, but is this expected?

File: client/dashboard/components/settings/general/store-address.js (hunk 2 above)
Comment (louwie17) [reply client/dashboard/components/settings/general/store-address.js:99]: This is only triggered when the `countryState` is updated, which means the user manually selected a country/region from the typeahead field (they didn't use autofill).
In this case, to keep consistent with the autofill, we update the autofill fields with the selected item from the dropdown, which is mostly what is happening in this hook.

File: client/dashboard/components/settings/general/store-address.js (hunk 3 above)
Comment (louwie17) [reply client/dashboard/components/settings/general/store-address.js:117]: Probably not a bad idea, I only noticed the issue with state, but that was because I am using `Canada` and it's abbreviation matches nicely.
I will add that.

**Comment by louwie17** [comment]
> I also noticed that if the field is already filled, autocomplete doesn't work when selecting a new address. This feels a bit odd to me, but is this expected?

@joshuatf from what I remember it was expected, when I tried to select a new address it would only change the field I was specifically on and the `onChange` handlers would not be triggered for any of the other fields (if they were filled out, my browser gave the option to clear them first and then select a new address which worked fine).
Was this the case for you? Meaning, when you selected a different address did the city & postal code fields change? or did they remain the same? (if they were previously filled).

**Comment by louwie17** [comment]
@joshuatf are you able to have another look at this? I added abbreviation support for countries and fixed the clear form on autofill.

One thing to note, the way my autofill works is: If you modified a field after using autofill, and then try to clear it with autofill, it will only clear the fields that hadn't been modified.

File: packages/components/src/select-control/index.js [hunk 4]
```diff
@@ -559,6 +563,7 @@ SelectControl.defaultProps = {
 	showClearButton: false,
 	hideBeforeSearch: false,
 	staticList: false,
+	autoComplete: 'off',
```
Comment (joshuatf) [inline packages/components/src/select-control/index.js:566]: Should this default to `new-password` since `off` doesn't work with Chrome?  Or do you think consumers should be responsible for implementing this?

**Review by joshuatf — APPROVED** [review]
Testing well for my uses cases, thanks for nice solution, @louwie17.

Left one question about a default value, but a change might no be necessary and pre-approving ✅

File: packages/components/src/select-control/index.js (hunk 4 above)
Comment (louwie17) [reply packages/components/src/select-control/index.js:566]: I think consumers should still be responsible for this, as `new-password` isn't a natural way of turning it off. And from what I read, Chrome could decide to use `off` again if they so choose (`off` works fine on Safari and Firefox).
