### PR TITLE
Prompt a modal to save any unsaved changes in OBW

### LINKED ISSUE #7890: [Setup Wizard] User is allowed to make changes for their selected item or input fields but those changes are not getting saved.
### Describe the bug
In WooCommerce Setup Wizard flow user is allowed to move back to different sections of wizard flow (like Store Details, Industry, Product Types, Business Details and Theme) by clicking on those sections present at the top. Now once the user is on a particular section, He/She is allowed to make changes for their previously selected item or input fields but those changes are not getting saved if he moves back again to a different section by clicking on those sections present at the top.

### To Reproduce

1.  Install the WooCommerce plugin.
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open.
3. Complete the WooCommerce Setup Wizard flow by putting any values to the input field and selecting any options present on different pages.
4. Once the user is on the select theme section of the flow, Now again move back store details section by clicking the link present on top, Once the user is on the Store details section try to make some changes in the input fields like city, address, email etc. After making the changes move back to the theme section of the flow.
5. Once the user is back on the theme section, Now again move to the store details section of the flow by clicking the link present on the top and check whether user changes are saved or not which the user did in step-4.

**This issue is also reproducible if user moves back and forward using browser back and forward button.**

### Actual behavior:
Currently, the user is allowed to make changes on different sections of the wizard flow and those changes are not getting saved if he moves back to a different section of the setup flow.

### Screenshots

https://user-images.githubusercontent.com/19307354/140176932-94b7e9a6-3745-419f-aac2-ffebcbb95524.mp4

### Expected behavior
Either the user should not be allowed to make changes to existing fields or we should inform the user that the currently made changes are not saved when he tries to move to any other section of the page.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome 
* Version: 95.0.4638.69

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #7890 

This PR adds a new modal to warn the users about any unsaved changes when moving to a different step without clicking the continue button.

### Screenshots
Screen Shot 2022-02-08 at 5 23 30 PM

### Detailed test instructions:

1. Start with a fresh install.
2. Navigate to WooCommerce -> Home to start the OBW.
3. Complete a few steps.
4. Click any of the previous steps and make some changes.
5. Click the next/previous step. You should be prompted by the modal to save your changes. Click the save button.
6. Go back to the step and confirm the changes.
7. Repeat the step, but click the disregard button for this time.
8. Confirm the changes are not saved for this time.

### CODE REVIEW

File: client/profile-wizard/header.js [hunk 1]
```diff
@@ -2,11 +2,58 @@
...
+		super( props );
+		this.state = {
+			showUnsavedChangesModal: false,
+		};
+		this.lastClickedStepKey = null;
+	}
+
+	shouldWarnForUnsavedChanges( step ) {
+		if ( typeof this.props.stepValueChanges[ step ] !== 'undefined' ) {
+			return ! isEqual(
```
Comment (rjchow) [inline client/profile-wizard/header.js:25]: There's a small maybe-bug here that results from the lack of canonicalization before comparison here (i.e the order of the objects in an array matter when doing isEqual).

This can be observed in this recording: https://app.replay.io/recording/setup-wizard-woocommerce-woocommerce-admin-woocommerce--2eb22ed1-47bd-432f-abff-50573e883515

Not sure its worth fixing because it'll involve going down the object tree and sorting all the arrays recursively. The impact to UX is quite small IMO, but could leave some users confused when they see the warning and then try restoring all the selection to avoid the warning

File: client/profile-wizard/steps/industry.js [hunk 2]
```diff
@@ -97,16 +107,15 @@ class Industry extends Component {
...
-			goToNextStep();
-		} else {
-			createNotice(
-				'error',
-				__(
-					'There was a problem updating your industries',
-					'woocommerce-admin'
-				)
-			);
+			return true;
```
Comment (rjchow) [inline client/profile-wizard/steps/industry.js:110]: I had a look around but I couldn't determine how this return value is used, and in the other flow  there's no return value. 

There's a .onContinue().then() below  - which would mean that it continues with the .then(goToNextStep()) even when isError == true

Could this be an unintended change?

**Review by rjchow — COMMENTED** [review]
Tests well for the happy path! I noticed some things about the error flow which applies to all of the steps, not sure if its an issue

File: client/profile-wizard/header.js (hunk 1 above)
Comment (moon0326) [reply client/profile-wizard/header.js:25]: Thank you @rjchow That's a good catch. I'll work on fixing it!

Comment (moon0326) [reply client/profile-wizard/header.js]: Updated in https://github.com/woocommerce/woocommerce-admin/pull/8278/commits/6a79a6b6e2ede6643e71cf7c28fa9e89f193e17f and https://github.com/woocommerce/woocommerce-admin/pull/8278/commits/908407df0c93f33ae404bae44e9fd35ba856f5f6

**Review by chihsuan — CHANGES_REQUESTED** [review]
@moon0326 Test well and nice work! 

However, I noticed that [test-lint-js check failed](https://github.com/woocommerce/woocommerce-admin/runs/5131442972?check_suite_focus=true). I also confirmed that on my local with `npm run test:client`. Could you take a look?

**Comment by moon0326** [comment]
> @moon0326 Test well and nice work!
> 
> However, I noticed that [test-lint-js check failed](https://github.com/woocommerce/woocommerce-admin/runs/5131442972?check_suite_focus=true). I also confirmed that on my local with `npm run test:client`. Could you take a look?

Thank you for spotting it. My local tests pass with https://github.com/woocommerce/woocommerce-admin/pull/8278/commits/6ff7d7c8bb200cd6ea36234ee85e8694768768b0 change, but one of them still fails in Github 🤔 

I'll look into it further.

**Comment by moon0326** [comment]
> @moon0326 Test well and nice work!
> 
> However, I noticed that [test-lint-js check failed](https://github.com/woocommerce/woocommerce-admin/runs/5131442972?check_suite_focus=true). I also confirmed that on my local with `npm run test:client`. Could you take a look?

Fixed the tests in https://github.com/woocommerce/woocommerce-admin/pull/8278/commits/4dbb92bada026481296b1628e6476dd936db2cd4

**Review by chihsuan — APPROVED** [review]
Looks good. Thanks! 👍
