### PR TITLE
Fix recommended card Gutenberg CSS conflict

### LINKED ISSUE #7394: [GlobalStep] Menu (Three dots)  button appears misaligned on "Recommended ways to get paid" banner when "Gutenberg" plugin is active.
## Bug Description:
Menu (Three dots) button appears misaligned on "Recommended ways to get paid" banner when "Gutenberg" plugin is active.

## Environment:
WooCommerce Admin: v2.5.0 Beta-2
Woocommerce Version : WooCommerce 5.5.1
WordPress version: (v5.8)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v14.0

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Install and activate WooCommerce Admin 2.5.0 Beta-2. 
1. Install and activate "Gutenberg" plugin.
1. Complete the onboarding setup wizard.
1. Visit Woocommerce > Settings > Payments.
1. Observe that three dot button appears misaligned on "Recommended ways to get paid" banner when "Gutenberg" plugin is active.

## Actual Result:
Menu (Three dots)  button appears misaligned on "Recommended ways to get paid" banner when "Gutenberg" plugin is active.

## Expected Result:
Menu (Three dots) button should be properly aligned on "Recommended ways to get paid" banner when "Gutenberg" plugin is active.

## Screenshot:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.0-beta.2
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.21
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: wp_
Total Database Size: 5.60MB
Database Data Size: 4.08MB
Database Index Size: 1.52MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 27
page: 6
post: 2
product: 21
product_variation: 10
shop_coupon: 5
shop_order: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Jetpack: by Automattic – 9.9.1
WooCommerce Admin: by WooCommerce – 2.5.0-beta.2
WooCommerce: by Automattic – 5.5.1

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Gutenberg: by Gutenberg Team – 11.1.0
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 47
Oldest: 2021-07-21 12:42:54 +0000
Newest: 2021-07-21 13:48:10 +0000

### Status report information ###

Generated at: 2021-07-21 15:08:44 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by ilyasfoo**
Fixes #7394

This PR fixes style conflicts caused by Gutenberg changes.

### Screenshots

image

### Detailed test instructions:

1. Install & activate the latest Gutenberg plugin.
1. Open WooCommerce > Settings > Payments.
2. Wait for a little, and observe the recommended card rendered fine as per screenshot.
3. Optionally, deactivate Gutenberg plugin and observe the card renders correctly as well.

### CODE REVIEW

**Review by louwie17 — CHANGES_REQUESTED** [review]
As discussed in Slack lets omit the `<CardBody` wrapper to forego having to adding `padding: 0 !important`.
Otherwise this tested well.

**Comment by ilyasfoo** [comment]
@louwie17 Addressed in 9a34b62

File: client/payments/payment-recommendations.tsx [hunk 1]
```diff
@@ -221,9 +221,9 @@ const PaymentRecommendations: React.FC = () => {
 					/>
 				</div>
 			</CardHeader>
-			<CardBody>
+			<div>
```
Comment (joshuatf) [inline client/payments/payment-recommendations.tsx:224]: I think we could skip this `div` to avoid an extra tag.  Thoughts?

**Review by joshuatf — COMMENTED** [review]
Thanks for fixing this up, @ilyasfoo!  Left an optional comment about the `div`.  I think we can also remove the body padding changes from `payment-recommendations.scss`:

```scss
	.components-card__body {
		padding: 0;
	}
```

File: client/payments/payment-recommendations.tsx (hunk 1 above)
Comment (ilyasfoo) [reply client/payments/payment-recommendations.tsx]: >I think we can also remove the body padding changes from payment-recommendations.scss.

I was thinking to preserve the structure but I don't think it matters in this case, removed in 54bd850. I've also removed the CSS

**Comment by ilyasfoo** [comment]
Thanks for your suggestions @joshuatf! Addressed all in 54bd850

File: client/payments/payment-recommendations.tsx [hunk 2]
```diff
@@ -221,9 +215,7 @@ const PaymentRecommendations: React.FC = () => {
 					/>
 				</div>
 			</CardHeader>
-			<CardBody>
-				<List items={ pluginsList } />
-			</CardBody>
+			<List items={ pluginsList } />
 			<CardFooter>
```
Comment (louwie17) [inline client/payments/payment-recommendations.tsx:219]: One last thing, the new padding seems to override the footer as well, it defaults to `size-large`.
I think we can remove the CardHeader size, and change the Card size to `medium` instead of `large`.

After doing that you can also remove this line: https://github.com/woocommerce/woocommerce-admin/blob/fa9ed31702e4f104844d8d40f368f84a79a196b9/client/payments/payment-recommendations.scss#L42

**Review by louwie17 — CHANGES_REQUESTED** [review]
Thanks for the changes @ilyasfoo, I requested a couple more 🙈 if you don't mind. They are small.

**Comment by ilyasfoo** [comment]
Thanks for the suggestion @louwie17! I didn't notice the footer was larger earlier. Sharp eye! Changes made 69d1e77

**Review by louwie17 — APPROVED** [review]
> Thanks for the suggestion @louwie17! I didn't notice the footer was larger earlier. Sharp eye! Changes made 69d1e77

Likewise thanks for the changes @ilyasfoo, things look great! This is good to merge 🚀
