### PR TITLE
Don't allow unselecting all items in chart legends

### LINKED ISSUE #383: Prevent user from disabling all series in a chart legend
A user can disable all of the series in the legend resulting in a broken chart. Prevent user from disabling all data in the chart by requiring a minimum of 1 series active (checked) in the legend at all times.

screen recording 2018-09-10 at 09 22 am

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #383.

**Steps to test**
* Go to a page with a chart.
* Try to unselect all items.
* Verify that it's not possible.

### CODE REVIEW

**Review by greenafrican — APPROVED** [review]
Nice one @Aljullu LGTM and tests run fine.

File: client/components/chart/test/legend.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+		total: 100,
+	},
+	{
+		key: 'ipsum',
+		visible: true,
+		total: 100,
+	},
+];
+
+describe( 'Legend', () => {
```
Comment (timmyc) [inline client/components/chart/test/legend.js]: Thanks for the tests 🙌
