### PR TITLE
Add remote inbox notifications contains comparison and fix product count rule

### LINKED ISSUE #5954: Update inbox message link: 💪Your first product message
**Description:** We want to update the CTA link of the message that was implemented in #4223 as now there's an entire guide focused on shipping: https://woocommerce.com/posts/ecommerce-shipping-solutions-guide/?utm_source=inbox

### PR DESCRIPTION
**Pull request by becdetat**
Fixes #5954 and completes #4223

This adds a `contains` (and `!contains`) comparison (so you can do a comparison operation on an array) and fixes the product count rule - it was being triggered at a point where the product count query was one less than the correct value on product add.

The note spec itself is here in the woocommerce.com feed: 9267-gh-woocommerce.com

Note that #5954 is just requesting a change to the URL, however when investigating I realised that the note in #4223 was never actually created, the (considerable) plumbing was designed but never put to use and ticket #4223 was closed and doesn't seem to have been tested.

### Screenshots
image

### Detailed test instructions:

1. You'll need a woocommerce.com instance
2. Check out this branch (9267-gh-woocommerce.com) in your local woocommerce.com instance
3. Delete all of your products
3. Add `http://woocommerce.test/wp-json/wccom/inbox-notifications/1.0/notifications.json` to `DataSourcePoller.php`'s `DATA_SOURCES` arrray
4. `DELETE FROM wp_wc_admin_notes`
5. `DELETE FROM wp_options WHERE option_name IN ('wc_remote_inbox_notifications_specs', 'wc_remote_inbox_notifications_stored_state')`
6. Run the `wc_admin_daily` cron task
7. Check home screen that the new message _is not_ prosent
8. Add a product
9. Check home screen that the new message is now present

### CODE REVIEW

**Comment by louwie17** [comment]
@becdetat the link referenced to Woocommerce.com (9267-gh-woocommerce.com) does not seem to load for me, does it load for you?

**Comment by becdetat** [comment]
@louwie17 it's a tampermonkey shortcode (https://fieldguide.automattic.com/public-github-repo-shorthand/) but it looks like it breaks on the `.com` in the url. Go to the `Automattic/woocommerce.com` repo and find issue 9267.

File: src/RemoteInboxNotifications/StoredStateSetupForProducts.php [hunk 1]
```diff
@@ -93,10 +95,14 @@ public static function run_on_transition_post_status( $new_status, $old_status,
...
 
+		update_option( self::NEW_PRODUCT_COUNT_OPTION_NAME, 1 );
+
 		$stored_state                         = RemoteInboxNotificationsEngine::get_stored_state();
 		$stored_state->there_are_now_products = true;
 		RemoteInboxNotificationsEngine::update_stored_state( $stored_state );
 
 		RemoteInboxNotificationsEngine::run();
+
+		update_option( self::NEW_PRODUCT_COUNT_OPTION_NAME, 0 );
```
Comment (louwie17) [inline src/RemoteInboxNotifications/StoredStateSetupForProducts.php:106]: Not a show stopper, and this could be my lack of understanding of the inbox notification code. But would there also be a way to pass the product count through the `run` or `stored_state` functions instead of using wp option to temporarily store it.
It's not huge, but it always reminds me that another plugin or something could change that in-between.

**Review by louwie17 — APPROVED** [review]
Nice work @becdetat! Tested it, and the note shows up as expected.
Screen Shot 2021-01-18 at 3 20 32 PM

Just left one note, but that isn't a show stopper for me.

File: src/RemoteInboxNotifications/StoredStateSetupForProducts.php (hunk 1 above)
Comment (becdetat) [reply src/RemoteInboxNotifications/StoredStateSetupForProducts.php:106]: Passing it via `stored_state` is a great idea, I'll do that.

Comment (becdetat) [reply src/RemoteInboxNotifications/StoredStateSetupForProducts.php]: Done in 588450c

Comment (louwie17) [reply src/RemoteInboxNotifications/StoredStateSetupForProducts.php]: Awesome, looks good, thanks :)
