### PR TITLE
Task List: Personalize your store / Import products - error message is not formatted correctly

### LINKED ISSUE #4314: Task List: Personalize your store / Import products - error message is not formatted correctly
**Describe the bug**

In `Personalize your store` task after onbaording is completed, if the products import fails, the error message is not being formatted correctly. 

**To Reproduce**

1. Complete new onboarding;
2. On the task list, select `Personalize your store`;
3. On `Import demo products` step, select to import products by clicking on the button;
4. See error message not being formatted correctly showing html tags:

import

**Expected behavior**

The error message should not show html tags. 

**Screenshots**

Above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.4
* Browser: Chrome
* Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context**

N/A.

### PR DESCRIPTION
**Pull request by jacob-sewell**
Fixes #4314 

When an error happens during sample item import, it's likely the error message that comes back from the server will contain HTML tags, which has up to now been just printed on the screen in the notice.

This PR uses the `__unstableHTML` option to preserve markup in messages received from the API when importing sample products. It also adds support for `__unstableHTML` to the `Snackbar` element.

### Screenshots

Before:
9D6B7022-FEE5-47FE-BF7B-73C3688D2F2F_4_5005_c

After:

Default message if the error.message property is falsy:
F5F4648F-820D-4E7D-A9CB-DE7D6EAA42D6_4_5005_c

A specific server-side error message with no markup:
Screen Shot 2022-01-25 at 10 56 33

A specific server-side error message with markup:
Screen Shot 2022-01-25 at 10 57 29

### Detailed test instructions:

-  Go to the "Personalize my store" OBW task
- ...somehow arrange for an Exception to be thrown during the sample import...
- Click "Import Products"
- Verify the formatting of the error message that appears.

### CODE REVIEW

**Comment by jacob-sewell** [comment]
I'm not convinced that this is the right approach here. If we want to preserve the content coming from the server we'll need to either strip its tags (problematic in the case of a link that's now both useless and confusing) or display it in a way that allows the tags to be parsed (doesn't seem to be possible with `createNotice`, so might be out of scope).

Thoughts?

File: client/tasks/fills/appearance.js [hunk 1]
```diff
@@ -137,8 +137,14 @@ class Appearance extends Component {
 				this.setState( { isPending: false } );
 				this.completeStep();
 			} )
-			.catch( ( error ) => {
-				createNotice( 'error', error.message );
+			.catch( () => {
+				createNotice(
+					'error',
+					__(
+						'There was an error importing the sample products',
```
Comment (joshuatf) [inline client/tasks/fills/appearance.js:144]: By removing the `error.message` we remove the ability to get our messages sent from the server, which we currently do use:

https://github.com/woocommerce/woocommerce-admin/blob/4f44222b3d10eeacaeeb50d166e73005a1149e22/src/API/OnboardingTasks.php#L318

We could wrap the `import_sample_products` in a try/catch, but something tells me this error came from JN and I think this can happen anywhere during the REST lifecycle, so that would not fully resolve the issue

File: client/tasks/fills/appearance.js [hunk 2]
```diff
@@ -137,8 +137,14 @@ class Appearance extends Component {
 				this.setState( { isPending: false } );
 				this.completeStep();
 			} )
-			.catch( ( error ) => {
-				createNotice( 'error', error.message );
```
Comment (joshuatf) [inline client/tasks/fills/appearance.js:141]: Another option is to sanitize the HTML or strip tags.  We could strip pretty by creating a div element and grabbing the text content.  A utility function that does this might prove useful.

**Review by joshuatf — COMMENTED** [review]
Nice work on this, Jacob!

This does work, but removes our response error messages.  I'm also guessing this error happens in a lot of places where it occurs from JN sites.

If we want to set this precedent, we might want to look into how we can apply this to all api fetches.

**Comment by mattsherman** [comment]
> If we want to preserve the content coming from the server we'll need to either strip its tags (problematic in the case of a link that's now both useless and confusing) 

Yeah, that would be bad from a UX perspective.

> or display it in a way that allows the tags to be parsed (doesn't seem to be possible with `createNotice`, so might be out of scope).

It looks like this isn't supported by `createNotice` (anymore; [Gutenberg issue](https://github.com/WordPress/gutenberg/issues/17400)), so I agree that is out of scope.

Looking at the bigger picture though...

1. This appears to be the generic error message that gets sent back when an API request fatals. So, it doesn't really provide any useful information for the end user.

I would suggest changing the error message in this case to:

```
There was an unexpected error importing the sample products. Check your site's error logs for more details.
```

2. We should consider opening a followup issue to improve the error handling when we encounter a problem importing the sample data.

**Comment by joshuatf** [comment]
>We should consider opening a followup issue to improve the error handling when we encounter a problem importing the sample data.

I think we do have some error handling as is, but I suspect that this error is higher up in the REST response and more of a JN issue.

That said, generic handling of the WordPress errors might not be a bad thing for all calls.

**Comment by jacob-sewell** [comment]
Thanks @mattsherman and @joshuatf for your thoughts. Lemme see if I can integrate them a little....

What about checking for tags and defaulting to a generic server-side error message if tags are found? That way we could preserve messages we're doing on purpose (e.g. 'the sample products file is not found'), *assuming* they're tagless (which they should be), but catch any errors that are expecting to be inserted directly into HTML.

Alternately, we could whitelist the specific error messages we know about (we should have the same output from `__()` in JS as on the server, right?) and replace anything we don't recognize with a generic server-side error message. (Is there a way to take a string and check whether it appears in a given domain? Then we could effectively whitelist everything that can come out of a `__( ..., 'woocommerce-admin' )` call.)

Do we have a rule about console logging in production? Should I be feeding a message that is about to be overridden into `console.error()` or `console.warn()` so it'll be easy to catch additional messages we might want to whitelist?

**Comment by becdetat** [comment]
I may be completely incorrect but I think notices support HTML if you hack it a bit.

```
createNotice(
    'success',
    'here is a <a href="https://automattic.com">link</a>',
    { __unstableHTML: true }
);
```

Obviously you would only want to do that in certain circumstances where a) you expect that you might get HTML in the message and b) you trust the origin of the message.

In general though I always prefer to never reduce the amount of information in an error message if possible. There's nothing worse than trying to google a generic error message. Especially if you then find out that it's because the actual error message is being clobbered by the UI.

**Comment by joshuatf** [comment]
>Alternately, we could whitelist the specific error messages we know about

This is an interesting idea, but might be a little difficult in practice.  Since the message will have been translated already by the server, we won't be able to have a comprehensive list of messages to catch.

We could watch for `500` response codes as they do tend to be more generic server errors in nature, but we also have some responses with `500` codes that provide more detailed information.

>In general though I always prefer to never reduce the amount of information in an error message if possible. 

I'm with @becdetat on this one.  The more specific and less adulterated message we can provide, the better.

>{ __unstableHTML: true }

This is a good find!  I wonder if using this for all messages would be safe or if we should limit exposure.  If the latter, then we could limit to 500 responses where we can't guarantee the type of response sent by the server.

**Comment by jacob-sewell** [comment]
> > Alternately, we could whitelist the specific error messages we know about
> 
> This is an interesting idea, but might be a little difficult in practice. Since the message will have been translated already by the server, we won't be able to have a comprehensive list of messages to catch.

Can we not count on getting the same output from `__()` on the client side as the server?

> > { __unstableHTML: true }

> This is a good find! I wonder if using this for all messages would be safe or if we should limit exposure. If the latter, then we could limit to `500` responses where we can't guarantee the type of response sent by the server.

Using something that starts with `__unstable` definitely is a red flag. On the other hand, if we're getting malicious markup here it means something's already very wrong.

**Comment by jacob-sewell** [comment]
Thanks to @louwie17 for pointing out why the `__unstableHTML` option wasn't changing the output, and suggesting a way to fix it.

As of this writing this PR will preserve HTML tags in error messages we get from the sample products import API call.

**Review by louwie17 — APPROVED** [review]
Thanks for the updated changes @jacob-sewell, this tested well, nice work!
I am approving, but I was wondering if we should remove the styling on a `p` tag within the snackbar component (only the direct children). Something like this:
```
components-snackbar__content > div > p { margin: 0; padding: 0 }
```
I am not totally set on this, as it doesn't seem like a huge issue, just me being slightly picky on the extra spacing.

Also for reference I added this filter to my `mu-plugin` to product the error:
```
add_filter('woocommerce_product_csv_importer_class', function() {
    throw new \RuntimeException();
    return '';
});
```

**Comment by joshuatf** [comment]
Just noting that we still need a follow-up for this.  This solves the issue in this task, but we would need to do this in all REST API calls since this error has the potential to pop up in any of those.

I would love a more catch-all solution, but this may be the best to handle this.
