### PR TITLE
Increase per_page value for search results on the Analytics pages.

### LINKED ISSUE #6790: Product analytics: Only 10 products shown on "All products with titles that include ..." search instead of all
**Describe the bug**

When trying to get a report of all products sold in a period of time, I often use the feature "All products with titles that include ..." because on my e-commerce the brand name is in the title. But unfortunately I don't get all the products containing that string, but only a subset of it, max 10 products.

Whereas it should display all products containing that particular string.

**To Reproduce**

1. I set up a clean environment with wp-env, latest versions of WP 5.7, WC 5.1.0, WC Stripe gateway 5.1.0 & Storefront 3.5.1.
2. Create 15 products containing a similar string in the title (e.g. "Product A", "Product B", ...)
1. Place 15 orders
2. Make sure all Schedule Actions are completed
3. Go to "Analytics" -> "Products"
4. You should now see the 15 products which have been sold
5. Search for the similar string and select "All products with titles that include ..." (e.g. "Product")
6. Now you only see 10 products

**Expected behavior**

After all these steps, it should display the 15 products

**Screenshots**

- [Before search 15 products are shown](https://user-images.githubusercontent.com/6989959/114524059-2e654f80-9c45-11eb-809f-9a8da5ebb1b9.png)
- [After search only 10 products shown](https://user-images.githubusercontent.com/6989959/114522037-3fad5c80-9c43-11eb-9811-fdd7295e6131.png)

**Screencast**

https://user-images.githubusercontent.com/6989959/114522340-97e45e80-9c43-11eb-8da7-8e869698cade.mp4

**Desktop (please complete the following information):**

* OS: MacOs BigSur 11.2.3
* Browser: Tested on latest versions of Chrome & Firefox

**Additional context**

```
### WordPress Environment ###

WordPress address (URL): http://localhost:8888
Site address (URL): http://localhost:8888
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.4.16
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.9-MariaDB-1:10.5.9+maria~focal
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 3.97MB
Database Data Size: 2.48MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 6
post: 2
product: 15
shop_order: 15

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 5.1.0
WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 50
Oldest: 2021-04-13 07:45:51 +0000
Newest: 2021-04-13 08:16:03 +0000


### Status report information ###

Generated at: 2021-04-13 08:34:57 +00:00
```

### PR DESCRIPTION
**Pull request by moon0326**
Fixes woocommerce/woocommerce-admin#6790 

This PR increases the # of per_page value when a search is performed on the report pages.

This should work for many stores until we implement pagination.

I've opened an [issue](woocommerce/woocommerce#32244) to implement pagination.

Note: Merging this PR will close https://github.com/woocommerce/woocommerce-admin/issues/6790. We should reopen it as this PR doesn't fix the root cause.

### Detailed test instructions:

1. Navigate to Analytics -> Products
2. Open browser inspector
3. Type a keyword in the search input and click "All products with titles that include" link.
4. Click "Network" in your browser inspector and filter by "search"
5. Confirm that the value of `per_page` is `100`

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
I agree to have this fix to temporarily increase supported number of products for this feature. LGTM! 🚢

File: packages/data/src/items/utils.js [hunk 1]
```diff
@@ -77,8 +78,10 @@ export function searchItemsByString( select, endpoint, search ) {
 	search.forEach( ( searchWord ) => {
 		const query = {
 			search: searchWord,
-			per_page: 10,
+			...{ per_page: 10 },
```
Comment (ilyasfoo) [inline packages/data/src/items/utils.js:81]: Sorry a nitpick, I'm not sure though why is this required to be spread? If i'm not mistaken, we could do simply like:
```suggestion
			per_page: 10,
```

Comment (moon0326) [reply packages/data/src/items/utils.js]: Thank you for the catch 👍 I think I was confused with something else when I worked on this 🤦 updated in https://github.com/woocommerce/woocommerce-admin/pull/7385/commits/61f230acb7385c3b7574dbaadc3b5e8281e1a0f0
