### PR TITLE
Convert date to timestamp before passing to set_date_prop to persist …

### LINKED ISSUE #6742: Note dates are not read as UTC and increment on every update
**Describe the bug**
In [`Notes\DataStore::read()`](https://github.com/woocommerce/woocommerce-admin/blob/56f15c85720b764663cf76e3f60ec3a826bb00d2/src/Notes/DataStore.php#L109-L110) date values (`date_created` and `date_reminder`) are passed directly to [`WC_Data::set_date_prop()`](https://github.com/woocommerce/woocommerce/blob/1c40a28409a34b0c47f5167319d99ac6b1ddc779/includes/abstracts/abstract-wc-data.php#L811) causing them to be parsed as local date strings.

One noticeable side-effect is that `date_created` is incremented by the time difference between local and UTC whenever any note prop is updated.

**To Reproduce**
```php
use Automattic\WooCommerce\Admin\Notes\Notes;

for ($i = 0; $i < 5; $i++) {
	$note = Notes::get_note(123);

	echo $note->get_date_created()->format('Y-m-d H:i:s T'), '<br>';

	$note->set_status('actioned');
	$note->save();
}
```
Output:
```
2021-04-04 08:00:00 PDT
2021-04-04 15:00:00 PDT
2021-04-04 22:00:00 PDT
2021-04-05 05:00:00 PDT
2021-04-05 12:00:00 PDT
```

**Expected behavior**
UTC date strings should first be converted to timestamps before being passed through to `WC_Data::set_date_prop()` so that they are handled as UTC instead of local dates.

This is what the the [product data store](https://github.com/woocommerce/woocommerce/blob/1c40a28409a34b0c47f5167319d99ac6b1ddc779/includes/data-stores/class-wc-product-data-store-cpt.php#L174-L175) does for example.

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #6742 

This PR converts the datetime string into timestamp before passing it to `WC_Data::set_date_prop` to prevent the value gets changes.

### Detailed test instructions:

This is a bit confusing to understand at first. Let's reproduce it first to understand what the problem is.

1. Navigate to Settings -> General and change Timezone to UTC-7 for testing purposes.
2. Navigate to WooCommerce -> Home
3. Choose a note and find the note in the D.B
4. Make a note of `date_created` value of the note from the D.B.
5. Dismiss the note by clicking the "Dismiss" button.
6. Go back to the D.B and check   the `date_created` value again. The value has been changed when it should not.

Testing the fix

Checkout this branch and repeat the steps. The `date_created` value should not be changed for this time.

### CODE REVIEW

File: src/Notes/Note.php [hunk 1]
```diff
@@ -503,7 +503,7 @@ public function set_date_created( $date ) {
 			$this->error( 'admin_note_invalid_data', __( 'The admin note date prop cannot be empty.', 'woocommerce-admin' ) );
 		}
 
-		$this->set_date_prop( 'date_created', $date );
+		$this->set_date_prop( 'date_created', wc_string_to_timestamp( $date ) );
```
Comment (mattsherman) [inline src/Notes/Note.php:506]: `wc_string_to_timestamp` says it only accepts a string. But, according to our docs for `set_date_created`, `$date` could be an integer. So, we should account for that.

File: src/Notes/Note.php [hunk 2]
```diff
@@ -512,7 +512,7 @@ public function set_date_created( $date ) {
 	 * @param string|integer|null $date UTC timestamp, or ISO 8601 DateTime. If the DateTime string has no timezone or offset, WordPress site timezone will be assumed. Null if there is no date.
 	 */
 	public function set_date_reminder( $date ) {
-		$this->set_date_prop( 'date_reminder', $date );
+		$this->set_date_prop( 'date_reminder', wc_string_to_timestamp( $date ) );
```
Comment (mattsherman) [inline src/Notes/Note.php:515]: Same comment as above.

**Review by mattsherman — CHANGES_REQUESTED** [review]
It would be good to add some automated testing for this in `WC_Tests_Notes_Data_Store`.

File: src/Notes/Note.php (hunk 1 above)
Comment (moon0326) [reply src/Notes/Note.php:506]: @mattsherman Nice catch! 👍 I will update the code with a test.

Comment (moon0326) [reply src/Notes/Note.php]: @mattsherman  Fixed in https://github.com/woocommerce/woocommerce-admin/pull/6795/commits/e191299a87d7e92d2a69578c8b4b50618f961b8d 

I also created a new test `WC_Tests_Notes_Note` as we're testing behavior of `Note`

File: tests/notes/class-wc-tests-notes-note.php [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+		// Create a new note.
+		$note = new Note();
+		$note->set_title( 'title2' );
+		$note->save();
+
+		// Load it via the data store.
+		$note                         = new Note( $note->get_id() );
+		$date_created_from_first_save = $note->get_date_created()->format( 'Y-m-d H:i:s' );
+		// Save it again.
+		$note->save();
```
Comment (mattsherman) [inline tests/notes/class-wc-tests-notes-note.php:47]: If Note ever optimized its save to only save if it was dirty, this test would do nothing. It would be good to actually change something so that we are assured that it would always save.

**Review by mattsherman — APPROVED** [review]
Thanks for making the changes and adding tests! I have tested and it works as expected.

I've added a few comments regarding potential improvements to make to the the tests, but I'm pre-approving since things are good as is!

File: tests/notes/class-wc-tests-notes-note.php [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+		$note         = new Note( $note->get_id() );
+		$date_created = $note->get_date_created()->format( 'Y-m-d H:i:s' );
+		$this->assertEquals( $expected_date, $date_created );
+	}
+
+	/**
+	 * Tests note correctly saves/loads date_created value
+	 * when it gets saved multiple times.
+	 */
+	public function test_note_correctly_sets_created_date_when_saved() {
```
[the remark this answers is not in the document]
Comment (moon0326) [reply tests/notes/class-wc-tests-notes-note.php:37]: That is a really good point. I will make change 👍

File: tests/notes/class-wc-tests-notes-note.php (hunk 3 above)
Comment (moon0326) [reply tests/notes/class-wc-tests-notes-note.php:47]: Good point 👍 I will make the change.

File: tests/notes/class-wc-tests-notes-note.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (moon0326) [reply tests/notes/class-wc-tests-notes-note.php:37]: @mattsherman done in https://github.com/woocommerce/woocommerce-admin/pull/6795/commits/020277c28690bb145ec5ecde77e9355d82a34d08
