### PR TITLE
Make use of memoization to prevent DynamicForm re-initialization

### LINKED ISSUE #7249: DynamicForm fields prematurely emptied
**Describe the bug**
When completing fields under the new payment gateway suggestions feature and saving, fields can temporarily be seen blank before the request is complete.

Originally noted here - https://github.com/woocommerce/woocommerce-admin/pull/7228#pullrequestreview-692094315

**To Reproduce**

1. Add one of the enhanced gateways.
2. Navigate to the payment task.
3. Fill out the fields and proceed.
4. Note the fields are emptied during save.

**Expected behavior**
Expected the filled in values to stay until the task is completed and no longer visible.

**Screenshots**
123314076-88657980-d500-11eb-81db-2ac2228c902b (1)

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #7249 

Make use of memoization to prevent DynamicForm re-initialization during submission.
This fixes an issue where the form quickly clears before the payment gateway finishes (see GIF).

No changelog as the payment gateway stuff isn't live yet.

### Screenshots

dynamic-form-reset

### Detailed test instructions:

- Add one of the enhanced gateways ([eWay for example](112-gh-woocommerce/woocommerce-gateway-eway) (have to use that branch), using a New Zealand address).
- Navigate to the payment task.
- Fill out the fields and proceed.
- Notice that the fields stay filled in until the redirect.

### CODE REVIEW

File: client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js [hunk 1]
```diff
@@ -94,22 +95,24 @@ export const Connect = ( {
...
+			<DynamicForm
+				fields={ fields }
+				isBusy={ isUpdating }
+				onSubmit={ handleSubmit }
+				submitLabel={ __( 'Proceed', 'woocommerce-admin' ) }
+				validate={ ( values ) => validateFields( values, fields ) }
+				{ ...props }
+			/>
+		);
+	} );
```
Comment (louwie17) [inline client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js:109]: This way we don't re-create the DynamicForm component every time the render method is being called.

File: packages/components/src/dynamic-form/dynamic-form.tsx [hunk 2]
```diff
@@ -50,21 +61,13 @@ export const DynamicForm: React.FC< DynamicFormProps > = ( {
...
-				[ field.id ]:
-					field.type === 'checkbox'
-						? field.value === 'yes'
-						: field.value,
-			} ),
-			{}
-		);
+	const initialValues = useMemo( () => getInitialConfigValues( fields ), [
+		fields,
+	] );
```
Comment (louwie17) [inline packages/components/src/dynamic-form/dynamic-form.tsx:66]: This wasn't required, but thought it would be nice to have.

File: client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js [hunk 3]
```diff
@@ -94,22 +95,24 @@ export const Connect = ( {
...
-		<DynamicForm
-			fields={ fields }
-			isBusy={ isUpdating }
-			onSubmit={ handleSubmit }
-			submitLabel={ __( 'Proceed', 'woocommerce-admin' ) }
-			validate={ ( values ) => validateFields( values, fields ) }
-			{ ...props }
-		/>
-	);
+	const DefaultForm = useRef( ( props ) => {
```
Comment (joshuatf) [inline client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js:98]: `useRef` works here to prevent the re-render, but also prevents props from working here (busy state will no longer work and if fields were updated, they would not work).

File: packages/components/src/dynamic-form/dynamic-form.tsx (hunk 2 above)
Comment (joshuatf) [reply packages/components/src/dynamic-form/dynamic-form.tsx:66]: Nice! 💯

**Review by joshuatf — COMMENTED** [review]
Thanks for jumping on this one, Lourens!  This fix works to resolve the input fields being cleared but prevents the busy state from working.

I'm thinking the solution may be to hold values in state in the `DynamicForm` component.  What do you think?

File: client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js (hunk 3 above)
Comment (louwie17) [reply client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js:98]: Yeah I do agree, `useRef` felled like a dirty fix (but did the trick). I think I will refactor this a bit.

**Comment by louwie17** [comment]
Thanks for the review @joshuatf 

> I'm thinking the solution may be to hold values in state in the `DynamicForm` component. What do you think?

Yeah holding the values within the DynamicForm seems like a good plan.

File: client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js (hunk 3 above)
Comment (louwie17) [reply client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js]: Fixed here, I end up just using the rendered element: https://github.com/woocommerce/woocommerce-admin/pull/7256/commits/f9d5b0a1173aca18a7aea21857c889786724ff8e
This can still be used by using `{ defaultForm }` or `cloneElement(defaultForm, newProps)`.

**Comment by louwie17** [comment]
> I'm thinking the solution may be to hold values in state in the `DynamicForm` component. What do you think?

I end up not doing anything here, as the Form that `DynamicForm` uses already handles the state of the field values. The main issue was the re-generation of the `defaultForm` component.
I changed it slightly so we don't need to use `useRef`.
@joshuatf if you have time for another look

File: packages/onboarding/src/components/WooPaymentGatewayConfigure/README.md [hunk 4]
```diff
@@ -6,7 +6,13 @@ A Slotfill component that will replace the <DynamicForm /> component involved in
 
 ```jsx
 <WooPaymentGatewayConfigure id={ key }>
-  {({defaultForm: DefaultForm}) => <p>Fill Content</p>}
+  {({defaultForm: DefaultForm}) => {
+    return <>
+    <p>Fill Content
```
Comment (joshuatf) [inline packages/onboarding/src/components/WooPaymentGatewayConfigure/README.md:11]: Thanks for updating this 🎉 

The formatting is a little off here, but awesome to expand on this example!

**Review by joshuatf — APPROVED** [review]
Nice!  Sometimes the simple solution is the best solution.

Testing well and LGTM pending one formatting change in the readme.

File: client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.js [hunk 5]
```diff
@@ -151,17 +151,13 @@ export const Setup = ( {
...
-			<Stepper
-				isVertical
-				isPending={ stepperPending }
-				currentStep={ needsPluginInstall ? 'install' : 'configure' }
-				steps={ [ installStep, configureStep ].filter( Boolean ) }
-				{ ...props }
-			/>
-		),
-		[ stepperPending, installStep, configureStep ]
+	const defaultStepper = (
```
Comment (joelclimbsthings) [inline client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.js:154]: Hey @louwie17 & @joshuatf , this change made it so we can't override props for the `<DefaultStepper />` in the slotfill, which I thought was kind of a cool feature. Was that intentional and still desired?
