### PR TITLE
Fix SelectControl focus and de-focus bug

### LINKED ISSUE #6879: OBW wizard resets country to "Afghanistan" when tabbing through fields
**Describe the bug**
When tabbing through the fields in the onboarding wizard, if I select a country, and then again tab through the fields, Afghanistan gets selected overriding my previous selection

**To Reproduce**

1. On the first step of the onboarding wizard, select a country (other than Afghanistan) from the dropdown
2. Use tab / shift+tab to navigate through the form fields, notice that the country you have previously selected gets reset to Afghanistan.

**Expected behavior**
I expected my previous country selection to have been retained.

**Screenshots**

https://user-images.githubusercontent.com/363749/115927158-9a1b9980-a449-11eb-897e-0d24e88df8ae.mov

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome
* Version: 89

### PR DESCRIPTION
**Pull request by ilyasfoo**
Fixes #6879

- Fixes `<SelectControl>` component from unintended selecting the first option when focusing and de-focusing (such as navigating forms via Tab/Shift-Tab).
- Also changes the behaviour to automatically scroll to the currently selected option when the options list is displayed.

### Accessibility

-   [x] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader

### Screenshots

Automatic scroll:

### Detailed test instructions:

1. Navigate to Setup Wizard.
2. Select any country in `Country / Region` except for the first option (Afghanistan).
3. Set focus to `Address line 2` by clicking on the text field.
4. Press `Tab` twice, so that the Country field is focused and de-focused.
5. Observe the selected option did not change to Afghanistan.

### CODE REVIEW

File: packages/components/src/select-control/index.js [hunk 1]
```diff
@@ -25,10 +25,15 @@ const initialState = { isExpanded: false, isFocused: false, query: '' };
...
+
+		const { selected, options } = props;
 		this.state = {
 			...initialState,
 			searchOptions: [],
-			selectedIndex: 0,
+			selectedIndex:
+				selected && options?.length
+					? options.findIndex( ( option ) => option.key === selected )
+					: 0,
```
Comment (jeffstieler) [inline packages/components/src/select-control/index.js:36]: What do you think about defaulting to no selection (`-1`)?

That way, when a user tabs over the control without interacting, nothing is selected unexpectedly.

**Review by jeffstieler — CHANGES_REQUESTED** [review]
Overall this is a great change and does solve #6879, but I think there is an opportunity to refine the UX just a bit.

File: packages/components/src/select-control/index.js [hunk 2]
```diff
@@ -233,7 +249,7 @@ export class SelectControl extends Component {
 			{
 				query,
 				isFocused: true,
-				selectedIndex: 0,
+				selectedIndex: query?.length > 0 ? 0 : this.state.selectedIndex, // Only set to 0 if we're actually searching.
```
[the remark this answers is not in the document]
Comment (ilyasfoo) [reply packages/components/src/select-control/index.js]: That behaviour makes more sense, changes made 168c4c4. Thanks for making the suggestion!

File: packages/components/src/select-control/index.js (hunk 1 above)
Comment (ilyasfoo) [reply packages/components/src/select-control/index.js]: Yep makes sense, changes made in 168c4c4.

File: packages/components/src/select-control/index.js [hunk 3]
```diff
@@ -25,15 +25,10 @@ const initialState = { isExpanded: false, isFocused: false, query: '' };
...
-
-		const { selected, options } = props;
 		this.state = {
 			...initialState,
 			searchOptions: [],
-			selectedIndex:
-				selected && options?.length
-					? options.findIndex( ( option ) => option.key === selected )
-					: 0,
+			selectedIndex: -1,
```
Comment (jeffstieler) [inline packages/components/src/select-control/index.js:31]: This seems to break `SelectControl`s that are supplied a `selected` prop. I think all we need to change from the original code is the `selectedIndex` from `0` to `-1`.

File: packages/components/src/select-control/list.js [hunk 4]
```diff
@@ -116,9 +116,11 @@ class List extends Component {
 				return;
 
 			case TAB:
-				this.select( options[ selectedIndex ] );
-				setExpanded( false );
-				onSearch( null );
+				if ( selectedIndex > -1 ) {
```
Comment (jeffstieler) [inline packages/components/src/select-control/list.js:119]: Given the other changes, I don't think this check is needed.

File: packages/components/src/select-control/test/index.js [hunk 5]
```diff
@@ -260,33 +260,27 @@ describe( 'SelectControl', () => {
...
-					expect(
-						getByRole( 'option', { name: 'bar' } )
-					).toBeInTheDocument()
-				);
-				// In browser, the <Button> in <List> component is automatically "selected" when <Control> lost focus.
-				// I was not able to produce the same behaviour with unit test, but a click on the currently
-				// selected option should be sufficient to simulate the logic in this test.
-				userEvent.click( getByRole( 'option', { selected: true } ) );
-				expect( onChangeMock ).toHaveBeenCalledTimes( 0 );
-			} );
```
Comment (jeffstieler) [inline packages/components/src/select-control/test/index.js]: This test case should still pass, but broke because of the changes to the initial state above.

File: packages/components/src/select-control/test/index.js [hunk 6]
```diff
@@ -260,33 +260,27 @@ describe( 'SelectControl', () => {
...
+		it( 'should not have a selected option on initial render', async () => {
```
Comment (jeffstieler) [inline packages/components/src/select-control/test/index.js:263]: The control _should_ have a selected option on initial render if supplied a `selected` prop that matches an option's `key` should it not?

**Review by jeffstieler — CHANGES_REQUESTED** [review]
Better than before, but I think we introduced some regressions with the initial state changes.

It would probably be beneficial to add a `SelectControl` to the storybook that has a value for the `selected` prop to make sure things are working as expected for that case as well.

File: packages/components/src/select-control/index.js (hunk 3 above)
Comment (ilyasfoo) [reply packages/components/src/select-control/index.js:31]: Sorry Jeff I don't get this one, this change _is from `0` to `-1`_ from the original code. I've also tested a `SelectControl` with `selected` prop given, and seems working fine with mine. If it's possible, maybe you can help to provide an example where it breaks? :pray:

I'll make an update to the storybook to include an example with `selected` as well.

File: packages/components/src/select-control/list.js (hunk 4 above)
Comment (ilyasfoo) [reply packages/components/src/select-control/list.js:119]: Actually we do, since pressing tab on the component will attempt to select anyways. Doesn't break the component but it does prompt an error on [this line](https://github.com/woocommerce/woocommerce-admin/blob/d167204498f57a74b45ae1a668050ed8674d6bb8/packages/components/src/select-control/list.js#L48) since the `option` is `undefined`.

File: packages/components/src/select-control/index.js (hunk 3 above)
Comment (ilyasfoo) [reply packages/components/src/select-control/index.js]: Ah, I misunderstood your original suggestion 🤦 . Changes made in 0890a7b

File: packages/components/src/select-control/test/index.js (hunk 5 above)
Comment (ilyasfoo) [reply packages/components/src/select-control/test/index.js]: True, this is now fixed in 0890a7b

File: packages/components/src/select-control/test/index.js (hunk 6 above)
Comment (ilyasfoo) [reply packages/components/src/select-control/test/index.js]: This test case was the result of my misunderstanding 😅 . I've changed it to `should not automatically select first option on focus`

**Comment by ilyasfoo** [comment]
Thanks for the review @jeffstieler! I've misunderstood your original suggestion, now it should work like what you'd expect. Also made updated the storybook with an example of `selected` prop. Please have another look 🙏 !

**Review by jeffstieler — APPROVED** [review]
This is now working as expected, thanks @ilyasfoo!

Not a blocker for this PR, but there seems to be a more noticeable delay when tabbing out of the control now. I think we're probably doing (and then undoing) some unnecessary work in our `reset()` functionality.

**Comment by ilyasfoo** [comment]
@jeffstieler Thanks for highlighting that! I've decided to look into it and found out that the [`onSearch( null )`](https://github.com/woocommerce/woocommerce-admin/pull/3507/files#diff-1e69220e8f190ce9004b709e77983470ebf919057d810c4c27b0515b26061069R122)  call here might not be necessary which caused the appearance of delay. I've removed it and did not notice any regression from the original PR, nor found anything amiss with tab behaviour in all SelectControl I could find.

On my way towards that, I've also discovered multiple regressions that have been caused by this PR:
1. When we've already selected something, search, then press up or down, it will use the index based on all options instead of the filtered ones.
2. Pressing enter after search triggers an error if nothing is selected.
3. Option list was not hidden on pressing tab without selecting anything even after losing focus on combobox (happened in compare products search).

I've made a PR to fix these and added some tests to go along with it. Hopefully, these tests should capture some of the behaviours that could easily break without us noticing. 

Would appreciate if you can have a look at this one last time!

**Comment by becdetat** [comment]
The speed/delay of tabbing through the control seems good to me atm

**Review by becdetat — APPROVED** [review]
Looks good to me 👍
