### PR TITLE
Skip checking WooCommerce theme support if stylesheet does not exist

### LINKED ISSUE #5740: Onboarding returns fatal error if a child theme is installed under a subdirectory with its parent
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, maybe closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If a theme is installed into a sub-directory **with a child theme**, WooCommerce>Home returns a fatal error like:

```
Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/Users/soner/Downloads/Dev/sites/storefront/app/public/wp-content/themes/storefront): failed to open dir: No such file or directory in /Users/soner/Downloads/Dev/sites/storefront/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 583

UnexpectedValueException: RecursiveDirectoryIterator::__construct(/Users/soner/Downloads/Dev/sites/storefront/app/public/wp-content/themes/storefront): failed to open dir: No such file or directory in /Users/soner/Downloads/Dev/sites/storefront/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 583
```
It doesn't matter the parent or the child theme is active, it returns the same error. But, if you remove the child theme, it starts working again even the parent theme is still under a subfolder.

**Expected behavior**
WooCommerce>Home shouldn't return a fatal error because the themes are installed in a subfolder.

**Actual behavior**
WooCommerce>Home returns a fatal error when a theme and its child theme installed into a subfolder.
(For example wp-content/themes/storefront-theme/storefront & wp-content/themes/storefront-theme/storefront-child)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Install Storefront and an empty child theme for Storefront into a storefront-theme subfolder.
2. Activate one of the themes (parent, child, or another theme like Twenty Twenty).
3. Navigate to WooCommerce>Home.
4. See the error below an empty page.

**Screenshots**

Screen Shot 2020-11-23 at 18 23 08

Safari Screenshot 2020-11-23 18 40 14

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report, we won't be able to fully evaluate this issue.
<details>

```
### WordPress Environment ###

WordPress address (URL): https://storefront.kalonya
Site address (URL): https://storefront.kalonya
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 3.81MB
Database Data Size: 2.41MB
Database Index Size: 1.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 8
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Classic Editor: by WordPress Contributors – 1.6
Really Simple SSL: by Really Simple Plugins – 3.3.5
WooCommerce: by Automattic – 4.7.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: woocommerce/woocommerce#6 - /shop/
Cart: woocommerce/woocommerce#7 - /cart/
Checkout: woocommerce/woocommerce#8 - /checkout/
My account: woocommerce/woocommerce#9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.9.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2020-11-23 17:28:07 +0000
Newest: 2020-11-23 17:29:29 +0000
```

</details>

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #5740 

This PR fixes a fatal error when a child theme is installed in a subdirectory and the subdirectory does not have a stylesheet file.

### Detailed test instructions:

Please enable both `WP_DEBUG` and `WP_DEBUG_LOG` from the `wp-config.php` before starting.

Confirm the error without this branch.

1. Create a fresh installation of WordPress + WooCommerce
2. Create `storefront-theme` directory in /wp-content/themes directory.
3. Create an empty child theme in the `storefront-theme`. I've attached a child theme for testing purposes.  [storefront-child-theme.zip](https://github.com/woocommerce/woocommerce-admin/files/5626451/storefront-child-theme.zip). Your themes folder should look like the following.
Screen Shot 2020-12-02 at 1 49 22 PM

4. Navigate to WooCommerce -> Home
5. Open a terminal and cd to WordPress. Check the error by running `tail -f wp-content/debug.log`

Change your branch to this PR and repeat the process. The fatal error should be gone.

### CODE REVIEW

**Comment by joelclimbsthings** [comment]
Hey @moon0326 , I spent some time trying to reproduce this but didn't have any luck on my local. I created a fresh site, installed WooCommerce, and then followed the steps as you outlined. 


> * Create `storefront-theme` directory in /wp-content/themes directory.
> 
> * Create an empty child theme in the `storefront-theme`. I've attached a child theme for testing purposes.  [storefront-child-theme.zip](https://github.com/woocommerce/woocommerce-admin/files/5626451/storefront-child-theme.zip)
> 
> * Navigate to WooCommerce -> Home

But I'm not getting any kind of error. I also tried installing the actual Storefront theme and embedding the child theme within that directory with no error.

Does this require any particular version?

I'm running WP 5.5.3 & WC 4.7.1 (with the embedded WC Admin 1.6.3)

**Comment by moon0326** [comment]
Hey @joelclimbsthings, thank you for the test! This does not require a particular version, but it requires a specific folder structure. I've attached my folder structure.

You also need to make sure to have a fresh DB or delete `_transient_timeout_wc_onboarding_themes` from the `wp_options` table.

I also noticed that it's not clear that you are getting an error on some pages. Please enable `WP_DEBUG` and `WP_DEBUG_LOG` from `wp-config.php` and tail `wp-content/debug.log` for the error messages. I will update the PR with this information.

Screen Shot 2020-12-02 at 1 49 22 PM

File: src/Features/Onboarding.php [hunk 1]
```diff
@@ -574,7 +574,11 @@ public static function has_woocommerce_support( $theme ) {
 		}
 
 		foreach ( $themes as $theme ) {
-			$directory = new \RecursiveDirectoryIterator( $theme->theme_root . '/' . $theme->stylesheet );
+			$stylesheet_file = $theme->theme_root . '/' . $theme->stylesheet;
+			if ( ! file_exists( $stylesheet_file ) ) {
+				continue;
+			}
```
Comment (joelclimbsthings) [inline src/Features/Onboarding.php:580]: So, just to clarify; it looks like if a stylesheet is not present, the theme is more-or-less ignored for the purposes of checking for WooCommerce support? Assuming that's the behavior we want, this looks good to me :+1:

**Review by joelclimbsthings — CHANGES_REQUESTED** [review]

**Comment by joelclimbsthings** [comment]
Thanks @moon0326 , looks like my folder structure wasn't quite right! I managed to reproduce the error, and it disappeared when activating this branch of the WooCommerce plugin :+1: . I had one quick question just for clarity, but LGTM.

File: src/Features/Onboarding.php (hunk 1 above)
Comment (moon0326) [reply src/Features/Onboarding.php:580]: @joelclimbsthings Yup, that's the case. This is somewhat edge case since people usually don't structure a theme directory in such a way and even the [official doc](https://developer.wordpress.org/themes/advanced-topics/child-themes/) recommends putting a child theme at the top level. Thank you for the review 👍

**Review by joelclimbsthings — APPROVED** [review]
:shipit:
